# words_data_2.py  — second batch (~1900 more words)

WORDS2 = [

# ══════════════════════════════════════════════
#  A1  —  more core vocabulary
# ══════════════════════════════════════════════

# Numbers as words
("null", "", "zero", "Null ist eine Zahl.", "Zero is a number.", "numbers", "A1"),
("eins", "", "one", "Eins plus eins ist zwei.", "One plus one is two.", "numbers", "A1"),
("zwei", "", "two", "Ich habe zwei Hunde.", "I have two dogs.", "numbers", "A1"),
("drei", "", "three", "Wir sind drei Personen.", "We are three people.", "numbers", "A1"),
("vier", "", "four", "Das Tisch hat vier Beine.", "The table has four legs.", "numbers", "A1"),
("fünf", "", "five", "Ich habe fünf Finger.", "I have five fingers.", "numbers", "A1"),
("sechs", "", "six", "Das Würfel hat sechs Seiten.", "The dice has six sides.", "numbers", "A1"),
("sieben", "", "seven", "Die Woche hat sieben Tage.", "The week has seven days.", "numbers", "A1"),
("acht", "", "eight", "Es ist acht Uhr.", "It is eight o'clock.", "numbers", "A1"),
("neun", "", "nine", "Neun minus drei ist sechs.", "Nine minus three is six.", "numbers", "A1"),
("zehn", "", "ten", "Ich zähle bis zehn.", "I count to ten.", "numbers", "A1"),
("zwanzig", "", "twenty", "Ich bin zwanzig Jahre alt.", "I am twenty years old.", "numbers", "A1"),
("hundert", "", "hundred", "Ein Meter hat hundert Zentimeter.", "One metre has a hundred centimetres.", "numbers", "A1"),
("tausend", "", "thousand", "Ein Kilometer hat tausend Meter.", "One kilometre has a thousand metres.", "numbers", "A1"),

# Greetings / basics
("Hallo", "", "hello", "Hallo! Wie geht es dir?", "Hello! How are you?", "misc", "A1"),
("Tschüss", "", "bye / goodbye", "Tschüss! Bis morgen!", "Bye! See you tomorrow!", "misc", "A1"),
("Danke", "", "thank you", "Danke für deine Hilfe!", "Thank you for your help!", "misc", "A1"),
("Bitte", "", "please / you're welcome", "Bitte, setz dich!", "Please, sit down!", "misc", "A1"),
("Entschuldigung", "die", "excuse me / apology", "Entschuldigung, wo ist der Bahnhof?", "Excuse me, where is the station?", "misc", "A1"),
("Ja", "", "yes", "Ja, ich komme.", "Yes, I'm coming.", "misc", "A1"),
("Nein", "", "no", "Nein, danke.", "No, thank you.", "misc", "A1"),
("Willkommen", "", "welcome", "Willkommen in Deutschland!", "Welcome to Germany!", "misc", "A1"),

# More places
("Land", "das", "country / land", "Deutschland ist ein Land.", "Germany is a country.", "travel", "A1"),
("Deutschland", "", "Germany", "Ich lebe in Deutschland.", "I live in Germany.", "travel", "A1"),
("Österreich", "", "Austria", "Wien ist in Österreich.", "Vienna is in Austria.", "travel", "A1"),
("Schweiz", "die", "Switzerland", "Die Schweiz ist schön.", "Switzerland is beautiful.", "travel", "A1"),
("Europa", "", "Europe", "Europa hat viele Länder.", "Europe has many countries.", "travel", "A1"),
("Welt", "die", "world", "Die Welt ist groß.", "The world is big.", "misc", "A1"),

# More body parts
("Herz", "das", "heart", "Das Herz schlägt schnell.", "The heart beats fast.", "body", "A1"),
("Gehirn", "das", "brain", "Das Gehirn denkt.", "The brain thinks.", "body", "A2"),
("Hals", "der", "neck / throat", "Mein Hals tut weh.", "My throat hurts.", "body", "A1"),
("Schulter", "die", "shoulder", "Sie zuckt mit den Schultern.", "She shrugs.", "body", "A2"),
("Knie", "das", "knee", "Das Knie ist verletzt.", "The knee is injured.", "body", "A2"),
("Zahn", "der", "tooth", "Der Zahn tut weh.", "The tooth hurts.", "body", "A1"),
("Zunge", "die", "tongue", "Die Zunge schmeckt.", "The tongue tastes.", "body", "A2"),
("Lunge", "die", "lung", "Die Lunge atmet.", "The lung breathes.", "body", "B1"),
("Blut", "das", "blood", "Das Blut ist rot.", "Blood is red.", "body", "A2"),
("Haut", "die", "skin", "Die Haut ist weich.", "The skin is soft.", "body", "A2"),
("Haar", "das", "hair", "Das Haar ist lang.", "The hair is long.", "body", "A1"),

# More home items
("Schrank", "der", "wardrobe / cupboard", "Der Schrank ist voll.", "The wardrobe is full.", "home", "A2"),
("Regal", "das", "shelf", "Das Regal ist aus Holz.", "The shelf is made of wood.", "home", "A2"),
("Spiegel", "der", "mirror", "Ich schaue in den Spiegel.", "I look in the mirror.", "home", "A2"),
("Waschmaschine", "die", "washing machine", "Die Waschmaschine läuft.", "The washing machine is running.", "home", "A2"),
("Kühlschrank", "der", "fridge / refrigerator", "Der Kühlschrank ist kalt.", "The fridge is cold.", "home", "A2"),
("Herd", "der", "cooker / stove", "Der Herd ist heiß.", "The stove is hot.", "home", "A2"),
("Ofen", "der", "oven", "Der Ofen backt.", "The oven is baking.", "home", "A2"),
("Mikrowelle", "die", "microwave", "Ich wärme es in der Mikrowelle.", "I heat it in the microwave.", "home", "A2"),
("Teppich", "der", "carpet / rug", "Der Teppich ist weich.", "The carpet is soft.", "home", "A2"),
("Vorhang", "der", "curtain", "Der Vorhang ist geschlossen.", "The curtain is closed.", "home", "A2"),
("Decke", "die", "ceiling / blanket", "Die Decke ist weiß.", "The ceiling is white.", "home", "A2"),
("Boden", "der", "floor / ground / soil", "Der Boden ist sauber.", "The floor is clean.", "home", "A1"),
("Wand", "die", "wall", "Das Bild hängt an der Wand.", "The picture hangs on the wall.", "home", "A1"),
("Treppe", "die", "stairs / staircase", "Die Treppe ist steil.", "The stairs are steep.", "home", "A2"),
("Keller", "der", "cellar / basement", "Der Keller ist kühl.", "The cellar is cool.", "home", "A2"),
("Dach", "das", "roof", "Das Dach ist kaputt.", "The roof is broken.", "home", "A2"),
("Garten", "der", "garden", "Der Garten blüht.", "The garden is in bloom.", "home", "A1"),
("Garage", "die", "garage", "Das Auto steht in der Garage.", "The car is in the garage.", "home", "A2"),
("Briefkasten", "der", "letterbox / mailbox", "Der Brief ist im Briefkasten.", "The letter is in the letterbox.", "home", "A2"),

# More food
("Schokolade", "die", "chocolate", "Ich liebe Schokolade.", "I love chocolate.", "food", "A1"),
("Keks", "der", "biscuit / cookie", "Der Keks ist süß.", "The biscuit is sweet.", "food", "A1"),
("Eis", "das", "ice cream / ice", "Das Eis ist kalt.", "The ice cream is cold.", "food", "A1"),
("Marmelade", "die", "jam", "Marmelade auf Brot ist lecker.", "Jam on bread is delicious.", "food", "A1"),
("Honig", "der", "honey", "Honig ist süß.", "Honey is sweet.", "food", "A1"),
("Nuss", "die", "nut", "Die Nuss ist hart.", "The nut is hard.", "food", "A2"),
("Erdbeere", "die", "strawberry", "Die Erdbeere ist rot.", "The strawberry is red.", "food", "A2"),
("Kirsche", "die", "cherry", "Die Kirsche ist lecker.", "The cherry is delicious.", "food", "A2"),
("Birne", "die", "pear", "Die Birne ist süß.", "The pear is sweet.", "food", "A2"),
("Traube", "die", "grape", "Die Traube ist saftig.", "The grape is juicy.", "food", "A2"),
("Zitrone", "die", "lemon", "Die Zitrone ist sauer.", "The lemon is sour.", "food", "A2"),
("Gurke", "die", "cucumber", "Die Gurke ist grün.", "The cucumber is green.", "food", "A2"),
("Karotte", "die", "carrot", "Die Karotte ist orange.", "The carrot is orange.", "food", "A2"),
("Zwiebel", "die", "onion", "Die Zwiebel riecht stark.", "The onion smells strong.", "food", "A2"),
("Knoblauch", "der", "garlic", "Knoblauch ist gesund.", "Garlic is healthy.", "food", "A2"),
("Paprika", "die", "pepper / paprika", "Die Paprika ist bunt.", "The pepper is colourful.", "food", "A2"),
("Spinat", "der", "spinach", "Spinat ist grün und gesund.", "Spinach is green and healthy.", "food", "A2"),
("Bohne", "die", "bean", "Bohnen sind reich an Protein.", "Beans are rich in protein.", "food", "A2"),
("Linse", "die", "lentil", "Linsen sind lecker.", "Lentils are delicious.", "food", "B1"),
("Hähnchen", "das", "chicken (meat)", "Ich esse gern Hähnchen.", "I like eating chicken.", "food", "A2"),
("Wurst", "die", "sausage", "Die Wurst ist typisch deutsch.", "The sausage is typically German.", "food", "A1"),
("Schinken", "der", "ham", "Schinken schmeckt gut.", "Ham tastes good.", "food", "A2"),
("Joghurt", "der", "yoghurt", "Joghurt ist gesund.", "Yoghurt is healthy.", "food", "A2"),
("Sahne", "die", "cream", "Mit Sahne ist es lecker.", "With cream it is delicious.", "food", "A2"),
("Mehl", "das", "flour", "Mehl brauche ich zum Backen.", "I need flour for baking.", "food", "A2"),
("Öl", "das", "oil", "Ich koche mit Öl.", "I cook with oil.", "food", "A2"),
("Essig", "der", "vinegar", "Essig macht Salat lecker.", "Vinegar makes salad tasty.", "food", "A2"),
("Gewürz", "das", "spice", "Das Gewürz ist scharf.", "The spice is hot.", "food", "A2"),
("Pfeffer", "der", "pepper (spice)", "Pfeffer macht es scharf.", "Pepper makes it spicy.", "food", "A2"),
("Zimt", "der", "cinnamon", "Zimt riecht gut.", "Cinnamon smells nice.", "food", "B1"),
("Vanille", "die", "vanilla", "Vanille ist süß.", "Vanilla is sweet.", "food", "B1"),
("Snack", "der", "snack", "Ich esse einen kleinen Snack.", "I eat a small snack.", "food", "A2"),
("Portion", "die", "portion", "Eine große Portion bitte!", "A large portion please!", "food", "A2"),
("Rezept", "das", "recipe", "Das Rezept ist einfach.", "The recipe is simple.", "food", "A2"),
("Zutaten", "", "ingredients (plural)", "Die Zutaten sind frisch.", "The ingredients are fresh.", "food", "A2"),
("Speisekarte", "die", "menu", "Darf ich die Speisekarte sehen?", "May I see the menu?", "food", "A2"),

# More animals
("Hase", "der", "rabbit / hare", "Der Hase springt.", "The rabbit jumps.", "animals", "A1"),
("Kaninchen", "das", "rabbit (pet)", "Das Kaninchen ist niedlich.", "The rabbit is cute.", "animals", "A1"),
("Hamster", "der", "hamster", "Der Hamster schläft.", "The hamster is sleeping.", "animals", "A1"),
("Papagei", "der", "parrot", "Der Papagei spricht.", "The parrot talks.", "animals", "A2"),
("Schildkröte", "die", "turtle / tortoise", "Die Schildkröte ist langsam.", "The turtle is slow.", "animals", "A2"),
("Schlange", "die", "snake", "Die Schlange ist lang.", "The snake is long.", "animals", "A2"),
("Frosch", "der", "frog", "Der Frosch quakt.", "The frog croaks.", "animals", "A2"),
("Biene", "die", "bee", "Die Biene macht Honig.", "The bee makes honey.", "animals", "A2"),
("Schmetterling", "der", "butterfly", "Der Schmetterling ist bunt.", "The butterfly is colourful.", "animals", "A2"),
("Ameise", "die", "ant", "Die Ameise ist fleißig.", "The ant is hardworking.", "animals", "A2"),
("Spinne", "die", "spider", "Die Spinne spinnt.", "The spider spins.", "animals", "A2"),
("Fliege", "die", "fly", "Die Fliege fliegt.", "The fly flies.", "animals", "A2"),
("Mücke", "die", "mosquito", "Die Mücke sticht.", "The mosquito stings.", "animals", "A2"),
("Ente", "die", "duck", "Die Ente schwimmt.", "The duck swims.", "animals", "A1"),
("Huhn", "das", "chicken / hen", "Das Huhn legt Eier.", "The hen lays eggs.", "animals", "A1"),
("Gans", "die", "goose", "Die Gans ist weiß.", "The goose is white.", "animals", "A2"),
("Schaf", "das", "sheep", "Das Schaf ist weiß.", "The sheep is white.", "animals", "A1"),
("Ziege", "die", "goat", "Die Ziege frisst Gras.", "The goat eats grass.", "animals", "A2"),
("Esel", "der", "donkey", "Der Esel ist stur.", "The donkey is stubborn.", "animals", "A2"),
("Wolf", "der", "wolf", "Der Wolf heult.", "The wolf howls.", "animals", "A2"),
("Fuchs", "der", "fox", "Der Fuchs ist schlau.", "The fox is clever.", "animals", "A2"),
("Reh", "das", "deer / roe deer", "Das Reh rennt weg.", "The deer runs away.", "animals", "A2"),
("Hirsch", "der", "stag / deer", "Der Hirsch hat Geweih.", "The stag has antlers.", "animals", "B1"),
("Delfin", "der", "dolphin", "Der Delfin ist klug.", "The dolphin is clever.", "animals", "A2"),
("Wal", "der", "whale", "Der Wal ist riesig.", "The whale is huge.", "animals", "A2"),
("Hai", "der", "shark", "Der Hai ist gefährlich.", "The shark is dangerous.", "animals", "A2"),
("Adler", "der", "eagle", "Der Adler fliegt hoch.", "The eagle flies high.", "animals", "A2"),
("Eule", "die", "owl", "Die Eule ist nachtaktiv.", "The owl is nocturnal.", "animals", "A2"),
("Pinguin", "der", "penguin", "Der Pinguin kann nicht fliegen.", "The penguin cannot fly.", "animals", "A2"),
("Zebra", "das", "zebra", "Das Zebra hat Streifen.", "The zebra has stripes.", "animals", "A2"),
("Giraffe", "die", "giraffe", "Die Giraffe hat einen langen Hals.", "The giraffe has a long neck.", "animals", "A2"),
("Krokodil", "das", "crocodile", "Das Krokodil ist gefährlich.", "The crocodile is dangerous.", "animals", "A2"),
("Nashorn", "das", "rhinoceros", "Das Nashorn ist stark.", "The rhinoceros is strong.", "animals", "B1"),
("Gorilla", "der", "gorilla", "Der Gorilla ist stark.", "The gorilla is strong.", "animals", "B1"),
("Kamel", "das", "camel", "Das Kamel lebt in der Wüste.", "The camel lives in the desert.", "animals", "A2"),

# Months
("Januar", "der", "January", "Januar ist kalt.", "January is cold.", "time", "A1"),
("Februar", "der", "February", "Im Februar schneit es.", "In February it snows.", "time", "A1"),
("März", "der", "March", "Im März beginnt der Frühling.", "In March spring begins.", "time", "A1"),
("April", "der", "April", "April macht was er will.", "April does what it wants.", "time", "A1"),
("Mai", "der", "May", "Im Mai ist es warm.", "In May it is warm.", "time", "A1"),
("Juni", "der", "June", "Juni ist der sechste Monat.", "June is the sixth month.", "time", "A1"),
("Juli", "der", "July", "Im Juli machen wir Urlaub.", "In July we go on holiday.", "time", "A1"),
("August", "der", "August", "August ist der heißeste Monat.", "August is the hottest month.", "time", "A1"),
("September", "der", "September", "Im September beginnt die Schule.", "In September school starts.", "time", "A1"),
("Oktober", "der", "October", "Oktober ist bunt.", "October is colourful.", "time", "A1"),
("November", "der", "November", "November ist grau.", "November is grey.", "time", "A1"),
("Dezember", "der", "December", "Im Dezember ist Weihnachten.", "In December is Christmas.", "time", "A1"),

# Seasons
("Frühling", "der", "spring", "Im Frühling blühen Blumen.", "In spring flowers bloom.", "time", "A1"),
("Sommer", "der", "summer", "Im Sommer ist es heiß.", "In summer it is hot.", "time", "A1"),
("Herbst", "der", "autumn / fall", "Im Herbst fallen die Blätter.", "In autumn the leaves fall.", "time", "A1"),
("Winter", "der", "winter", "Im Winter schneit es.", "In winter it snows.", "time", "A1"),

# More time
("Uhrzeit", "die", "time (of day)", "Wie ist die Uhrzeit?", "What time is it?", "time", "A1"),
("Nachmittag", "der", "afternoon", "Am Nachmittag mache ich Sport.", "In the afternoon I do sport.", "time", "A1"),
("Abend", "der", "evening", "Guten Abend!", "Good evening!", "time", "A1"),
("Morgen", "der", "morning", "Guten Morgen!", "Good morning!", "time", "A1"),
("Nacht", "die", "night", "Gute Nacht!", "Good night!", "time", "A1"),
("Mittag", "der", "noon / midday", "Mittags esse ich.", "At noon I eat.", "time", "A1"),
("Mitternacht", "die", "midnight", "Um Mitternacht ist es still.", "At midnight it is quiet.", "time", "A2"),
("früh", "", "early", "Ich stehe früh auf.", "I get up early.", "time", "A1"),
("spät", "", "late", "Es ist schon spät.", "It is already late.", "time", "A1"),
("immer", "", "always", "Er kommt immer zu spät.", "He always arrives late.", "adverbs", "A1"),
("nie", "", "never", "Ich esse nie Fleisch.", "I never eat meat.", "adverbs", "A1"),
("manchmal", "", "sometimes", "Manchmal bin ich müde.", "Sometimes I am tired.", "adverbs", "A1"),
("oft", "", "often", "Ich gehe oft ins Kino.", "I often go to the cinema.", "adverbs", "A1"),
("selten", "", "rarely / seldom", "Ich gehe selten aus.", "I rarely go out.", "adverbs", "A2"),
("schon", "", "already", "Ich bin schon fertig.", "I am already finished.", "adverbs", "A1"),
("noch", "", "still / yet", "Ich bin noch hier.", "I am still here.", "adverbs", "A1"),
("bald", "", "soon", "Wir kommen bald.", "We are coming soon.", "adverbs", "A1"),
("danach", "", "afterwards / then", "Danach gehe ich schlafen.", "Afterwards I go to sleep.", "adverbs", "A2"),
("vorher", "", "before / previously", "Vorher hatte ich keine Zeit.", "Before I had no time.", "adverbs", "A2"),
("zuerst", "", "first / at first", "Zuerst esse ich.", "First I eat.", "adverbs", "A2"),
("dann", "", "then / next", "Dann gehen wir.", "Then we go.", "adverbs", "A1"),
("schließlich", "", "finally / eventually", "Schließlich haben wir es geschafft.", "Finally we managed it.", "adverbs", "B1"),
("sofort", "", "immediately", "Komm sofort!", "Come immediately!", "adverbs", "A2"),
("überall", "", "everywhere", "Das gibt es überall.", "That exists everywhere.", "adverbs", "A2"),
("nirgendwo", "", "nowhere", "Es ist nirgendwo zu finden.", "It is nowhere to be found.", "adverbs", "B1"),
("irgendwo", "", "somewhere", "Er ist irgendwo draußen.", "He is somewhere outside.", "adverbs", "B1"),
("hier", "", "here", "Ich bin hier.", "I am here.", "adverbs", "A1"),
("da", "", "there / then", "Das Buch ist da.", "The book is there.", "adverbs", "A1"),
("dort", "", "there (more distant)", "Dort steht ein Baum.", "There stands a tree.", "adverbs", "A1"),
("oben", "", "above / up / upstairs", "Das Buch ist oben.", "The book is above.", "adverbs", "A1"),
("unten", "", "below / down / downstairs", "Die Katze ist unten.", "The cat is downstairs.", "adverbs", "A1"),
("links", "", "left", "Bieg links ab!", "Turn left!", "adverbs", "A1"),
("rechts", "", "right", "Das Haus ist rechts.", "The house is on the right.", "adverbs", "A1"),
("geradeaus", "", "straight ahead", "Geh geradeaus!", "Go straight ahead!", "adverbs", "A1"),
("nah", "", "near / close", "Das Café ist nah.", "The café is near.", "adjectives", "A1"),
("weit", "", "far / wide", "Der Bahnhof ist weit.", "The station is far.", "adjectives", "A1"),
("draußen", "", "outside", "Die Kinder spielen draußen.", "The children play outside.", "adverbs", "A1"),
("drinnen", "", "inside", "Es ist warm drinnen.", "It is warm inside.", "adverbs", "A1"),

# More A1 verbs
("laufen", "", "to run / walk", "Ich laufe jeden Morgen.", "I run every morning.", "verbs", "A1"),
("stehen", "", "to stand", "Er steht an der Tür.", "He stands at the door.", "verbs", "A1"),
("sitzen", "", "to sit", "Sie sitzt auf dem Stuhl.", "She sits on the chair.", "verbs", "A1"),
("liegen", "", "to lie (down)", "Das Buch liegt auf dem Tisch.", "The book lies on the table.", "verbs", "A1"),
("hängen", "", "to hang", "Das Bild hängt an der Wand.", "The picture hangs on the wall.", "verbs", "A1"),
("stellen", "", "to place / put (upright)", "Ich stelle das Glas hin.", "I place the glass down.", "verbs", "A1"),
("legen", "", "to lay / put (flat)", "Ich lege das Buch hin.", "I lay the book down.", "verbs", "A1"),
("setzen", "", "to set / place / sit", "Setz dich!", "Sit down!", "verbs", "A1"),
("tanzen", "", "to dance", "Sie tanzt gut.", "She dances well.", "verbs", "A1"),
("singen", "", "to sing", "Er singt laut.", "He sings loudly.", "verbs", "A1"),
("malen", "", "to paint / draw", "Das Kind malt ein Bild.", "The child paints a picture.", "verbs", "A1"),
("zeichnen", "", "to draw", "Ich zeichne ein Haus.", "I draw a house.", "verbs", "A1"),
("rechnen", "", "to calculate", "Ich rechne die Summe.", "I calculate the sum.", "verbs", "A1"),
("zählen", "", "to count", "Zähl bis zehn!", "Count to ten!", "verbs", "A1"),
("suchen", "", "to search / look for", "Ich suche meinen Schlüssel.", "I am looking for my key.", "verbs", "A1"),
("anrufen", "", "to call (by phone)", "Ich rufe dich an.", "I will call you.", "verbs", "A2"),
("aufmachen", "", "to open", "Mach die Tür auf!", "Open the door!", "verbs", "A1"),
("zumachen", "", "to close", "Mach das Fenster zu!", "Close the window!", "verbs", "A1"),
("aufstehen", "", "to get up / stand up", "Ich stehe um 7 auf.", "I get up at 7.", "verbs", "A1"),
("einschlafen", "", "to fall asleep", "Das Baby schläft ein.", "The baby falls asleep.", "verbs", "A2"),
("aufwachen", "", "to wake up", "Ich wache früh auf.", "I wake up early.", "verbs", "A2"),
("anziehen", "", "to put on (clothes)", "Ich ziehe mich an.", "I get dressed.", "verbs", "A2"),
("ausziehen", "", "to take off (clothes)", "Zieh die Schuhe aus!", "Take off your shoes!", "verbs", "A2"),
("waschen", "", "to wash", "Ich wasche mir die Hände.", "I wash my hands.", "verbs", "A1"),
("duschen", "", "to shower", "Ich dusche jeden Tag.", "I shower every day.", "verbs", "A2"),
("kochen", "", "to cook / boil", "Ich koche Wasser.", "I boil water.", "verbs", "A1"),
("backen", "", "to bake", "Ich backe Kuchen.", "I bake cake.", "verbs", "A2"),
("schneiden", "", "to cut", "Schneid das Brot!", "Cut the bread!", "verbs", "A2"),
("probieren", "", "to try / taste", "Probier das mal!", "Try that!", "verbs", "A2"),
("bezahlen", "", "to pay", "Ich bezahle die Rechnung.", "I pay the bill.", "verbs", "A2"),
("klingeln", "", "to ring (bell)", "Es klingelt an der Tür.", "The doorbell is ringing.", "verbs", "A2"),
("schicken", "", "to send", "Ich schicke eine E-Mail.", "I send an email.", "verbs", "A2"),
("empfangen", "", "to receive", "Ich empfange Post.", "I receive post.", "verbs", "A2"),
("einladen", "", "to invite", "Ich lade dich ein.", "I invite you.", "verbs", "A2"),
("feiern", "", "to celebrate", "Wir feiern Geburtstag.", "We celebrate a birthday.", "verbs", "A2"),
("schenken", "", "to give (as a gift)", "Ich schenke dir ein Buch.", "I give you a book as a gift.", "verbs", "A2"),
("vergessen", "", "to forget", "Ich vergesse immer den Schlüssel.", "I always forget the key.", "verbs", "A2"),
("erinnern", "", "to remember / remind", "Ich erinnere mich.", "I remember.", "verbs", "A2"),
("wiederholen", "", "to repeat / revise", "Wiederhole den Satz!", "Repeat the sentence!", "verbs", "A2"),
("üben", "", "to practise", "Ich übe täglich Deutsch.", "I practise German daily.", "verbs", "A2"),
("prüfen", "", "to check / test", "Ich prüfe die Antwort.", "I check the answer.", "verbs", "A2"),
("wählen", "", "to choose / vote", "Wähl eine Option!", "Choose an option!", "verbs", "A2"),
("empfehlen", "", "to recommend", "Ich empfehle das Restaurant.", "I recommend the restaurant.", "verbs", "B1"),
("bestellen", "", "to order", "Ich bestelle einen Kaffee.", "I order a coffee.", "verbs", "A2"),
("reservieren", "", "to reserve / book", "Ich reserviere einen Tisch.", "I reserve a table.", "verbs", "A2"),
("mieten", "", "to rent", "Ich miete ein Zimmer.", "I rent a room.", "verbs", "B1"),
("vermieten", "", "to let / rent out", "Er vermietet eine Wohnung.", "He rents out a flat.", "verbs", "B1"),
("umziehen", "", "to move (house)", "Wir ziehen um.", "We are moving house.", "verbs", "B1"),
("reparieren", "", "to repair", "Ich repariere das Auto.", "I repair the car.", "verbs", "A2"),
("bauen", "", "to build", "Wir bauen ein Haus.", "We build a house.", "verbs", "A2"),
("messen", "", "to measure", "Ich messe die Temperatur.", "I measure the temperature.", "verbs", "B1"),
("wiegen", "", "to weigh", "Das Paket wiegt 2 kg.", "The package weighs 2 kg.", "verbs", "B1"),
("füllen", "", "to fill", "Füll das Glas!", "Fill the glass!", "verbs", "A2"),
("leeren", "", "to empty", "Leere den Mülleimer!", "Empty the bin!", "verbs", "A2"),
("putzen", "", "to clean / brush", "Ich putze die Zähne.", "I brush my teeth.", "verbs", "A1"),
("aufräumen", "", "to tidy up", "Räum dein Zimmer auf!", "Tidy up your room!", "verbs", "A1"),
("sammeln", "", "to collect / gather", "Ich sammle Briefmarken.", "I collect stamps.", "verbs", "A2"),
("sortieren", "", "to sort", "Sortier die Bücher!", "Sort the books!", "verbs", "A2"),
("organisieren", "", "to organise", "Ich organisiere das Treffen.", "I organise the meeting.", "verbs", "B1"),
("planen", "", "to plan", "Wir planen eine Reise.", "We plan a trip.", "verbs", "A2"),
("starten", "", "to start / launch", "Das Programm startet.", "The programme starts.", "verbs", "A2"),
("stoppen", "", "to stop", "Stopp das Auto!", "Stop the car!", "verbs", "A2"),
("kontrollieren", "", "to control / check", "Ich kontrolliere die Arbeit.", "I check the work.", "verbs", "B1"),
("reagieren", "", "to react", "Wie reagierst du?", "How do you react?", "verbs", "B1"),
("handeln", "", "to act / trade", "Wir müssen jetzt handeln.", "We must act now.", "verbs", "B1"),
("lösen", "", "to solve / loosen", "Ich löse das Problem.", "I solve the problem.", "verbs", "B1"),
("prüfen", "", "to check / examine", "Der Arzt prüft mich.", "The doctor examines me.", "verbs", "B1"),
("wechseln", "", "to change / swap", "Ich wechsle das Hemd.", "I change my shirt.", "verbs", "B1"),
("tauschen", "", "to exchange / swap", "Wir tauschen die Plätze.", "We swap places.", "verbs", "B1"),
("teilen", "", "to share / divide", "Wir teilen das Essen.", "We share the food.", "verbs", "A2"),
("verbinden", "", "to connect / join", "Verbinde die Punkte!", "Connect the dots!", "verbs", "B1"),
("trennen", "", "to separate", "Trenn die Wäsche!", "Separate the laundry!", "verbs", "B1"),
("beenden", "", "to finish / end", "Beende die Aufgabe!", "Finish the task!", "verbs", "B1"),
("beginnen", "", "to begin / start", "Wir beginnen jetzt.", "We begin now.", "verbs", "A2"),
("dauern", "", "to last / take (time)", "Das dauert lange.", "That takes a long time.", "verbs", "A2"),
("passen", "", "to fit / suit", "Die Hose passt nicht.", "The trousers don't fit.", "verbs", "A2"),
("gefallen", "", "to please / like", "Das gefällt mir.", "I like that.", "verbs", "A2"),
("fehlen", "", "to be missing / to miss", "Du fehlst mir.", "I miss you.", "verbs", "A2"),
("kennen", "", "to know (a person/place)", "Ich kenne ihn gut.", "I know him well.", "verbs", "A1"),
("kennenlernen", "", "to get to know", "Ich lerne sie kennen.", "I get to know her.", "verbs", "A2"),
("vorstellen", "", "to introduce / imagine", "Darf ich mich vorstellen?", "May I introduce myself?", "verbs", "A2"),
("informieren", "", "to inform", "Ich informiere dich.", "I will inform you.", "verbs", "B1"),
("berichten", "", "to report", "Der Journalist berichtet.", "The journalist reports.", "verbs", "B1"),
("erzählen", "", "to tell / narrate", "Er erzählt eine Geschichte.", "He tells a story.", "verbs", "A2"),
("zuhören", "", "to listen", "Hör mir zu!", "Listen to me!", "verbs", "A2"),
("antworten", "", "to answer / reply", "Antwort auf meine Frage!", "Answer my question!", "verbs", "A1"),
("bitten", "", "to ask / request", "Ich bitte um Hilfe.", "I ask for help.", "verbs", "A2"),
("erlauben", "", "to allow / permit", "Das ist erlaubt.", "That is allowed.", "verbs", "B1"),
("verbieten", "", "to forbid / ban", "Das ist verboten.", "That is forbidden.", "verbs", "B1"),
("empfehlen", "", "to recommend", "Ich empfehle dieses Buch.", "I recommend this book.", "verbs", "B1"),
("vorschlagen", "", "to suggest", "Ich schlage vor, zu gehen.", "I suggest going.", "verbs", "B1"),
("zustimmen", "", "to agree", "Ich stimme zu.", "I agree.", "verbs", "B1"),
("ablehnen", "", "to reject / decline", "Sie lehnt das Angebot ab.", "She declines the offer.", "verbs", "B1"),
("akzeptieren", "", "to accept", "Ich akzeptiere das.", "I accept that.", "verbs", "B1"),
("kritisieren", "", "to criticise", "Er kritisiert meine Arbeit.", "He criticises my work.", "verbs", "B2"),
("loben", "", "to praise", "Der Lehrer lobt den Schüler.", "The teacher praises the pupil.", "verbs", "B1"),
("warnen", "", "to warn", "Ich warne dich!", "I warn you!", "verbs", "B1"),
("drohen", "", "to threaten", "Er droht mir.", "He threatens me.", "verbs", "B2"),
("versprechen", "", "to promise", "Ich verspreche es.", "I promise.", "verbs", "B1"),
("lügen", "", "to lie", "Er lügt immer.", "He always lies.", "verbs", "B1"),
("zweifeln", "", "to doubt", "Ich zweifle daran.", "I doubt that.", "verbs", "B1"),
("vermuten", "", "to suspect / assume", "Ich vermute, dass...", "I suspect that...", "verbs", "B1"),
("bemerken", "", "to notice", "Ich bemerke das.", "I notice that.", "verbs", "B1"),
("erkennen", "", "to recognise", "Ich erkenne das Muster.", "I recognise the pattern.", "verbs", "B1"),
("untersuchen", "", "to examine / investigate", "Wir untersuchen das Problem.", "We investigate the problem.", "verbs", "B2"),
("prüfen", "", "to test / verify", "Ich prüfe die Fakten.", "I verify the facts.", "verbs", "B1"),
("messen", "", "to measure", "Wir messen den Abstand.", "We measure the distance.", "verbs", "B1"),
("berechnen", "", "to calculate", "Ich berechne den Preis.", "I calculate the price.", "verbs", "B1"),
("schätzen", "", "to estimate / appreciate", "Ich schätze deine Hilfe.", "I appreciate your help.", "verbs", "B1"),
("bewerten", "", "to evaluate / rate", "Bewerte das Produkt!", "Rate the product!", "verbs", "B2"),
("auswählen", "", "to select / choose", "Wähle eine Option aus!", "Select an option!", "verbs", "B1"),
("kombinieren", "", "to combine", "Ich kombiniere die Farben.", "I combine the colours.", "verbs", "B2"),
("anpassen", "", "to adapt / adjust", "Ich passe mich an.", "I adapt.", "verbs", "B2"),
("optimieren", "", "to optimise", "Wir optimieren den Prozess.", "We optimise the process.", "verbs", "C1"),
("automatisieren", "", "to automate", "Wir automatisieren die Aufgabe.", "We automate the task.", "verbs", "C1"),
("digitalisieren", "", "to digitalise", "Alles wird digitalisiert.", "Everything is being digitalised.", "verbs", "B2"),
("speichern", "", "to save / store", "Ich speichere die Datei.", "I save the file.", "verbs", "B1"),
("löschen", "", "to delete / extinguish", "Ich lösche die Datei.", "I delete the file.", "verbs", "B1"),
("herunterladen", "", "to download", "Ich lade die App herunter.", "I download the app.", "verbs", "B1"),
("hochladen", "", "to upload", "Ich lade das Foto hoch.", "I upload the photo.", "verbs", "B1"),
("installieren", "", "to install", "Ich installiere das Programm.", "I install the programme.", "verbs", "B1"),
("aktualisieren", "", "to update", "Ich aktualisiere das System.", "I update the system.", "verbs", "B1"),
("verbessern", "", "to improve", "Ich verbessere meine Kenntnisse.", "I improve my knowledge.", "verbs", "B1"),

# ══════════════════════════════════════════════
# More nouns — school, work, travel, misc
# ══════════════════════════════════════════════

("Bleistift", "der", "pencil", "Ich schreibe mit dem Bleistift.", "I write with the pencil.", "school", "A1"),
("Radiergummi", "der", "eraser / rubber", "Ich brauche einen Radiergummi.", "I need an eraser.", "school", "A1"),
("Lineal", "das", "ruler", "Das Lineal ist 30 cm lang.", "The ruler is 30 cm long.", "school", "A1"),
("Schere", "die", "scissors", "Die Schere schneidet gut.", "The scissors cut well.", "school", "A1"),
("Kleber", "der", "glue", "Der Kleber haftet gut.", "The glue sticks well.", "school", "A1"),
("Pinsel", "der", "paintbrush", "Der Pinsel ist nass.", "The paintbrush is wet.", "school", "A1"),
("Farbe", "die", "colour / paint", "Welche Farbe magst du?", "What colour do you like?", "colors", "A1"),
("Papier", "das", "paper", "Das Papier ist weiß.", "The paper is white.", "school", "A1"),
("Mappe", "die", "folder / portfolio", "Die Mappe ist voll.", "The folder is full.", "school", "A2"),
("Rucksack", "der", "rucksack / backpack", "Der Rucksack ist schwer.", "The rucksack is heavy.", "school", "A1"),
("Tornister", "der", "school bag", "Der Tornister ist neu.", "The school bag is new.", "school", "A1"),
("Hausaufgabe", "die", "homework", "Ich mache Hausaufgaben.", "I do homework.", "school", "A1"),
("Stundenplan", "der", "timetable", "Der Stundenplan hängt an der Wand.", "The timetable hangs on the wall.", "school", "A2"),
("Pause", "die", "break / pause", "In der Pause esse ich.", "During the break I eat.", "school", "A1"),
("Schulhof", "der", "school yard / playground", "Die Kinder spielen auf dem Schulhof.", "The children play in the school yard.", "school", "A1"),
("Direktor", "der", "headteacher / director (m)", "Der Direktor spricht.", "The headteacher speaks.", "school", "A2"),
("Direktorin", "die", "headteacher / director (f)", "Die Direktorin ist streng.", "The headteacher is strict.", "school", "A2"),
("Zeugnis", "das", "school report / certificate", "Das Zeugnis ist gut.", "The school report is good.", "school", "A2"),
("Abitur", "das", "A-levels / school-leaving exam", "Ich mache Abitur.", "I am doing my A-levels.", "school", "B1"),
("Studium", "das", "studies / degree", "Das Studium dauert drei Jahre.", "The degree takes three years.", "school", "B1"),
("Vorlesung", "die", "lecture", "Die Vorlesung beginnt um 9.", "The lecture starts at 9.", "school", "B1"),
("Hausarbeit", "die", "essay / housework", "Ich schreibe eine Hausarbeit.", "I write an essay.", "school", "B2"),
("Diplomarbeit", "die", "thesis / diploma work", "Die Diplomarbeit ist fertig.", "The thesis is finished.", "school", "C1"),

# Work
("Angestellte", "der/die", "employee", "Die Angestellte arbeitet hart.", "The employee works hard.", "work", "B1"),
("Beamte", "der", "civil servant (m)", "Der Beamte arbeitet im Amt.", "The civil servant works in the office.", "work", "B1"),
("Unternehmen", "das", "company / enterprise", "Das Unternehmen wächst.", "The company is growing.", "work", "B1"),
("Abteilung", "die", "department", "Die Abteilung ist groß.", "The department is large.", "work", "B1"),
("Besprechung", "die", "meeting / discussion", "Ich habe eine Besprechung.", "I have a meeting.", "work", "B1"),
("Protokoll", "das", "minutes / record", "Das Protokoll ist fertig.", "The minutes are finished.", "work", "B2"),
("Bewerbung", "die", "application (job)", "Ich schreibe eine Bewerbung.", "I write a job application.", "work", "B1"),
("Lebenslauf", "der", "CV / résumé", "Mein Lebenslauf ist aktuell.", "My CV is up to date.", "work", "B1"),
("Vorstellungsgespräch", "das", "job interview", "Das Vorstellungsgespräch war gut.", "The job interview went well.", "work", "B2"),
("Kündigung", "die", "resignation / dismissal", "Die Kündigung kam überraschend.", "The dismissal came unexpectedly.", "work", "B2"),
("Überstunden", "", "overtime (plural)", "Ich mache Überstunden.", "I do overtime.", "work", "B1"),
("Urlaub", "der", "holiday (time off)", "Ich nehme Urlaub.", "I take holiday.", "work", "A2"),
("Lohn", "der", "wage", "Der Lohn ist niedrig.", "The wage is low.", "work", "B1"),
("Steuer", "die", "tax", "Die Steuern sind hoch.", "Taxes are high.", "work", "B2"),
("Rechnung", "die", "invoice / bill", "Die Rechnung bitte!", "The bill please!", "work", "A2"),
("Angebot", "das", "offer / deal", "Das Angebot ist gut.", "The offer is good.", "work", "B1"),
("Auftrag", "der", "order / commission", "Ich habe einen Auftrag.", "I have a commission.", "work", "B1"),
("Lieferung", "die", "delivery", "Die Lieferung kommt morgen.", "The delivery comes tomorrow.", "work", "B2"),
("Produkt", "das", "product", "Das Produkt ist neu.", "The product is new.", "work", "A2"),
("Service", "der", "service", "Der Service ist gut.", "The service is good.", "work", "A2"),
("Kunde", "der", "customer (m)", "Der Kunde ist zufrieden.", "The customer is satisfied.", "work", "A2"),
("Kundschaft", "die", "customers / clientele", "Die Kundschaft wächst.", "The clientele is growing.", "work", "B2"),

# Transport
("Flugzeug", "das", "aeroplane", "Das Flugzeug fliegt hoch.", "The aeroplane flies high.", "travel", "A1"),
("Schiff", "das", "ship / boat", "Das Schiff fährt langsam.", "The ship sails slowly.", "travel", "A2"),
("U-Bahn", "die", "underground / metro", "Ich fahre U-Bahn.", "I take the underground.", "travel", "A2"),
("Straßenbahn", "die", "tram", "Die Straßenbahn kommt.", "The tram is coming.", "travel", "A2"),
("Taxi", "das", "taxi", "Ich nehme ein Taxi.", "I take a taxi.", "travel", "A2"),
("Motorrad", "das", "motorcycle", "Das Motorrad ist schnell.", "The motorcycle is fast.", "travel", "A2"),
("Roller", "der", "scooter", "Ich fahre Roller.", "I ride a scooter.", "travel", "A2"),
("Lastwagen", "der", "lorry / truck", "Der Lastwagen ist groß.", "The lorry is large.", "travel", "A2"),
("Ampel", "die", "traffic light", "Die Ampel ist rot.", "The traffic light is red.", "travel", "A2"),
("Autobahn", "die", "motorway / highway", "Auf der Autobahn ist Stau.", "There is a traffic jam on the motorway.", "travel", "A2"),
("Parkplatz", "der", "car park / parking space", "Der Parkplatz ist voll.", "The car park is full.", "travel", "A2"),
("Tankstelle", "die", "petrol station", "Die Tankstelle ist in der Nähe.", "The petrol station is nearby.", "travel", "A2"),
("Landkarte", "die", "map (geographical)", "Die Landkarte zeigt Europa.", "The map shows Europe.", "travel", "A2"),
("Kompass", "der", "compass", "Der Kompass zeigt Norden.", "The compass points north.", "travel", "A2"),
("Norden", "der", "north", "Berlin liegt im Norden.", "Berlin is in the north.", "travel", "A2"),
("Süden", "der", "south", "München liegt im Süden.", "Munich is in the south.", "travel", "A2"),
("Osten", "der", "east", "Die Sonne geht im Osten auf.", "The sun rises in the east.", "travel", "A2"),
("Westen", "der", "west", "Im Westen wird es Abend.", "In the west it becomes evening.", "travel", "A2"),
("Entfernung", "die", "distance", "Die Entfernung ist groß.", "The distance is large.", "travel", "B1"),
("Strecke", "die", "route / distance", "Die Strecke ist lang.", "The route is long.", "travel", "B1"),
("Abfahrt", "die", "departure", "Die Abfahrt ist um 8.", "The departure is at 8.", "travel", "A2"),
("Ankunft", "die", "arrival", "Die Ankunft ist um 10.", "The arrival is at 10.", "travel", "A2"),
("Verspätung", "die", "delay", "Der Zug hat Verspätung.", "The train is delayed.", "travel", "A2"),
("Gleis", "das", "platform / track", "Der Zug ist auf Gleis 3.", "The train is on platform 3.", "travel", "A2"),
("Gepäck", "das", "luggage", "Das Gepäck ist schwer.", "The luggage is heavy.", "travel", "A2"),
("Buchung", "die", "booking / reservation", "Die Buchung ist bestätigt.", "The booking is confirmed.", "travel", "B1"),
("Unterkunft", "die", "accommodation", "Die Unterkunft ist günstig.", "The accommodation is affordable.", "travel", "B1"),
("Gasthaus", "das", "inn / guesthouse", "Das Gasthaus ist gemütlich.", "The inn is cosy.", "travel", "A2"),
("Jugendherberge", "die", "youth hostel", "Die Jugendherberge ist billig.", "The youth hostel is cheap.", "travel", "A2"),
("Rezeption", "die", "reception", "An der Rezeption bekomme ich den Schlüssel.", "At reception I get the key.", "travel", "A2"),
("Zimmer", "das", "room", "Das Zimmer hat einen Balkon.", "The room has a balcony.", "travel", "A1"),
("Einzelzimmer", "das", "single room", "Ein Einzelzimmer, bitte.", "A single room, please.", "travel", "A2"),
("Doppelzimmer", "das", "double room", "Ein Doppelzimmer ist günstiger.", "A double room is cheaper.", "travel", "A2"),

# Nature / Environment
("Pflanze", "die", "plant", "Die Pflanze braucht Wasser.", "The plant needs water.", "nature", "A2"),
("Gras", "das", "grass", "Das Gras ist grün.", "The grass is green.", "nature", "A1"),
("Blatt", "das", "leaf / sheet", "Das Blatt fällt.", "The leaf falls.", "nature", "A2"),
("Ast", "der", "branch", "Der Ast ist dick.", "The branch is thick.", "nature", "A2"),
("Wurzel", "die", "root", "Die Wurzel ist tief.", "The root is deep.", "nature", "B1"),
("Stein", "der", "stone / rock", "Der Stein ist schwer.", "The stone is heavy.", "nature", "A1"),
("Sand", "der", "sand", "Der Sand ist heiß.", "The sand is hot.", "nature", "A1"),
("Erde", "die", "earth / soil", "Die Erde ist fruchtbar.", "The soil is fertile.", "nature", "A1"),
("Tal", "das", "valley", "Das Tal ist grün.", "The valley is green.", "nature", "A2"),
("Hügel", "der", "hill", "Der Hügel ist steil.", "The hill is steep.", "nature", "A2"),
("Küste", "die", "coast", "Die Küste ist schön.", "The coast is beautiful.", "nature", "A2"),
("Strand", "der", "beach", "Der Strand ist sandig.", "The beach is sandy.", "nature", "A2"),
("Wüste", "die", "desert", "Die Wüste ist heiß.", "The desert is hot.", "nature", "A2"),
("Dschungel", "der", "jungle", "Der Dschungel ist dicht.", "The jungle is dense.", "nature", "A2"),
("Wiese", "die", "meadow", "Die Wiese ist grün.", "The meadow is green.", "nature", "A2"),
("Feld", "das", "field", "Das Feld ist groß.", "The field is large.", "nature", "A2"),
("Bauernhof", "der", "farm", "Der Bauernhof ist groß.", "The farm is large.", "nature", "A2"),
("Luft", "die", "air", "Die Luft ist frisch.", "The air is fresh.", "nature", "A1"),
("Feuer", "das", "fire", "Das Feuer ist heiß.", "The fire is hot.", "nature", "A1"),
("Eis", "das", "ice", "Das Eis ist glatt.", "The ice is slippery.", "nature", "A1"),
("Frost", "der", "frost", "Es gibt Frost heute Nacht.", "There is frost tonight.", "nature", "B1"),
("Nebel", "der", "fog / mist", "Der Nebel ist dicht.", "The fog is thick.", "nature", "B1"),
("Gewitter", "das", "thunderstorm", "Das Gewitter ist stark.", "The thunderstorm is strong.", "nature", "B1"),
("Blitz", "der", "lightning / flash", "Der Blitz leuchtet.", "The lightning flashes.", "nature", "B1"),
("Donner", "der", "thunder", "Der Donner rollt.", "The thunder rolls.", "nature", "B1"),
("Regenbogen", "der", "rainbow", "Der Regenbogen ist bunt.", "The rainbow is colourful.", "nature", "A2"),
("Temperatur", "die", "temperature", "Die Temperatur sinkt.", "The temperature drops.", "nature", "A2"),
("Grad", "der", "degree", "Es sind 20 Grad.", "It is 20 degrees.", "nature", "A2"),
("Sonnenschein", "der", "sunshine", "Im Sonnenschein ist es warm.", "In the sunshine it is warm.", "nature", "A2"),
("Wasserfall", "der", "waterfall", "Der Wasserfall ist schön.", "The waterfall is beautiful.", "nature", "A2"),
("Quelle", "die", "spring / source", "Die Quelle ist frisch.", "The spring is fresh.", "nature", "B1"),
("Bach", "der", "stream / brook", "Der Bach fließt ruhig.", "The stream flows quietly.", "nature", "A2"),
("Teich", "der", "pond", "Der Teich ist klar.", "The pond is clear.", "nature", "A2"),

# Health & Medical
("Tablette", "die", "tablet / pill", "Nimm eine Tablette!", "Take a tablet!", "health", "A2"),
("Spritze", "die", "injection / syringe", "Die Spritze tut weh.", "The injection hurts.", "health", "B1"),
("Verband", "der", "bandage", "Der Verband ist nötig.", "The bandage is necessary.", "health", "B1"),
("Wunde", "die", "wound", "Die Wunde blutet.", "The wound is bleeding.", "health", "B1"),
("Allergie", "die", "allergy", "Ich habe eine Allergie.", "I have an allergy.", "health", "B1"),
("Impfung", "die", "vaccination", "Eine Impfung schützt.", "A vaccination protects.", "health", "B1"),
("Operation", "die", "operation / surgery", "Die Operation war erfolgreich.", "The operation was successful.", "health", "B1"),
("Therapie", "die", "therapy", "Die Therapie hilft.", "The therapy helps.", "health", "B1"),
("Diagnose", "die", "diagnosis", "Die Diagnose ist klar.", "The diagnosis is clear.", "health", "B2"),
("Symptom", "das", "symptom", "Das Symptom ist deutlich.", "The symptom is clear.", "health", "B2"),
("Husten", "der", "cough", "Ich habe Husten.", "I have a cough.", "health", "A2"),
("Schnupfen", "der", "cold (runny nose)", "Ich habe Schnupfen.", "I have a cold.", "health", "A2"),
("Erkältung", "die", "cold (illness)", "Ich habe eine Erkältung.", "I have a cold.", "health", "A2"),
("Grippe", "die", "flu / influenza", "Ich habe die Grippe.", "I have the flu.", "health", "B1"),
("Kopfschmerzen", "", "headache (plural)", "Ich habe Kopfschmerzen.", "I have a headache.", "health", "A2"),
("Bauchschmerzen", "", "stomach ache (plural)", "Ich habe Bauchschmerzen.", "I have a stomach ache.", "health", "A2"),
("Blutdruck", "der", "blood pressure", "Der Blutdruck ist hoch.", "The blood pressure is high.", "health", "B1"),
("Herzkrankheit", "die", "heart disease", "Herzkrankheit ist verbreitet.", "Heart disease is common.", "health", "C1"),
("Diabetes", "der", "diabetes", "Er hat Diabetes.", "He has diabetes.", "health", "B2"),
("Stress", "der", "stress", "Stress schadet der Gesundheit.", "Stress is bad for health.", "health", "A2"),
("Depression", "die", "depression", "Depression ist behandelbar.", "Depression is treatable.", "health", "B2"),
("Schlaflosigkeit", "die", "insomnia", "Schlaflosigkeit ist quälend.", "Insomnia is tormenting.", "health", "B2"),
("Übergewicht", "das", "overweight", "Übergewicht ist ungesund.", "Being overweight is unhealthy.", "health", "B2"),
("Diät", "die", "diet", "Ich mache eine Diät.", "I am on a diet.", "health", "B1"),
("Apotheke", "die", "pharmacy", "Ich gehe zur Apotheke.", "I go to the pharmacy.", "health", "A2"),
("Rezept", "das", "prescription (also: recipe)", "Ich brauche ein Rezept.", "I need a prescription.", "health", "A2"),
("Blutprobe", "die", "blood test", "Die Blutprobe zeigt alles.", "The blood test shows everything.", "health", "B2"),

# Technology
("Smartphone", "das", "smartphone", "Mein Smartphone ist neu.", "My smartphone is new.", "tech", "A2"),
("Tablet", "das", "tablet (device)", "Das Tablet ist praktisch.", "The tablet is practical.", "tech", "A2"),
("Laptop", "der", "laptop", "Mein Laptop ist kaputt.", "My laptop is broken.", "tech", "A2"),
("Tastatur", "die", "keyboard", "Die Tastatur ist ergonomisch.", "The keyboard is ergonomic.", "tech", "B1"),
("Bildschirm", "der", "screen / monitor", "Der Bildschirm ist groß.", "The screen is large.", "tech", "B1"),
("Maus", "die", "computer mouse", "Die Maus funktioniert nicht.", "The mouse doesn't work.", "tech", "A2"),
("Drucker", "der", "printer", "Der Drucker druckt schnell.", "The printer prints fast.", "tech", "A2"),
("Kamera", "die", "camera", "Die Kamera macht gute Fotos.", "The camera takes good photos.", "tech", "A2"),
("Fernseher", "der", "television (set)", "Der Fernseher ist groß.", "The television is large.", "tech", "A2"),
("Radio", "das", "radio", "Das Radio spielt Musik.", "The radio plays music.", "tech", "A2"),
("Lautsprecher", "der", "speaker", "Der Lautsprecher ist laut.", "The speaker is loud.", "tech", "B1"),
("Kopfhörer", "der", "headphones", "Ich benutze Kopfhörer.", "I use headphones.", "tech", "A2"),
("Kabel", "das", "cable / wire", "Das Kabel ist lang.", "The cable is long.", "tech", "A2"),
("Stecker", "der", "plug", "Der Stecker passt nicht.", "The plug doesn't fit.", "tech", "B1"),
("Batterie", "die", "battery", "Die Batterie ist leer.", "The battery is empty.", "tech", "A2"),
("Strom", "der", "electricity / current", "Der Strom fließt.", "The electricity flows.", "tech", "B1"),
("Netz", "das", "network / net", "Das Netz ist schnell.", "The network is fast.", "tech", "B1"),
("App", "die", "app", "Die App ist kostenlos.", "The app is free.", "tech", "A2"),
("Software", "die", "software", "Die Software ist aktuell.", "The software is up to date.", "tech", "B1"),
("Hardware", "die", "hardware", "Die Hardware ist gut.", "The hardware is good.", "tech", "B1"),
("Passwort", "das", "password", "Das Passwort ist sicher.", "The password is secure.", "tech", "A2"),
("Benutzername", "der", "username", "Mein Benutzername ist...", "My username is...", "tech", "A2"),
("E-Mail", "die", "email", "Ich schreibe eine E-Mail.", "I write an email.", "tech", "A1"),
("Datei", "die", "file", "Die Datei ist groß.", "The file is large.", "tech", "B1"),
("Ordner", "der", "folder", "Der Ordner ist voll.", "The folder is full.", "tech", "B1"),
("Virus", "der", "virus (computer)", "Der Virus ist gefährlich.", "The virus is dangerous.", "tech", "B1"),
("Update", "das", "update", "Das Update läuft.", "The update is running.", "tech", "A2"),
("Website", "die", "website", "Die Website ist übersichtlich.", "The website is clear.", "tech", "A2"),
("Blog", "der", "blog", "Ich schreibe einen Blog.", "I write a blog.", "tech", "A2"),
("Algorithmus", "der", "algorithm", "Der Algorithmus ist komplex.", "The algorithm is complex.", "tech", "C1"),
("künstliche Intelligenz", "die", "artificial intelligence", "Künstliche Intelligenz verändert alles.", "Artificial intelligence changes everything.", "tech", "C1"),

# Sports & Leisure
("Turnen", "das", "gymnastics", "Turnen macht stark.", "Gymnastics makes you strong.", "sports", "B1"),
("Leichtathletik", "die", "athletics", "Leichtathletik ist vielfältig.", "Athletics is diverse.", "sports", "B1"),
("Basketball", "der", "basketball", "Basketball ist mein Sport.", "Basketball is my sport.", "sports", "A2"),
("Volleyball", "der", "volleyball", "Volleyball macht Spaß.", "Volleyball is fun.", "sports", "A2"),
("Tennis", "das", "tennis", "Tennis ist ein eleganter Sport.", "Tennis is an elegant sport.", "sports", "A2"),
("Tischtennis", "das", "table tennis", "Tischtennis spiele ich gern.", "I like playing table tennis.", "sports", "A2"),
("Golf", "das", "golf", "Golf erfordert Geduld.", "Golf requires patience.", "sports", "B1"),
("Boxen", "das", "boxing", "Boxen ist ein Kampfsport.", "Boxing is a combat sport.", "sports", "B1"),
("Radfahren", "das", "cycling", "Radfahren ist gesund.", "Cycling is healthy.", "sports", "A2"),
("Wandern", "das", "hiking", "Wandern in den Bergen.", "Hiking in the mountains.", "sports", "A2"),
("Klettern", "das", "climbing", "Klettern macht Spaß.", "Climbing is fun.", "sports", "B1"),
("Skifahren", "das", "skiing", "Skifahren liebe ich.", "I love skiing.", "sports", "A2"),
("Reiten", "das", "horse riding", "Reiten ist toll.", "Horse riding is great.", "sports", "B1"),
("Segeln", "das", "sailing", "Segeln auf dem See.", "Sailing on the lake.", "sports", "B1"),
("Tauchen", "das", "diving", "Tauchen im Meer.", "Diving in the sea.", "sports", "B1"),
("Yoga", "das", "yoga", "Yoga entspannt den Körper.", "Yoga relaxes the body.", "sports", "A2"),
("Fitness", "die", "fitness", "Fitness ist wichtig.", "Fitness is important.", "sports", "A2"),
("Training", "das", "training", "Das Training beginnt.", "The training begins.", "sports", "A2"),
("Wettkampf", "der", "competition / contest", "Der Wettkampf ist hart.", "The competition is tough.", "sports", "B1"),
("Turnier", "das", "tournament", "Das Turnier beginnt.", "The tournament begins.", "sports", "B1"),
("Meisterschaft", "die", "championship", "Die Meisterschaft findet statt.", "The championship takes place.", "sports", "B1"),
("Rekord", "der", "record", "Ein neuer Rekord!", "A new record!", "sports", "B1"),
("Trainer", "der", "coach / trainer", "Der Trainer ist gut.", "The coach is good.", "sports", "A2"),
("Stadion", "das", "stadium", "Das Stadion ist riesig.", "The stadium is enormous.", "sports", "A2"),
("Schwimmbad", "das", "swimming pool", "Das Schwimmbad ist kalt.", "The swimming pool is cold.", "sports", "A2"),
("Sporthalle", "die", "sports hall / gymnasium", "Wir trainieren in der Sporthalle.", "We train in the sports hall.", "sports", "A2"),

# Culture & Arts
("Gemälde", "das", "painting", "Das Gemälde ist alt.", "The painting is old.", "misc", "B1"),
("Skulptur", "die", "sculpture", "Die Skulptur ist modern.", "The sculpture is modern.", "misc", "B1"),
("Ausstellung", "die", "exhibition", "Die Ausstellung ist interessant.", "The exhibition is interesting.", "misc", "B1"),
("Museum", "das", "museum", "Das Museum ist groß.", "The museum is large.", "misc", "A2"),
("Galerie", "die", "gallery", "Die Galerie zeigt neue Kunst.", "The gallery shows new art.", "misc", "B1"),
("Oper", "die", "opera", "Die Oper ist lang.", "The opera is long.", "misc", "B1"),
("Ballett", "das", "ballet", "Das Ballett ist elegant.", "The ballet is elegant.", "misc", "B1"),
("Literatur", "die", "literature", "Literatur öffnet Horizonte.", "Literature opens horizons.", "misc", "B1"),
("Roman", "der", "novel", "Der Roman ist spannend.", "The novel is exciting.", "misc", "B1"),
("Gedicht", "das", "poem", "Das Gedicht ist schön.", "The poem is beautiful.", "misc", "B1"),
("Lied", "das", "song", "Das Lied ist traurig.", "The song is sad.", "misc", "A2"),
("Melodie", "die", "melody", "Die Melodie ist schön.", "The melody is beautiful.", "misc", "B1"),
("Rhythmus", "der", "rhythm", "Der Rhythmus ist schnell.", "The rhythm is fast.", "misc", "B1"),
("Instrument", "das", "instrument", "Ich spiele ein Instrument.", "I play an instrument.", "misc", "A2"),
("Gitarre", "die", "guitar", "Ich spiele Gitarre.", "I play guitar.", "misc", "A2"),
("Klavier", "das", "piano", "Das Klavier klingt schön.", "The piano sounds beautiful.", "misc", "A2"),
("Geige", "die", "violin", "Die Geige klingt traurig.", "The violin sounds sad.", "misc", "B1"),
("Flöte", "die", "flute", "Die Flöte ist leicht.", "The flute is light.", "misc", "B1"),
("Schlagzeug", "das", "drums", "Das Schlagzeug ist laut.", "The drums are loud.", "misc", "B1"),

# Social & Daily Life
("Nachbar", "der", "neighbour (m)", "Der Nachbar ist freundlich.", "The neighbour is friendly.", "misc", "A2"),
("Nachbarin", "die", "neighbour (f)", "Die Nachbarin hilft mir.", "The neighbour helps me.", "misc", "A2"),
("Haustier", "das", "pet", "Mein Haustier ist ein Hund.", "My pet is a dog.", "animals", "A1"),
("Geburtstag", "der", "birthday", "Heute ist mein Geburtstag.", "Today is my birthday.", "misc", "A1"),
("Geschenk", "das", "gift / present", "Das Geschenk ist schön.", "The gift is beautiful.", "misc", "A1"),
("Party", "die", "party", "Die Party ist super.", "The party is great.", "misc", "A2"),
("Einladung", "die", "invitation", "Ich habe eine Einladung.", "I have an invitation.", "misc", "A2"),
("Feier", "die", "celebration / party", "Die Feier beginnt um 7.", "The celebration begins at 7.", "misc", "A2"),
("Fest", "das", "festival / celebration", "Das Fest macht Spaß.", "The festival is fun.", "misc", "A2"),
("Weihnachten", "", "Christmas", "Frohe Weihnachten!", "Merry Christmas!", "misc", "A1"),
("Ostern", "", "Easter", "Frohe Ostern!", "Happy Easter!", "misc", "A1"),
("Silvester", "der", "New Year's Eve", "Silvester feiern wir.", "We celebrate New Year's Eve.", "misc", "A2"),
("Hochzeit", "die", "wedding", "Die Hochzeit ist schön.", "The wedding is beautiful.", "misc", "A2"),
("Ehe", "die", "marriage", "Die Ehe hält.", "The marriage lasts.", "misc", "B1"),
("Scheidung", "die", "divorce", "Die Scheidung ist traurig.", "The divorce is sad.", "misc", "B2"),
("Geburt", "die", "birth", "Die Geburt war einfach.", "The birth was easy.", "misc", "B1"),
("Tod", "der", "death", "Der Tod ist unvermeidlich.", "Death is inevitable.", "misc", "B1"),
("Beerdigung", "die", "funeral", "Die Beerdigung war ruhig.", "The funeral was quiet.", "misc", "B2"),
("Traum", "der", "dream", "Ich habe einen Traum.", "I have a dream.", "misc", "A2"),
("Albtraum", "der", "nightmare", "Das war ein Albtraum.", "That was a nightmare.", "misc", "B1"),
("Abenteuer", "das", "adventure", "Das ist ein Abenteuer.", "That is an adventure.", "misc", "A2"),
("Entdeckung", "die", "discovery", "Eine große Entdeckung!", "A great discovery!", "misc", "B1"),
("Erfindung", "die", "invention", "Eine nützliche Erfindung.", "A useful invention.", "misc", "B1"),
("Wunder", "das", "miracle / wonder", "Das ist ein Wunder!", "That is a miracle!", "misc", "B1"),
("Zufall", "der", "coincidence / chance", "Das ist Zufall.", "That is a coincidence.", "misc", "B1"),
("Absicht", "die", "intention / purpose", "Mit Absicht getan.", "Done intentionally.", "misc", "B2"),
("Gewohnheit", "die", "habit", "Das ist eine Gewohnheit.", "That is a habit.", "misc", "B2"),
("Tradition", "die", "tradition", "Die Tradition lebt.", "The tradition lives.", "misc", "B1"),
("Brauch", "der", "custom / tradition", "Das ist ein alter Brauch.", "That is an old custom.", "misc", "B2"),
("Ritual", "das", "ritual", "Das Ritual ist wichtig.", "The ritual is important.", "misc", "C1"),
("Spruch", "der", "saying / phrase", "Ein alter Spruch sagt...", "An old saying goes...", "misc", "B2"),

# More adjectives across levels
("bequem", "", "comfortable", "Der Stuhl ist bequem.", "The chair is comfortable.", "adjectives", "A2"),
("unbequem", "", "uncomfortable", "Das Bett ist unbequem.", "The bed is uncomfortable.", "adjectives", "A2"),
("freundlich", "", "friendly", "Er ist sehr freundlich.", "He is very friendly.", "adjectives", "A1"),
("unfreundlich", "", "unfriendly", "Der Chef ist unfreundlich.", "The boss is unfriendly.", "adjectives", "A2"),
("höflich", "", "polite", "Sei höflich!", "Be polite!", "adjectives", "A2"),
("unhöflich", "", "impolite / rude", "Das ist unhöflich.", "That is rude.", "adjectives", "A2"),
("fleißig", "", "hardworking / diligent", "Sie ist sehr fleißig.", "She is very hardworking.", "adjectives", "A2"),
("faul", "", "lazy", "Er ist faul.", "He is lazy.", "adjectives", "A2"),
("neugierig", "", "curious / nosy", "Das Kind ist neugierig.", "The child is curious.", "adjectives", "A2"),
("mutig", "", "brave / courageous", "Der Soldat ist mutig.", "The soldier is brave.", "adjectives", "B1"),
("ängstlich", "", "anxious / fearful", "Das Kind ist ängstlich.", "The child is anxious.", "adjectives", "B1"),
("ruhig", "", "calm / quiet", "Er ist sehr ruhig.", "He is very calm.", "adjectives", "A2"),
("nervös", "", "nervous", "Ich bin nervös.", "I am nervous.", "adjectives", "A2"),
("aufgeregt", "", "excited / agitated", "Sie ist aufgeregt.", "She is excited.", "adjectives", "A2"),
("gelangweilt", "", "bored", "Ich bin gelangweilt.", "I am bored.", "adjectives", "A2"),
("überrascht", "", "surprised", "Ich bin überrascht.", "I am surprised.", "adjectives", "A2"),
("stolz", "", "proud", "Er ist stolz auf dich.", "He is proud of you.", "adjectives", "B1"),
("beschämt", "", "ashamed", "Ich bin beschämt.", "I am ashamed.", "adjectives", "B1"),
("dankbar", "", "grateful", "Ich bin dankbar.", "I am grateful.", "adjectives", "B1"),
("zufrieden", "", "satisfied / content", "Ich bin zufrieden.", "I am satisfied.", "adjectives", "B1"),
("unzufrieden", "", "dissatisfied", "Er ist unzufrieden.", "He is dissatisfied.", "adjectives", "B1"),
("optimistisch", "", "optimistic", "Sei optimistisch!", "Be optimistic!", "adjectives", "B1"),
("pessimistisch", "", "pessimistic", "Er ist pessimistisch.", "He is pessimistic.", "adjectives", "B1"),
("realistisch", "", "realistic", "Sei realistisch!", "Be realistic!", "adjectives", "B2"),
("kreativ", "", "creative", "Sie ist sehr kreativ.", "She is very creative.", "adjectives", "B1"),
("intelligent", "", "intelligent", "Er ist intelligent.", "He is intelligent.", "adjectives", "A2"),
("klug", "", "clever / wise", "Sie ist klug.", "She is clever.", "adjectives", "A2"),
("dumm", "", "stupid / silly", "Das ist dumm.", "That is stupid.", "adjectives", "A2"),
("stark", "", "strong", "Er ist stark.", "He is strong.", "adjectives", "A2"),
("schwach", "", "weak", "Das Argument ist schwach.", "The argument is weak.", "adjectives", "A2"),
("dick", "", "thick / fat", "Das Buch ist dick.", "The book is thick.", "adjectives", "A1"),
("dünn", "", "thin / slim", "Die Wand ist dünn.", "The wall is thin.", "adjectives", "A1"),
("kurz", "", "short", "Das Kleid ist kurz.", "The dress is short.", "adjectives", "A1"),
("lang", "", "long", "Der Fluss ist lang.", "The river is long.", "adjectives", "A1"),
("hoch", "", "high / tall", "Der Berg ist hoch.", "The mountain is high.", "adjectives", "A1"),
("niedrig", "", "low", "Die Temperatur ist niedrig.", "The temperature is low.", "adjectives", "A2"),
("tief", "", "deep / low", "Der See ist tief.", "The lake is deep.", "adjectives", "A2"),
("flach", "", "flat / shallow", "Das Land ist flach.", "The land is flat.", "adjectives", "B1"),
("breit", "", "wide / broad", "Die Straße ist breit.", "The road is wide.", "adjectives", "A2"),
("eng", "", "narrow / tight", "Die Gasse ist eng.", "The alley is narrow.", "adjectives", "A2"),
("voll", "", "full", "Das Glas ist voll.", "The glass is full.", "adjectives", "A1"),
("leer", "", "empty", "Das Glas ist leer.", "The glass is empty.", "adjectives", "A1"),
("schwierig", "", "difficult", "Das ist schwierig.", "That is difficult.", "adjectives", "A2"),
("leicht", "", "easy / light", "Das ist leicht.", "That is easy.", "adjectives", "A1"),
("bekannt", "", "well-known / familiar", "Er ist bekannt.", "He is well-known.", "adjectives", "B1"),
("unbekannt", "", "unknown", "Die Ursache ist unbekannt.", "The cause is unknown.", "adjectives", "B1"),
("berühmt", "", "famous", "Sie ist berühmt.", "She is famous.", "adjectives", "B1"),
("selten", "", "rare / seldom", "Das ist sehr selten.", "That is very rare.", "adjectives", "B1"),
("häufig", "", "frequent / common", "Das ist häufig.", "That is frequent.", "adjectives", "B1"),
("regelmäßig", "", "regular", "Ich trainiere regelmäßig.", "I train regularly.", "adjectives", "B1"),
("gelegentlich", "", "occasional / occasional", "Gelegentlich mache ich Fehler.", "Occasionally I make mistakes.", "adjectives", "B2"),
("modern", "", "modern", "Das Design ist modern.", "The design is modern.", "adjectives", "A2"),
("traditionell", "", "traditional", "Das Essen ist traditionell.", "The food is traditional.", "adjectives", "B1"),
("natürlich", "", "natural / of course", "Das ist natürlich.", "That is natural.", "adjectives", "A2"),
("künstlich", "", "artificial", "Das Licht ist künstlich.", "The light is artificial.", "adjectives", "B1"),
("organisch", "", "organic", "Ich kaufe organisches Gemüse.", "I buy organic vegetables.", "adjectives", "B2"),
("digital", "", "digital", "Die Welt ist digital.", "The world is digital.", "adjectives", "A2"),
("analog", "", "analogue", "Ein analoges Gerät.", "An analogue device.", "adjectives", "B2"),
("international", "", "international", "Das ist international.", "That is international.", "adjectives", "B1"),
("national", "", "national", "Die nationale Hymne.", "The national anthem.", "adjectives", "B1"),
("lokal", "", "local", "Das ist ein lokales Problem.", "That is a local problem.", "adjectives", "B1"),
("global", "", "global", "Ein globales Problem.", "A global problem.", "adjectives", "B2"),
("politisch", "", "political", "Das ist politisch.", "That is political.", "adjectives", "B2"),
("wirtschaftlich", "", "economic", "Die wirtschaftliche Lage.", "The economic situation.", "adjectives", "B2"),
("sozial", "", "social", "Soziale Gerechtigkeit.", "Social justice.", "adjectives", "B2"),
("kulturell", "", "cultural", "Das kulturelle Erbe.", "The cultural heritage.", "adjectives", "B2"),
("wissenschaftlich", "", "scientific", "Eine wissenschaftliche Studie.", "A scientific study.", "adjectives", "B2"),
("technisch", "", "technical", "Ein technisches Problem.", "A technical problem.", "adjectives", "B1"),
("praktisch", "", "practical", "Das ist praktisch.", "That is practical.", "adjectives", "B1"),
("theoretisch", "", "theoretical", "Theoretisch ist das möglich.", "Theoretically that is possible.", "adjectives", "B2"),
("aktuell", "", "current / up-to-date", "Die aktuelle Situation.", "The current situation.", "adjectives", "B1"),
("vergangen", "", "past", "Im vergangenen Jahr.", "In the past year.", "adjectives", "B1"),
("zukünftig", "", "future", "Zukünftige Entwicklungen.", "Future developments.", "adjectives", "B2"),
("vorherig", "", "previous", "Das vorherige Modell.", "The previous model.", "adjectives", "B2"),
("nächst", "", "next", "Das nächste Mal.", "The next time.", "adjectives", "A1"),
("letzt", "", "last", "Das letzte Mal.", "The last time.", "adjectives", "A1"),
("erst", "", "first", "Das erste Mal.", "The first time.", "adjectives", "A1"),
("genau", "", "exact / precise", "Das ist genau richtig.", "That is exactly right.", "adjectives", "A2"),
("ungefähr", "", "approximately", "Ungefähr 10 Minuten.", "Approximately 10 minutes.", "adverbs", "A2"),
("mindestens", "", "at least", "Mindestens eine Stunde.", "At least one hour.", "adverbs", "B1"),
("höchstens", "", "at most", "Höchstens zwei Stunden.", "At most two hours.", "adverbs", "B1"),
("bereits", "", "already", "Ich bin bereits fertig.", "I am already finished.", "adverbs", "B1"),
("jedoch", "", "however / yet", "Jedoch ist das schwierig.", "However that is difficult.", "adverbs", "B1"),
("allerdings", "", "however / admittedly", "Das ist allerdings schwer.", "That is admittedly difficult.", "adverbs", "B2"),
("außerdem", "", "besides / moreover", "Außerdem ist er klug.", "Besides, he is clever.", "adverbs", "B1"),
("deshalb", "", "therefore / that is why", "Deshalb bin ich hier.", "That is why I am here.", "adverbs", "A2"),
("deswegen", "", "therefore / because of this", "Deswegen gehe ich.", "That is why I am going.", "adverbs", "A2"),
("trotzdem", "", "nevertheless / still", "Trotzdem mache ich es.", "I do it nevertheless.", "adverbs", "B1"),
("dennoch", "", "nonetheless / yet", "Dennoch bleibt es wahr.", "Nonetheless it remains true.", "adverbs", "B2"),
("obwohl", "", "although / even though", "Obwohl es schwer ist.", "Although it is difficult.", "adverbs", "B1"),
("weil", "", "because", "Weil ich müde bin.", "Because I am tired.", "adverbs", "A1"),
("damit", "", "so that / with it", "Damit du es weißt.", "So that you know.", "adverbs", "A2"),
("falls", "", "in case / if", "Falls es regnet.", "In case it rains.", "adverbs", "B1"),
("sobald", "", "as soon as", "Sobald du kommst.", "As soon as you come.", "adverbs", "B1"),
("solange", "", "as long as", "Solange du hier bist.", "As long as you are here.", "adverbs", "B1"),
("seitdem", "", "since (then)", "Seitdem ist alles anders.", "Since then everything is different.", "adverbs", "B2"),
("inzwischen", "", "meanwhile / by now", "Inzwischen bin ich fertig.", "By now I am finished.", "adverbs", "B2"),
("gleichzeitig", "", "simultaneously / at the same time", "Das geht gleichzeitig.", "That happens simultaneously.", "adverbs", "B2"),
("dadurch", "", "thereby / through this", "Dadurch wird es besser.", "Thereby it gets better.", "adverbs", "B2"),
("daran", "", "on it / about it", "Ich denke daran.", "I think about it.", "adverbs", "B1"),
("dafür", "", "for it / in favour", "Ich bin dafür.", "I am in favour.", "adverbs", "B1"),
("dagegen", "", "against it", "Ich bin dagegen.", "I am against it.", "adverbs", "B1"),
("davon", "", "from it / of it", "Ich weiß davon.", "I know about it.", "adverbs", "B1"),
("damit", "", "with it / therewith", "Was machst du damit?", "What do you do with it?", "adverbs", "A2"),
("woher", "", "from where", "Woher kommst du?", "Where do you come from?", "adverbs", "A1"),
("wohin", "", "to where", "Wohin gehst du?", "Where are you going?", "adverbs", "A1"),
("womit", "", "with what", "Womit schreibst du?", "What do you write with?", "adverbs", "B1"),
("worüber", "", "about what", "Worüber sprichst du?", "What are you talking about?", "adverbs", "B1"),
("woran", "", "on what / about what", "Woran arbeitest du?", "What are you working on?", "adverbs", "B1"),
("warum", "", "why", "Warum machst du das?", "Why do you do that?", "adverbs", "A1"),
("weshalb", "", "why / for what reason", "Weshalb bist du hier?", "Why are you here?", "adverbs", "B1"),
("wie", "", "how", "Wie geht es dir?", "How are you?", "adverbs", "A1"),
("wann", "", "when", "Wann kommst du?", "When are you coming?", "adverbs", "A1"),
("was", "", "what", "Was machst du?", "What are you doing?", "adverbs", "A1"),
("wer", "", "who", "Wer bist du?", "Who are you?", "adverbs", "A1"),
("welcher", "", "which", "Welcher Bus fährt?", "Which bus goes?", "adverbs", "A1"),
("wo", "", "where", "Wo bist du?", "Where are you?", "adverbs", "A1"),

# C1 / C2 — more sophisticated nouns
("Abhandlung", "die", "treatise / essay", "Eine wissenschaftliche Abhandlung.", "A scientific treatise.", "misc", "C1"),
("Betrachtung", "die", "observation / consideration", "Eine kritische Betrachtung.", "A critical observation.", "misc", "C1"),
("Diskurs", "der", "discourse", "Ein öffentlicher Diskurs.", "A public discourse.", "misc", "C1"),
("Evidenz", "die", "evidence", "Die Evidenz ist klar.", "The evidence is clear.", "misc", "C1"),
("Intention", "die", "intention", "Die Intention ist gut.", "The intention is good.", "misc", "C1"),
("Kohärenz", "die", "coherence", "Die Kohärenz fehlt.", "The coherence is missing.", "misc", "C1"),
("Legitimität", "die", "legitimacy", "Die Legitimität ist fraglich.", "The legitimacy is questionable.", "misc", "C1"),
("Narrativ", "das", "narrative", "Das Narrativ ist veraltet.", "The narrative is outdated.", "misc", "C1"),
("Plausibilität", "die", "plausibility", "Die Plausibilität ist gegeben.", "The plausibility is given.", "misc", "C1"),
("Redundanz", "die", "redundancy", "Redundanz ist zu vermeiden.", "Redundancy is to be avoided.", "misc", "C1"),
("Relativierung", "die", "relativisation", "Eine Relativierung ist nötig.", "A relativisation is needed.", "misc", "C1"),
("Repräsentation", "die", "representation", "Eine faire Repräsentation.", "A fair representation.", "misc", "C1"),
("Schlussfolgerung", "die", "conclusion", "Die Schlussfolgerung ist klar.", "The conclusion is clear.", "misc", "C1"),
("Schwerpunkt", "der", "focus / main emphasis", "Der Schwerpunkt liegt hier.", "The focus is here.", "misc", "C1"),
("Skepsis", "die", "scepticism", "Skepsis ist angebracht.", "Scepticism is appropriate.", "misc", "C1"),
("Stellungnahme", "die", "statement / position", "Eine offizielle Stellungnahme.", "An official statement.", "misc", "C1"),
("Substanz", "die", "substance", "Das hat Substanz.", "That has substance.", "misc", "C1"),
("Synthese", "die", "synthesis", "Eine Synthese entsteht.", "A synthesis is emerging.", "misc", "C1"),
("These", "die", "thesis / claim", "Die These ist belegt.", "The thesis is supported.", "misc", "C1"),
("Überarbeitung", "die", "revision", "Eine Überarbeitung ist nötig.", "A revision is needed.", "misc", "C1"),
("Verfassung", "die", "constitution / condition", "Die Verfassung gilt.", "The constitution applies.", "misc", "C1"),
("Vermittlung", "die", "mediation / conveyance", "Vermittlung ist schwierig.", "Mediation is difficult.", "misc", "C1"),
("Vorurteil", "das", "prejudice", "Vorurteile schaden.", "Prejudices cause harm.", "misc", "B2"),
("Widerstand", "der", "resistance", "Widerstand ist zwecklos.", "Resistance is futile.", "misc", "B2"),
("Zerfall", "der", "decay / disintegration", "Der Zerfall beginnt.", "The decay begins.", "misc", "C1"),
("Zeugnis", "das", "testimony / certificate", "Ein glaubwürdiges Zeugnis.", "A credible testimony.", "misc", "B2"),
("Zweck", "der", "purpose / aim", "Zu welchem Zweck?", "For what purpose?", "misc", "B2"),
("Zwischenergebnis", "das", "interim result", "Das Zwischenergebnis liegt vor.", "The interim result is available.", "misc", "C1"),

# C2 additional
("Ausgeburt", "die", "monstrous creation / spawn", "Eine Ausgeburt der Fantasie.", "A creation of fantasy.", "misc", "C2"),
("Dialektik", "die", "dialectics", "Hegels Dialektik ist komplex.", "Hegel's dialectics are complex.", "misc", "C2"),
("Entfremdung", "die", "alienation / estrangement", "Entfremdung ist ein Konzept.", "Alienation is a concept.", "misc", "C2"),
("Hybridität", "die", "hybridity", "Hybridität prägt die Kultur.", "Hybridity shapes culture.", "misc", "C2"),
("Immanenz", "die", "immanence", "Immanenz und Transzendenz.", "Immanence and transcendence.", "misc", "C2"),
("Konnotation", "die", "connotation", "Die Konnotation ist negativ.", "The connotation is negative.", "misc", "C2"),
("Metaebene", "die", "meta-level", "Auf der Metaebene.", "On the meta-level.", "misc", "C2"),
("Ontologie", "die", "ontology", "Ontologie ist eine Disziplin.", "Ontology is a discipline.", "misc", "C2"),
("Postulat", "das", "postulate", "Ein philosophisches Postulat.", "A philosophical postulate.", "misc", "C2"),
("Signifikanz", "die", "significance", "Die statistische Signifikanz.", "The statistical significance.", "misc", "C2"),
("Teleologie", "die", "teleology", "Teleologie erklärt Zwecke.", "Teleology explains purposes.", "misc", "C2"),
("Unschärfe", "die", "blur / vagueness / uncertainty", "Quantenmechanische Unschärfe.", "Quantum mechanical uncertainty.", "misc", "C2"),
("Vieldeutigkeit", "die", "multiple meanings / ambiguity", "Vieldeutigkeit kennzeichnet Lyrik.", "Ambiguity characterises poetry.", "misc", "C2"),
("Zuschreibung", "die", "attribution / ascription", "Eine falsche Zuschreibung.", "A false attribution.", "misc", "C2"),
]
