# words_data_3.py — third batch (~1200 more words, targeting letters/categories still thin)

WORDS3 = [

# ══════════════════════════════════════════════
# More A1/A2 — filling gaps in common letters
# ══════════════════════════════════════════════

# Q words (rare in German but some exist)
("Qualität", "die", "quality", "Die Qualität ist hoch.", "The quality is high.", "misc", "B1"),
("Quelle", "die", "source / spring", "Die Quelle ist zuverlässig.", "The source is reliable.", "misc", "B1"),
("Quittung", "die", "receipt", "Ich brauche eine Quittung.", "I need a receipt.", "work", "A2"),
("Quadrat", "das", "square", "Ein Quadrat hat vier Ecken.", "A square has four corners.", "school", "A2"),
("Quiz", "das", "quiz", "Das Quiz macht Spaß.", "The quiz is fun.", "misc", "A2"),

# X words
("Xylophon", "das", "xylophone", "Das Xylophon klingt schön.", "The xylophone sounds beautiful.", "misc", "A2"),

# Y words
("Yoga", "das", "yoga", "Yoga entspannt mich.", "Yoga relaxes me.", "sports", "A2"),

# More everyday A1 nouns
("Abend", "der", "evening", "Am Abend esse ich.", "In the evening I eat.", "time", "A1"),
("Antwort", "die", "answer / reply", "Ich warte auf eine Antwort.", "I wait for an answer.", "misc", "A1"),
("Arbeit", "die", "work", "Die Arbeit ist fertig.", "The work is finished.", "work", "A1"),
("Aufgabe", "die", "task / exercise", "Die Aufgabe ist einfach.", "The task is easy.", "school", "A1"),
("Ausgang", "der", "exit / outcome", "Wo ist der Ausgang?", "Where is the exit?", "travel", "A2"),
("Auskunft", "die", "information / inquiry", "Ich brauche Auskunft.", "I need information.", "misc", "A2"),
("Aussicht", "die", "view / prospect", "Die Aussicht ist wunderbar.", "The view is wonderful.", "travel", "B1"),

# B words (more)
("Baum", "der", "tree", "Der Baum ist alt.", "The tree is old.", "nature", "A1"),
("Bedeutung", "die", "meaning", "Was ist die Bedeutung?", "What is the meaning?", "misc", "B1"),
("Beginn", "der", "beginning / start", "Vom Beginn an.", "From the beginning.", "misc", "B1"),
("Bericht", "der", "report", "Der Bericht ist lang.", "The report is long.", "work", "B1"),
("Besuch", "der", "visit", "Der Besuch war schön.", "The visit was nice.", "misc", "A2"),
("Betrag", "der", "amount / sum", "Der Betrag ist hoch.", "The amount is high.", "work", "B1"),
("Bitte", "die", "request / plea", "Ich habe eine Bitte.", "I have a request.", "misc", "A2"),
("Blick", "der", "look / glance / view", "Ein kurzer Blick.", "A quick glance.", "misc", "B1"),
("Brücke", "die", "bridge", "Die Brücke ist alt.", "The bridge is old.", "travel", "A2"),
("Bürger", "der", "citizen", "Der Bürger wählt.", "The citizen votes.", "misc", "B1"),
("Bürgerin", "die", "citizen (f)", "Die Bürgerin hat Rechte.", "The citizen has rights.", "misc", "B1"),

# D words (more)
("Dauer", "die", "duration", "Die Dauer ist unbekannt.", "The duration is unknown.", "misc", "B1"),
("Denken", "das", "thinking / thought", "Kritisches Denken ist wichtig.", "Critical thinking is important.", "misc", "B2"),
("Druck", "der", "pressure / print", "Der Druck ist hoch.", "The pressure is high.", "misc", "B1"),
("Durchschnitt", "der", "average", "Der Durchschnitt liegt bei 70.", "The average is 70.", "school", "B1"),

# E words (more)
("Eindruck", "der", "impression", "Ein guter Eindruck.", "A good impression.", "misc", "B1"),
("Einheit", "die", "unit / unity", "Eine starke Einheit.", "A strong unity.", "misc", "B2"),
("Einsatz", "der", "deployment / effort / stake", "Ein großer Einsatz.", "A great effort.", "misc", "B2"),
("Entscheidung", "die", "decision", "Eine wichtige Entscheidung.", "An important decision.", "misc", "B1"),
("Ergebnis", "das", "result", "Das Ergebnis überrascht.", "The result is surprising.", "misc", "B1"),
("Erlaubnis", "die", "permission", "Ich brauche Erlaubnis.", "I need permission.", "misc", "B1"),
("Erschöpfung", "die", "exhaustion", "Totale Erschöpfung.", "Total exhaustion.", "health", "B2"),
("Erwartung", "die", "expectation", "Die Erwartungen sind hoch.", "The expectations are high.", "misc", "B2"),

# F words (more)
("Fabrik", "die", "factory", "Die Fabrik produziert Autos.", "The factory produces cars.", "work", "B1"),
("Fahrt", "die", "journey / ride / trip", "Eine lange Fahrt.", "A long journey.", "travel", "A2"),
("Familie", "die", "family", "Die Familie ist wichtig.", "The family is important.", "family", "A1"),
("Feind", "der", "enemy", "Er ist kein Feind.", "He is no enemy.", "misc", "B1"),
("Feindschaft", "die", "enmity / hostility", "Feindschaft ist schlecht.", "Enmity is bad.", "misc", "B2"),
("Fenster", "das", "window", "Das Fenster ist klein.", "The window is small.", "home", "A1"),
("Fernsehen", "das", "television", "Ich schaue Fernsehen.", "I watch television.", "misc", "A1"),
("Fläche", "die", "area / surface", "Die Fläche ist groß.", "The area is large.", "misc", "B1"),
("Fleck", "der", "spot / stain", "Ein roter Fleck.", "A red spot.", "misc", "B1"),
("Frieden", "der", "peace", "Frieden ist wertvoll.", "Peace is valuable.", "misc", "B1"),
("Frist", "die", "deadline / period", "Die Frist läuft ab.", "The deadline expires.", "work", "B2"),
("Führung", "die", "leadership / guidance", "Gute Führung ist nötig.", "Good leadership is needed.", "work", "B2"),
("Funktion", "die", "function", "Die Funktion ist klar.", "The function is clear.", "misc", "B1"),

# G words (more)
("Gang", "der", "corridor / gait / gear", "Der Gang ist lang.", "The corridor is long.", "home", "B1"),
("Gedächtnis", "das", "memory", "Ein gutes Gedächtnis hilft.", "A good memory helps.", "misc", "B2"),
("Gelände", "das", "terrain / grounds", "Das Gelände ist groß.", "The grounds are large.", "travel", "B1"),
("Gemeinschaft", "die", "community", "Die Gemeinschaft hilft.", "The community helps.", "misc", "B1"),
("Genehmigung", "die", "approval / permit", "Eine Genehmigung ist nötig.", "A permit is needed.", "misc", "B2"),
("Gespräch", "das", "conversation / talk", "Ein interessantes Gespräch.", "An interesting conversation.", "misc", "A2"),
("Gewinn", "der", "profit / gain / prize", "Der Gewinn ist hoch.", "The profit is high.", "work", "B1"),
("Grenze", "die", "border / limit", "Die Grenze ist klar.", "The limit is clear.", "misc", "A2"),
("Gruppe", "die", "group", "Die Gruppe ist groß.", "The group is large.", "misc", "A2"),
("Grundsatz", "der", "principle / basic rule", "Ein wichtiger Grundsatz.", "An important principle.", "misc", "C1"),

# H words (more)
("Handlung", "die", "action / plot", "Die Handlung ist spannend.", "The plot is exciting.", "misc", "B2"),
("Haushalt", "der", "household / budget", "Der Haushalt ist geregelt.", "The household is organised.", "home", "B1"),
("Herkunft", "die", "origin", "Meine Herkunft ist deutsch.", "My origin is German.", "misc", "B2"),
("Hilfe", "die", "help / assistance", "Danke für die Hilfe!", "Thank you for the help!", "misc", "A1"),
("Himmel", "der", "sky", "Der Himmel ist klar.", "The sky is clear.", "nature", "A1"),
("Hinweis", "der", "hint / note / reference", "Ein wichtiger Hinweis.", "An important hint.", "misc", "B1"),
("Hintergrund", "der", "background", "Der Hintergrund ist unklar.", "The background is unclear.", "misc", "B2"),

# I words (more)
("Industrie", "die", "industry", "Die Industrie wächst.", "The industry is growing.", "work", "B2"),
("Inhalt", "der", "content", "Der Inhalt ist relevant.", "The content is relevant.", "misc", "B1"),
("Interesse", "das", "interest", "Das Interesse ist groß.", "The interest is great.", "misc", "A2"),

# J words
("Jahrzehnt", "das", "decade", "Im letzten Jahrzehnt.", "In the last decade.", "time", "B1"),
("Jahrhundert", "das", "century", "Im neunzehnten Jahrhundert.", "In the nineteenth century.", "time", "B1"),
("Jahrtausend", "das", "millennium", "Ein neues Jahrtausend.", "A new millennium.", "time", "C1"),
("Jugend", "die", "youth", "In meiner Jugend.", "In my youth.", "misc", "B1"),
("Jugendliche", "der/die", "young person / teenager", "Die Jugendlichen lernen.", "The young people learn.", "misc", "B1"),

# K words (more)
("Kampf", "der", "fight / struggle", "Ein harter Kampf.", "A hard fight.", "misc", "B1"),
("Kennzeichen", "das", "characteristic / number plate", "Ein typisches Kennzeichen.", "A typical characteristic.", "misc", "B2"),
("Kern", "der", "core / nucleus / kernel", "Der Kern der Sache.", "The core of the matter.", "misc", "B2"),
("Kosten", "", "costs (plural)", "Die Kosten sind hoch.", "The costs are high.", "work", "A2"),
("Kraft", "die", "strength / force / power", "Die Kraft kommt zurück.", "The strength returns.", "misc", "B1"),
("Kreis", "der", "circle / district", "Ein Kreis ist rund.", "A circle is round.", "misc", "A2"),
("Kühl", "", "cool", "Es ist kühl draußen.", "It is cool outside.", "adjectives", "A2"),

# L words (more)
("Lage", "die", "position / situation", "Die Lage ist ernst.", "The situation is serious.", "misc", "B1"),
("Leistung", "die", "performance / output", "Gute Leistung!", "Good performance!", "work", "B1"),
("Lösung", "die", "solution", "Eine einfache Lösung.", "A simple solution.", "misc", "B1"),
("Luft", "die", "air", "Die Luft ist kalt.", "The air is cold.", "nature", "A1"),

# M words (more)
("Mangel", "der", "lack / shortage / defect", "Ein Mangel an Wasser.", "A lack of water.", "misc", "B2"),
("Maßstab", "der", "scale / standard / yardstick", "Ein hoher Maßstab.", "A high standard.", "misc", "C1"),
("Menge", "die", "quantity / crowd", "Eine große Menge.", "A large quantity.", "misc", "B1"),
("Mitte", "die", "middle / centre", "In der Mitte der Stadt.", "In the centre of the city.", "misc", "A2"),
("Mittel", "das", "means / remedy / average", "Ein Mittel zum Zweck.", "A means to an end.", "misc", "B2"),
("Mund", "der", "mouth", "Öffne deinen Mund!", "Open your mouth!", "body", "A1"),
("Mut", "der", "courage", "Er zeigt Mut.", "He shows courage.", "emotions", "B1"),

# N words (more)
("Nachricht", "die", "message / news", "Eine wichtige Nachricht.", "An important message.", "misc", "A2"),
("Natur", "die", "nature", "Die Natur ist schön.", "Nature is beautiful.", "nature", "A1"),
("Notfall", "der", "emergency", "Im Notfall anrufen!", "Call in an emergency!", "health", "B1"),
("Nutzung", "die", "use / usage", "Die Nutzung ist kostenlos.", "The use is free.", "misc", "B2"),

# O words (more)
("Oberfläche", "die", "surface", "Die Oberfläche ist glatt.", "The surface is smooth.", "misc", "B1"),
("Ordnung", "die", "order / tidiness", "Ordnung ist wichtig.", "Order is important.", "misc", "A2"),
("Ort", "der", "place / location", "An welchem Ort?", "At which place?", "travel", "A1"),

# P words (more)
("Pause", "die", "break / pause", "Ich mache eine Pause.", "I take a break.", "misc", "A1"),
("Person", "die", "person", "Eine wichtige Person.", "An important person.", "misc", "A1"),
("Pflicht", "die", "duty", "Das ist meine Pflicht.", "That is my duty.", "misc", "B1"),
("Prüfung", "die", "examination / test", "Die Prüfung ist morgen.", "The exam is tomorrow.", "school", "A2"),
("Punkt", "der", "point / dot / full stop", "Das ist ein wichtiger Punkt.", "That is an important point.", "misc", "A2"),

# R words (more)
("Rand", "der", "edge / border / margin", "Am Rand der Stadt.", "At the edge of the city.", "misc", "B1"),
("Raum", "der", "room / space", "Der Raum ist leer.", "The room is empty.", "misc", "B1"),
("Recht", "das", "right / law", "Das ist mein Recht.", "That is my right.", "misc", "B1"),
("Reihe", "die", "row / series", "Eine Reihe von Problemen.", "A series of problems.", "misc", "B1"),
("Risiko", "das", "risk", "Das Risiko ist gering.", "The risk is low.", "misc", "B1"),
("Rolle", "die", "role / reel", "Eine wichtige Rolle.", "An important role.", "misc", "B1"),

# S words (more)
("Schaden", "der", "damage / harm", "Der Schaden ist groß.", "The damage is great.", "misc", "B1"),
("Schatten", "der", "shadow / shade", "Im Schatten ist es kühl.", "In the shade it is cool.", "nature", "A2"),
("Schluss", "der", "conclusion / end", "Am Schluss...", "At the end...", "misc", "B1"),
("Schritt", "der", "step", "Ein wichtiger Schritt.", "An important step.", "misc", "A2"),
("Schuld", "die", "guilt / debt / fault", "Die Schuld liegt bei mir.", "The fault lies with me.", "misc", "B1"),
("Schwierigkeit", "die", "difficulty", "Eine große Schwierigkeit.", "A great difficulty.", "misc", "B1"),
("Sinn", "der", "sense / meaning", "Das ergibt Sinn.", "That makes sense.", "misc", "B1"),
("Sorge", "die", "worry / care", "Keine Sorge!", "No worries!", "emotions", "B1"),
("Spaß", "der", "fun / joke", "Das macht Spaß!", "That is fun!", "misc", "A1"),
("Stelle", "die", "place / position / job", "An dieser Stelle.", "At this point.", "misc", "B1"),
("Stimmung", "die", "mood / atmosphere", "Die Stimmung ist gut.", "The mood is good.", "emotions", "B1"),
("Stück", "das", "piece / play", "Ein Stück Kuchen.", "A piece of cake.", "misc", "A1"),
("Stunde", "die", "hour / class", "Eine Stunde Musik.", "One hour of music.", "time", "A1"),
("Suche", "die", "search", "Auf der Suche nach.", "In search of.", "misc", "B1"),

# T words (more)
("Tat", "die", "deed / act", "Eine mutige Tat.", "A courageous deed.", "misc", "B1"),
("Tatsache", "die", "fact", "Das ist eine Tatsache.", "That is a fact.", "misc", "B1"),
("Tätigkeit", "die", "activity / occupation", "Eine interessante Tätigkeit.", "An interesting activity.", "work", "B2"),
("Tier", "das", "animal", "Das Tier ist wild.", "The animal is wild.", "animals", "A1"),
("Ton", "der", "sound / tone / clay", "Ein schöner Ton.", "A beautiful sound.", "misc", "B1"),
("Traum", "der", "dream", "Ein schöner Traum.", "A beautiful dream.", "misc", "A2"),

# U words (more)
("Umgang", "der", "handling / dealing with", "Der Umgang ist schwierig.", "Dealing with it is difficult.", "misc", "B2"),
("Umstand", "der", "circumstance", "Unter diesen Umständen.", "Under these circumstances.", "misc", "B2"),
("Ungerechtigkeit", "die", "injustice", "Ungerechtigkeit ärgert mich.", "Injustice annoys me.", "misc", "B2"),
("Unterschied", "der", "difference", "Ein großer Unterschied.", "A big difference.", "misc", "B1"),
("Unterstützung", "die", "support", "Ich brauche Unterstützung.", "I need support.", "misc", "B1"),
("Ursprung", "der", "origin", "Der Ursprung ist unbekannt.", "The origin is unknown.", "misc", "B2"),

# V words (more)
("Verfahren", "das", "process / procedure", "Ein kompliziertes Verfahren.", "A complicated procedure.", "misc", "C1"),
("Vergangenheit", "die", "past", "Die Vergangenheit loslassen.", "Letting go of the past.", "time", "B1"),
("Vergütung", "die", "remuneration / compensation", "Die Vergütung ist fair.", "The remuneration is fair.", "work", "C1"),
("Verhalten", "das", "behaviour", "Das Verhalten ist merkwürdig.", "The behaviour is strange.", "misc", "B1"),
("Verständigung", "die", "communication / agreement", "Eine gute Verständigung.", "Good communication.", "misc", "B2"),
("Versuch", "der", "attempt / experiment", "Ein erster Versuch.", "A first attempt.", "misc", "B1"),
("Verteilung", "die", "distribution", "Eine faire Verteilung.", "A fair distribution.", "misc", "B2"),
("Verwaltung", "die", "administration", "Die Verwaltung ist kompliziert.", "The administration is complicated.", "work", "B2"),
("Verzeichnis", "das", "directory / list / index", "Das Verzeichnis ist aktuell.", "The directory is up to date.", "misc", "B2"),
("Vollständigkeit", "die", "completeness", "Vollständigkeit ist wichtig.", "Completeness is important.", "misc", "C1"),
("Vorhaben", "das", "project / plan / intention", "Ein großes Vorhaben.", "A big project.", "misc", "B2"),
("Vorschlag", "der", "suggestion / proposal", "Ein guter Vorschlag.", "A good suggestion.", "misc", "B1"),
("Vortrag", "der", "talk / lecture / presentation", "Ein spannender Vortrag.", "An exciting talk.", "school", "B1"),
("Vorwurf", "der", "accusation / reproach", "Ein ungerechtfertigter Vorwurf.", "An unjustified accusation.", "misc", "B2"),

# W words (more)
("Weg", "der", "way / path / road", "Der Weg ist lang.", "The way is long.", "travel", "A1"),
("Wesen", "das", "being / essence / nature", "Das Wesen der Sache.", "The essence of the matter.", "misc", "B2"),
("Widerspruch", "der", "contradiction", "Ein klarer Widerspruch.", "A clear contradiction.", "misc", "B2"),
("Wille", "der", "will / willpower", "Der Wille ist da.", "The will is there.", "misc", "B1"),
("Wirksamkeit", "die", "effectiveness", "Die Wirksamkeit ist belegt.", "The effectiveness is proven.", "misc", "C1"),
("Wohlbefinden", "das", "wellbeing", "Das Wohlbefinden ist wichtig.", "Wellbeing is important.", "health", "B2"),
("Wohlstand", "der", "prosperity / wealth", "Wohlstand bringt Glück.", "Prosperity brings happiness.", "misc", "B2"),

# Z words (more)
("Zeile", "die", "line (text)", "Die erste Zeile.", "The first line.", "school", "B1"),
("Zeit", "die", "time", "Die Zeit vergeht.", "Time passes.", "time", "A1"),
("Zeitraum", "der", "period of time", "In diesem Zeitraum.", "During this period.", "time", "B2"),
("Zeitung", "die", "newspaper", "Ich lese die Zeitung.", "I read the newspaper.", "misc", "A1"),
("Ziel", "das", "goal / destination", "Ich erreiche mein Ziel.", "I reach my goal.", "misc", "A2"),
("Zug", "der", "train / move / draft", "Der Zug fährt ab.", "The train departs.", "travel", "A1"),
("Zukunft", "die", "future", "Die Zukunft ist offen.", "The future is open.", "time", "B1"),
("Zustand", "der", "state / condition", "Ein guter Zustand.", "A good condition.", "misc", "B1"),

# ══════════════════════════════════════════════
# More verbs — all levels
# ══════════════════════════════════════════════

("abbrechen", "", "to break off / cancel / abort", "Ich breche das Gespräch ab.", "I break off the conversation.", "verbs", "B1"),
("abgeben", "", "to hand in / submit / give", "Ich gebe die Hausarbeit ab.", "I hand in the essay.", "verbs", "B1"),
("abhängen", "", "to depend on", "Das hängt davon ab.", "That depends on it.", "verbs", "B1"),
("abnehmen", "", "to lose weight / take off / decrease", "Er nimmt ab.", "He is losing weight.", "verbs", "B1"),
("abschalten", "", "to switch off / unwind", "Ich schalte ab.", "I switch off.", "verbs", "B1"),
("abschließen", "", "to complete / lock / conclude", "Ich schließe ab.", "I conclude.", "verbs", "B2"),
("abstimmen", "", "to vote / coordinate", "Wir stimmen ab.", "We vote.", "verbs", "B2"),
("abtrennen", "", "to separate / detach", "Trenne die Seiten ab!", "Separate the pages!", "verbs", "B2"),
("abwehren", "", "to fend off / ward off", "Er wehrt den Angriff ab.", "He fends off the attack.", "verbs", "C1"),
("achten", "", "to pay attention / respect", "Achte auf dich!", "Take care of yourself!", "verbs", "B1"),
("ähneln", "", "to resemble", "Er ähnelt seinem Vater.", "He resembles his father.", "verbs", "B2"),
("ankommen", "", "to arrive / depend", "Wann kommst du an?", "When are you arriving?", "verbs", "A2"),
("anmelden", "", "to register / sign up", "Ich melde mich an.", "I register.", "verbs", "B1"),
("annehmen", "", "to accept / assume", "Ich nehme das Angebot an.", "I accept the offer.", "verbs", "B1"),
("anpassen", "", "to adapt / adjust", "Ich passe mich an.", "I adapt.", "verbs", "B2"),
("anschauen", "", "to look at / watch", "Ich schaue den Film an.", "I watch the film.", "verbs", "A2"),
("anschließen", "", "to connect / follow", "Ich schließe das Gerät an.", "I connect the device.", "verbs", "B1"),
("ansehen", "", "to look at / regard", "Sieh dir das an!", "Look at that!", "verbs", "A2"),
("anwenden", "", "to apply / use", "Ich wende die Regel an.", "I apply the rule.", "verbs", "B2"),
("anzeigen", "", "to display / report", "Die App zeigt es an.", "The app displays it.", "verbs", "B1"),
("aufbauen", "", "to build up / construct", "Wir bauen etwas auf.", "We build something up.", "verbs", "B1"),
("auffordern", "", "to request / demand", "Ich fordere dich auf.", "I request you.", "verbs", "B2"),
("aufnehmen", "", "to record / absorb / accept", "Ich nehme das auf.", "I record that.", "verbs", "B1"),
("auflösen", "", "to dissolve / resolve", "Ich löse das Problem auf.", "I resolve the problem.", "verbs", "B2"),
("ausarbeiten", "", "to work out / develop", "Ich arbeite das aus.", "I work that out.", "verbs", "B2"),
("ausdrücken", "", "to express", "Ich drücke es aus.", "I express it.", "verbs", "B1"),
("ausfüllen", "", "to fill in / complete", "Füll das Formular aus!", "Fill in the form!", "verbs", "A2"),
("ausgehen", "", "to go out / run out", "Ich gehe aus.", "I go out.", "verbs", "A2"),
("aushalten", "", "to endure / bear", "Das kann ich nicht aushalten.", "I cannot bear that.", "verbs", "B2"),
("ausleihen", "", "to borrow / lend", "Ich leihe ein Buch aus.", "I borrow a book.", "verbs", "A2"),
("ausmachen", "", "to turn off / arrange", "Mach das Licht aus!", "Turn off the light!", "verbs", "A2"),
("ausnutzen", "", "to exploit / take advantage of", "Er nutzt sie aus.", "He exploits them.", "verbs", "B2"),
("ausrichten", "", "to align / deliver a message", "Richte es ihr aus!", "Pass it on to her!", "verbs", "B2"),
("ausschalten", "", "to switch off", "Schalte den Computer aus!", "Switch off the computer!", "verbs", "A2"),
("ausschneiden", "", "to cut out", "Schneid das Bild aus!", "Cut out the picture!", "verbs", "B1"),
("aussprechen", "", "to pronounce / express", "Wie sprichst du das aus?", "How do you pronounce that?", "verbs", "B1"),
("austauschen", "", "to exchange", "Wir tauschen Ideen aus.", "We exchange ideas.", "verbs", "B1"),
("auswandern", "", "to emigrate", "Er wandert aus.", "He emigrates.", "verbs", "B2"),
("bewegen", "", "to move", "Bewege dich mehr!", "Move more!", "verbs", "B1"),
("beachten", "", "to observe / pay attention to", "Beachte die Regel!", "Observe the rule!", "verbs", "B1"),
("begegnen", "", "to meet / encounter", "Ich begegne ihm.", "I encounter him.", "verbs", "B1"),
("behandeln", "", "to treat / deal with", "Der Arzt behandelt ihn.", "The doctor treats him.", "verbs", "B1"),
("behaupten", "", "to claim / assert", "Ich behaupte das.", "I claim that.", "verbs", "B2"),
("belegen", "", "to prove / occupy / enrol in", "Ich belege einen Kurs.", "I enrol in a course.", "verbs", "B2"),
("beobachten", "", "to observe / watch", "Ich beobachte die Vögel.", "I watch the birds.", "verbs", "B1"),
("berechnen", "", "to calculate", "Berechne die Summe!", "Calculate the sum!", "verbs", "B1"),
("beruhigen", "", "to calm down", "Beruhige dich!", "Calm down!", "verbs", "B1"),
("bestehen", "", "to exist / pass (exam) / insist", "Er besteht die Prüfung.", "He passes the exam.", "verbs", "B1"),
("betonen", "", "to stress / emphasise", "Ich betone das.", "I emphasise that.", "verbs", "B2"),
("betreffen", "", "to concern / affect", "Das betrifft uns alle.", "That concerns us all.", "verbs", "B2"),
("betreiben", "", "to operate / run", "Er betreibt ein Café.", "He runs a café.", "verbs", "B2"),
("beweisen", "", "to prove", "Ich beweise es.", "I prove it.", "verbs", "B2"),
("beziehen", "", "to relate to / obtain / move into", "Ich beziehe mich darauf.", "I refer to that.", "verbs", "B2"),
("darstellen", "", "to represent / portray", "Das stellt ein Problem dar.", "That represents a problem.", "verbs", "B2"),
("durchführen", "", "to carry out / implement", "Wir führen es durch.", "We carry it out.", "verbs", "B2"),
("eingreifen", "", "to intervene", "Ich greife ein.", "I intervene.", "verbs", "C1"),
("einhalten", "", "to keep / observe (a rule)", "Halte die Regeln ein!", "Keep the rules!", "verbs", "B2"),
("einsetzen", "", "to deploy / use", "Ich setze das ein.", "I deploy that.", "verbs", "B2"),
("einstellen", "", "to hire / adjust / stop", "Wir stellen ihn ein.", "We hire him.", "verbs", "B2"),
("entsprechen", "", "to correspond to / meet", "Das entspricht meinen Erwartungen.", "That meets my expectations.", "verbs", "B2"),
("ergänzen", "", "to add / supplement", "Ich ergänze die Liste.", "I supplement the list.", "verbs", "B2"),
("ergreifen", "", "to seize / take (measures)", "Ich ergreife Maßnahmen.", "I take measures.", "verbs", "C1"),
("erhalten", "", "to receive / maintain", "Ich erhalte eine Nachricht.", "I receive a message.", "verbs", "B1"),
("erhöhen", "", "to increase / raise", "Wir erhöhen den Preis.", "We raise the price.", "verbs", "B2"),
("erleben", "", "to experience", "Ich erlebe viel.", "I experience a lot.", "verbs", "B1"),
("erscheinen", "", "to appear / seem", "Er erscheint pünktlich.", "He appears punctually.", "verbs", "B1"),
("erzeugen", "", "to generate / produce", "Das erzeugt Stress.", "That generates stress.", "verbs", "B2"),
("fortsetzen", "", "to continue", "Ich setze fort.", "I continue.", "verbs", "B2"),
("gründen", "", "to found / establish", "Wir gründen ein Unternehmen.", "We found a company.", "verbs", "B2"),
("herausfordern", "", "to challenge", "Das fordert mich heraus.", "That challenges me.", "verbs", "B2"),
("hinweisen", "", "to point out / refer to", "Ich weise darauf hin.", "I point that out.", "verbs", "B2"),
("interessieren", "", "to interest", "Das interessiert mich.", "That interests me.", "verbs", "A2"),
("klären", "", "to clarify", "Wir klären das.", "We clarify that.", "verbs", "B1"),
("leisten", "", "to achieve / afford", "Ich leiste gute Arbeit.", "I do good work.", "verbs", "B2"),
("nachdenken", "", "to think / reflect", "Ich denke nach.", "I am thinking.", "verbs", "B1"),
("profitieren", "", "to profit / benefit", "Ich profitiere davon.", "I benefit from it.", "verbs", "B2"),
("schlussfolgern", "", "to conclude / infer", "Ich schlussfolgere.", "I conclude.", "verbs", "C1"),
("streiken", "", "to go on strike", "Die Arbeiter streiken.", "The workers are on strike.", "verbs", "B2"),
("überprüfen", "", "to check / verify", "Ich überprüfe das.", "I check that.", "verbs", "B2"),
("übertragen", "", "to transfer / transmit / translate", "Ich übertrage die Datei.", "I transfer the file.", "verbs", "B2"),
("verarbeiten", "", "to process", "Ich verarbeite die Daten.", "I process the data.", "verbs", "B2"),
("verdienen", "", "to earn / deserve", "Er verdient gut.", "He earns well.", "verbs", "B1"),
("vereinen", "", "to unite / combine", "Wir vereinen uns.", "We unite.", "verbs", "B2"),
("verfügen", "", "to have at one's disposal", "Ich verfüge über Erfahrung.", "I have experience at my disposal.", "verbs", "C1"),
("vernachlässigen", "", "to neglect", "Ich vernachlässige nichts.", "I neglect nothing.", "verbs", "C1"),
("vernetzen", "", "to network / connect", "Wir vernetzen uns.", "We network.", "verbs", "B2"),
("veröffentlichen", "", "to publish", "Ich veröffentliche den Artikel.", "I publish the article.", "verbs", "B2"),
("verpassen", "", "to miss", "Ich verpasse den Zug.", "I miss the train.", "verbs", "B1"),
("verschlechtern", "", "to worsen", "Die Lage verschlechtert sich.", "The situation worsens.", "verbs", "B2"),
("verschieben", "", "to postpone / shift", "Ich verschiebe den Termin.", "I postpone the appointment.", "verbs", "B2"),
("verschwinden", "", "to disappear", "Er verschwindet.", "He disappears.", "verbs", "B1"),
("vertrauen", "", "to trust", "Ich vertraue dir.", "I trust you.", "verbs", "B1"),
("verzichten", "", "to do without / forgo", "Ich verzichte darauf.", "I forgo that.", "verbs", "B2"),
("vorstellen", "", "to introduce / imagine", "Stell dir vor!", "Imagine!", "verbs", "A2"),
("wachsen", "", "to grow", "Der Baum wächst.", "The tree grows.", "verbs", "A2"),
("widmen", "", "to dedicate", "Ich widme mich der Arbeit.", "I dedicate myself to the work.", "verbs", "C1"),
("zugreifen", "", "to access / grab", "Greif zu!", "Help yourself!", "verbs", "B2"),
("zunehmen", "", "to increase / gain weight", "Die Zahl nimmt zu.", "The number is increasing.", "verbs", "B1"),
("zusammenfassen", "", "to summarise", "Fasse es zusammen!", "Summarise it!", "verbs", "B1"),
("zusammenstellen", "", "to compile / put together", "Ich stelle das zusammen.", "I compile that.", "verbs", "B2"),

# ══════════════════════════════════════════════
# More adjectives — all levels
# ══════════════════════════════════════════════

("aktiv", "", "active", "Er ist sehr aktiv.", "He is very active.", "adjectives", "A2"),
("passiv", "", "passive", "Sie ist passiv.", "She is passive.", "adjectives", "B1"),
("aggressiv", "", "aggressive", "Er ist aggressiv.", "He is aggressive.", "adjectives", "B1"),
("tolerant", "", "tolerant", "Sei tolerant!", "Be tolerant!", "adjectives", "B1"),
("flexibel", "", "flexible", "Ich bin flexibel.", "I am flexible.", "adjectives", "B1"),
("stabil", "", "stable", "Die Lage ist stabil.", "The situation is stable.", "adjectives", "B1"),
("instabil", "", "unstable", "Die Lage ist instabil.", "The situation is unstable.", "adjectives", "B2"),
("effizient", "", "efficient", "Ein effizientes System.", "An efficient system.", "adjectives", "B2"),
("effektiv", "", "effective", "Eine effektive Methode.", "An effective method.", "adjectives", "B2"),
("produktiv", "", "productive", "Ein produktiver Tag.", "A productive day.", "adjectives", "B1"),
("destruktiv", "", "destructive", "Destruktives Verhalten.", "Destructive behaviour.", "adjectives", "B2"),
("konstruktiv", "", "constructive", "Konstruktive Kritik.", "Constructive criticism.", "adjectives", "B2"),
("innovativ", "", "innovative", "Eine innovative Lösung.", "An innovative solution.", "adjectives", "C1"),
("konservativ", "", "conservative", "Eine konservative Einstellung.", "A conservative attitude.", "adjectives", "B2"),
("progressiv", "", "progressive", "Ein progressiver Ansatz.", "A progressive approach.", "adjectives", "C1"),
("radikal", "", "radical", "Eine radikale Änderung.", "A radical change.", "adjectives", "B2"),
("extrem", "", "extreme", "Das ist extrem.", "That is extreme.", "adjectives", "B1"),
("moderat", "", "moderate", "Eine moderate Meinung.", "A moderate opinion.", "adjectives", "B2"),
("neutral", "", "neutral", "Eine neutrale Position.", "A neutral position.", "adjectives", "B2"),
("objektiv", "", "objective", "Ein objektiver Bericht.", "An objective report.", "adjectives", "B2"),
("subjektiv", "", "subjective", "Das ist subjektiv.", "That is subjective.", "adjectives", "B2"),
("logisch", "", "logical", "Das ist logisch.", "That is logical.", "adjectives", "B1"),
("rational", "", "rational", "Eine rationale Entscheidung.", "A rational decision.", "adjectives", "B2"),
("irrational", "", "irrational", "Irrationales Verhalten.", "Irrational behaviour.", "adjectives", "C1"),
("emotional", "", "emotional", "Eine emotionale Reaktion.", "An emotional reaction.", "adjectives", "B1"),
("empfindlich", "", "sensitive / delicate", "Er ist empfindlich.", "He is sensitive.", "adjectives", "B1"),
("robust", "", "robust", "Ein robustes Material.", "A robust material.", "adjectives", "B2"),
("fragil", "", "fragile", "Das Glas ist fragil.", "The glass is fragile.", "adjectives", "B2"),
("dauerhaft", "", "permanent / durable", "Eine dauerhafte Lösung.", "A permanent solution.", "adjectives", "B2"),
("temporär", "", "temporary", "Eine temporäre Maßnahme.", "A temporary measure.", "adjectives", "B2"),
("vorläufig", "", "provisional / preliminary", "Ein vorläufiges Ergebnis.", "A preliminary result.", "adjectives", "C1"),
("endgültig", "", "final / definitive", "Eine endgültige Entscheidung.", "A final decision.", "adjectives", "C1"),
("unvermeidlich", "", "inevitable", "Das ist unvermeidlich.", "That is inevitable.", "adjectives", "C1"),
("erforderlich", "", "required / necessary", "Das ist erforderlich.", "That is required.", "adjectives", "B2"),
("verbindlich", "", "binding / obligatory", "Das ist verbindlich.", "That is binding.", "adjectives", "C1"),
("unverbindlich", "", "non-binding", "Das ist unverbindlich.", "That is non-binding.", "adjectives", "C1"),
("angemessen", "", "appropriate / adequate", "Das ist angemessen.", "That is appropriate.", "adjectives", "B2"),
("unangemessen", "", "inappropriate", "Das ist unangemessen.", "That is inappropriate.", "adjectives", "B2"),
("überzeugend", "", "convincing", "Ein überzeugendes Argument.", "A convincing argument.", "adjectives", "B2"),
("fraglich", "", "questionable / doubtful", "Das ist fraglich.", "That is questionable.", "adjectives", "B2"),
("zweifelhaft", "", "doubtful", "Das ist zweifelhaft.", "That is doubtful.", "adjectives", "B2"),
("eindeutig", "", "clear / unambiguous", "Eine eindeutige Antwort.", "A clear answer.", "adjectives", "B2"),
("mehrdeutig", "", "ambiguous", "Eine mehrdeutige Aussage.", "An ambiguous statement.", "adjectives", "C1"),
("bemerkenswert", "", "remarkable", "Ein bemerkenswerter Erfolg.", "A remarkable success.", "adjectives", "C1"),
("außergewöhnlich", "", "exceptional / extraordinary", "Eine außergewöhnliche Leistung.", "An exceptional performance.", "adjectives", "B2"),
("gewöhnlich", "", "ordinary / usual", "Ein gewöhnlicher Tag.", "An ordinary day.", "adjectives", "B1"),
("ungewöhnlich", "", "unusual", "Das ist ungewöhnlich.", "That is unusual.", "adjectives", "B1"),
("auffällig", "", "conspicuous / striking", "Ein auffälliges Muster.", "A striking pattern.", "adjectives", "B2"),
("unauffällig", "", "inconspicuous", "Er ist unauffällig.", "He is inconspicuous.", "adjectives", "B2"),
("sichtbar", "", "visible", "Das ist sichtbar.", "That is visible.", "adjectives", "B1"),
("unsichtbar", "", "invisible", "Das ist unsichtbar.", "That is invisible.", "adjectives", "B1"),
("spürbar", "", "noticeable / perceptible", "Das ist spürbar.", "That is noticeable.", "adjectives", "B2"),
("greifbar", "", "tangible / within reach", "Das ist greifbar.", "That is tangible.", "adjectives", "C1"),
("verständlich", "", "understandable / clear", "Das ist verständlich.", "That is understandable.", "adjectives", "B1"),
("unverständlich", "", "incomprehensible", "Das ist unverständlich.", "That is incomprehensible.", "adjectives", "B2"),
("unverzichtbar", "", "indispensable", "Das ist unverzichtbar.", "That is indispensable.", "adjectives", "C1"),
("entscheidend", "", "decisive / crucial", "Ein entscheidender Moment.", "A decisive moment.", "adjectives", "B2"),
("entsprechend", "", "corresponding / appropriate", "Entsprechende Maßnahmen.", "Corresponding measures.", "adjectives", "B2"),
("vorhanden", "", "available / present / existing", "Das ist vorhanden.", "That is available.", "adjectives", "B2"),
("eigenartig", "", "peculiar / strange", "Das ist eigenartig.", "That is peculiar.", "adjectives", "B2"),
("seltsam", "", "strange / odd", "Das ist seltsam.", "That is strange.", "adjectives", "B1"),
("merkwürdig", "", "strange / peculiar", "Das ist merkwürdig.", "That is peculiar.", "adjectives", "B2"),
("absurd", "", "absurd", "Das ist absurd.", "That is absurd.", "adjectives", "B2"),
("plausibel", "", "plausible", "Das ist plausibel.", "That is plausible.", "adjectives", "C1"),
("systematisch", "", "systematic", "Ein systematischer Ansatz.", "A systematic approach.", "adjectives", "B2"),
("strukturiert", "", "structured", "Eine strukturierte Arbeit.", "A structured piece of work.", "adjectives", "B2"),
("gründlich", "", "thorough", "Eine gründliche Analyse.", "A thorough analysis.", "adjectives", "B2"),
("oberflächlich", "", "superficial", "Eine oberflächliche Betrachtung.", "A superficial consideration.", "adjectives", "B2"),
("tiefgründig", "", "profound / deep", "Eine tiefgründige Frage.", "A profound question.", "adjectives", "C1"),
("erfahren", "", "experienced", "Ein erfahrener Lehrer.", "An experienced teacher.", "adjectives", "B1"),
("unerfahren", "", "inexperienced", "Ein unerfahrener Mitarbeiter.", "An inexperienced employee.", "adjectives", "B2"),
("qualifiziert", "", "qualified", "Ein qualifizierter Bewerber.", "A qualified applicant.", "adjectives", "B2"),
("kompetent", "", "competent", "Ein kompetenter Arzt.", "A competent doctor.", "adjectives", "B2"),
("inkompetent", "", "incompetent", "Das ist inkompetent.", "That is incompetent.", "adjectives", "B2"),
("professionell", "", "professional", "Ein professioneller Auftritt.", "A professional appearance.", "adjectives", "B2"),
("unprofessionell", "", "unprofessional", "Das ist unprofessionell.", "That is unprofessional.", "adjectives", "B2"),
("ehrenamtlich", "", "voluntary / honorary", "Ehrenamtliche Arbeit.", "Voluntary work.", "adjectives", "B2"),
("freiwillig", "", "voluntary / of one's own free will", "Das ist freiwillig.", "That is voluntary.", "adjectives", "B1"),
("pflichtbewusst", "", "conscientious / dutiful", "Er ist pflichtbewusst.", "He is conscientious.", "adjectives", "C1"),

# ══════════════════════════════════════════════
# More family / relationships
# ══════════════════════════════════════════════

("Onkel", "der", "uncle", "Mein Onkel ist lustig.", "My uncle is funny.", "family", "A1"),
("Tante", "die", "aunt", "Die Tante bringt Geschenke.", "The aunt brings gifts.", "family", "A1"),
("Cousin", "der", "cousin (m)", "Mein Cousin wohnt in Berlin.", "My cousin lives in Berlin.", "family", "A1"),
("Cousine", "die", "cousin (f)", "Meine Cousine ist älter.", "My cousin is older.", "family", "A1"),
("Nichte", "die", "niece", "Die Nichte ist süß.", "The niece is cute.", "family", "A2"),
("Neffe", "der", "nephew", "Der Neffe wächst schnell.", "The nephew grows fast.", "family", "A2"),
("Schwiegermutter", "die", "mother-in-law", "Die Schwiegermutter ist nett.", "The mother-in-law is nice.", "family", "B1"),
("Schwiegervater", "der", "father-in-law", "Der Schwiegervater kocht gut.", "The father-in-law cooks well.", "family", "B1"),
("Schwager", "der", "brother-in-law", "Mein Schwager ist Arzt.", "My brother-in-law is a doctor.", "family", "B1"),
("Schwägerin", "die", "sister-in-law", "Die Schwägerin kommt heute.", "The sister-in-law is coming today.", "family", "B1"),
("Verlobte", "der/die", "fiancé / fiancée", "Mein Verlobter ist toll.", "My fiancé is great.", "family", "B1"),
("Witwe", "die", "widow", "Die Witwe lebt allein.", "The widow lives alone.", "family", "B2"),
("Witwer", "der", "widower", "Der Witwer ist traurig.", "The widower is sad.", "family", "B2"),
("Einzelkind", "das", "only child", "Ich bin Einzelkind.", "I am an only child.", "family", "B1"),
("Zwilling", "der", "twin", "Sie sind Zwillinge.", "They are twins.", "family", "B1"),
("Geschwister", "", "siblings (plural)", "Ich habe drei Geschwister.", "I have three siblings.", "family", "A1"),
("Verwandte", "der/die", "relative", "Ein entfernter Verwandter.", "A distant relative.", "family", "B1"),

# ══════════════════════════════════════════════
# Professions — A2 / B1
# ══════════════════════════════════════════════

("Ingenieur", "der", "engineer (m)", "Der Ingenieur baut Brücken.", "The engineer builds bridges.", "work", "A2"),
("Ingenieurin", "die", "engineer (f)", "Die Ingenieurin plant das Projekt.", "The engineer plans the project.", "work", "A2"),
("Anwalt", "der", "lawyer (m)", "Der Anwalt verteidigt ihn.", "The lawyer defends him.", "work", "B1"),
("Anwältin", "die", "lawyer (f)", "Die Anwältin berät mich.", "The lawyer advises me.", "work", "B1"),
("Richter", "der", "judge (m)", "Der Richter spricht das Urteil.", "The judge pronounces the verdict.", "work", "B1"),
("Polizist", "der", "police officer (m)", "Der Polizist hilft.", "The police officer helps.", "work", "A2"),
("Polizistin", "die", "police officer (f)", "Die Polizistin regelt den Verkehr.", "The policewoman directs traffic.", "work", "A2"),
("Feuerwehrmann", "der", "firefighter (m)", "Der Feuerwehrmann löscht das Feuer.", "The firefighter extinguishes the fire.", "work", "A2"),
("Soldat", "der", "soldier (m)", "Der Soldat ist tapfer.", "The soldier is brave.", "work", "B1"),
("Kellner", "der", "waiter (m)", "Der Kellner bringt das Essen.", "The waiter brings the food.", "work", "A2"),
("Kellnerin", "die", "waitress", "Die Kellnerin ist freundlich.", "The waitress is friendly.", "work", "A2"),
("Koch", "der", "cook / chef (m)", "Der Koch kocht ausgezeichnet.", "The chef cooks excellently.", "work", "A2"),
("Köchin", "die", "cook / chef (f)", "Die Köchin ist kreativ.", "The chef is creative.", "work", "A2"),
("Bäcker", "der", "baker (m)", "Der Bäcker backt früh.", "The baker bakes early.", "work", "A2"),
("Bäckerin", "die", "baker (f)", "Die Bäckerin macht Brot.", "The baker makes bread.", "work", "A2"),
("Maler", "der", "painter (m)", "Der Maler streicht die Wand.", "The painter paints the wall.", "work", "A2"),
("Musiker", "der", "musician (m)", "Der Musiker spielt Gitarre.", "The musician plays guitar.", "work", "A2"),
("Sänger", "der", "singer (m)", "Der Sänger hat eine gute Stimme.", "The singer has a good voice.", "work", "A2"),
("Sängerin", "die", "singer (f)", "Die Sängerin singt wunderschön.", "The singer sings beautifully.", "work", "A2"),
("Schauspieler", "der", "actor (m)", "Der Schauspieler spielt gut.", "The actor acts well.", "work", "A2"),
("Schauspielerin", "die", "actress", "Die Schauspielerin ist berühmt.", "The actress is famous.", "work", "A2"),
("Journalist", "der", "journalist (m)", "Der Journalist schreibt Artikel.", "The journalist writes articles.", "work", "B1"),
("Wissenschaftler", "der", "scientist (m)", "Der Wissenschaftler forscht.", "The scientist researches.", "work", "B1"),
("Forscher", "der", "researcher (m)", "Der Forscher analysiert.", "The researcher analyses.", "work", "B1"),
("Politiker", "der", "politician (m)", "Der Politiker redet viel.", "The politician talks a lot.", "work", "B1"),
("Unternehmer", "der", "entrepreneur (m)", "Der Unternehmer gründet Firmen.", "The entrepreneur founds companies.", "work", "B1"),
("Handwerker", "der", "craftsman / tradesman", "Der Handwerker repariert.", "The craftsman repairs.", "work", "A2"),
("Mechaniker", "der", "mechanic (m)", "Der Mechaniker repariert Autos.", "The mechanic repairs cars.", "work", "A2"),
("Elektriker", "der", "electrician (m)", "Der Elektriker legt Kabel.", "The electrician lays cables.", "work", "A2"),
("Klempner", "der", "plumber (m)", "Der Klempner repariert Rohre.", "The plumber repairs pipes.", "work", "A2"),
("Tierarzt", "der", "vet (m)", "Der Tierarzt heilt Tiere.", "The vet heals animals.", "work", "A2"),
("Apotheker", "der", "pharmacist (m)", "Der Apotheker gibt Rat.", "The pharmacist gives advice.", "work", "A2"),
("Taxifahrer", "der", "taxi driver (m)", "Der Taxifahrer kennt die Stadt.", "The taxi driver knows the city.", "work", "A2"),
("Busfahrer", "der", "bus driver (m)", "Der Busfahrer fährt sicher.", "The bus driver drives safely.", "work", "A2"),
("Pilot", "der", "pilot (m)", "Der Pilot landet das Flugzeug.", "The pilot lands the plane.", "work", "A2"),

# ══════════════════════════════════════════════
# More nature / geography
# ══════════════════════════════════════════════

("Kontinent", "der", "continent", "Europa ist ein Kontinent.", "Europe is a continent.", "travel", "B1"),
("Insel", "die", "island", "Die Insel ist klein.", "The island is small.", "travel", "A2"),
("Halbinsel", "die", "peninsula", "Eine Halbinsel hat Küste.", "A peninsula has a coastline.", "travel", "B1"),
("Gebirge", "das", "mountain range", "Das Gebirge ist schneebedeckt.", "The mountain range is snow-covered.", "nature", "B1"),
("Gipfel", "der", "summit / peak", "Der Gipfel ist hoch.", "The summit is high.", "nature", "B1"),
("Höhle", "die", "cave", "Die Höhle ist dunkel.", "The cave is dark.", "nature", "B1"),
("Vulkan", "der", "volcano", "Der Vulkan ist aktiv.", "The volcano is active.", "nature", "B1"),
("Erdbeben", "das", "earthquake", "Ein Erdbeben erschüttert.", "An earthquake shakes.", "nature", "B1"),
("Überschwemmung", "die", "flood", "Die Überschwemmung ist schlimm.", "The flood is bad.", "nature", "B1"),
("Dürre", "die", "drought", "Die Dürre dauert an.", "The drought continues.", "nature", "B2"),
("Lawine", "die", "avalanche", "Eine Lawine geht ab.", "An avalanche comes down.", "nature", "B2"),
("Orkan", "der", "hurricane / storm", "Der Orkan ist stark.", "The hurricane is strong.", "nature", "B1"),
("Sturm", "der", "storm", "Der Sturm kommt.", "The storm is coming.", "nature", "A2"),
("Sonnenstich", "der", "sunstroke", "Ich habe einen Sonnenstich.", "I have sunstroke.", "health", "B1"),
("Jahreszeit", "die", "season", "Meine Lieblingsjahreszeit ist Sommer.", "My favourite season is summer.", "time", "A1"),
("Klima", "das", "climate", "Das Klima ist mild.", "The climate is mild.", "nature", "B1"),
("Treibhausgas", "das", "greenhouse gas", "Treibhausgase schaden.", "Greenhouse gases cause harm.", "nature", "C1"),
("Artenschutz", "der", "species protection", "Artenschutz ist wichtig.", "Species protection is important.", "nature", "C1"),
("Ozonschicht", "die", "ozone layer", "Die Ozonschicht ist dünn.", "The ozone layer is thin.", "nature", "B2"),
("Naturkatastrophe", "die", "natural disaster", "Eine Naturkatastrophe trifft ein.", "A natural disaster strikes.", "nature", "B2"),

# ══════════════════════════════════════════════
# Abstract / academic nouns — B2 / C1 / C2
# ══════════════════════════════════════════════

("Abstraktion", "die", "abstraction", "Abstraktion ist nötig.", "Abstraction is necessary.", "misc", "C1"),
("Affirmation", "die", "affirmation", "Eine positive Affirmation.", "A positive affirmation.", "misc", "C1"),
("Analogie", "die", "analogy", "Eine treffende Analogie.", "An apt analogy.", "misc", "C1"),
("Annahme", "die", "assumption", "Eine falsche Annahme.", "A false assumption.", "misc", "B2"),
("Antithese", "die", "antithesis", "Die Antithese stärkt.", "The antithesis strengthens.", "misc", "C1"),
("Axiom", "das", "axiom", "Ein grundlegendes Axiom.", "A fundamental axiom.", "misc", "C2"),
("Begründung", "die", "justification / reasoning", "Eine klare Begründung.", "A clear justification.", "misc", "B2"),
("Darstellung", "die", "presentation / depiction", "Eine klare Darstellung.", "A clear depiction.", "misc", "B2"),
("Deduktion", "die", "deduction", "Deduktion ist logisch.", "Deduction is logical.", "misc", "C1"),
("Denotation", "die", "denotation", "Denotation und Konnotation.", "Denotation and connotation.", "misc", "C2"),
("Determination", "die", "determination / determination", "Determination führt zum Ziel.", "Determination leads to the goal.", "misc", "C1"),
("Divergenz", "die", "divergence", "Die Divergenz wächst.", "The divergence is growing.", "misc", "C1"),
("Dualismus", "der", "dualism", "Körper-Geist-Dualismus.", "Body-mind dualism.", "misc", "C2"),
("Empirie", "die", "empiricism", "Empirie basiert auf Erfahrung.", "Empiricism is based on experience.", "misc", "C2"),
("Erkenntnistheorie", "die", "epistemology", "Erkenntnistheorie fragt: Was ist Wissen?", "Epistemology asks: What is knowledge?", "misc", "C2"),
("Falsifikation", "die", "falsification", "Falsifikation ist wissenschaftlich.", "Falsification is scientific.", "misc", "C2"),
("Finalität", "die", "finality", "Finalität bestimmt Handeln.", "Finality determines action.", "misc", "C2"),
("Gegenstand", "der", "object / subject matter", "Der Gegenstand der Forschung.", "The subject of research.", "misc", "B2"),
("Grundbegriff", "der", "basic concept", "Ein wichtiger Grundbegriff.", "An important basic concept.", "misc", "B2"),
("Hierarchie", "die", "hierarchy", "Eine klare Hierarchie.", "A clear hierarchy.", "misc", "B2"),
("Implikation", "die", "implication", "Die Implikationen sind klar.", "The implications are clear.", "misc", "C1"),
("Induktion", "die", "induction", "Induktion generalisiert.", "Induction generalises.", "misc", "C1"),
("Inferenz", "die", "inference", "Eine logische Inferenz.", "A logical inference.", "misc", "C2"),
("Interdependenz", "die", "interdependence", "Interdependenz ist überall.", "Interdependence is everywhere.", "misc", "C1"),
("Iteration", "die", "iteration", "Eine weitere Iteration.", "Another iteration.", "misc", "C1"),
("Kategorie", "die", "category", "In welche Kategorie?", "In which category?", "misc", "B2"),
("Konvergenz", "die", "convergence", "Konvergenz ist erkennbar.", "Convergence is recognisable.", "misc", "C1"),
("Korrelation", "die", "correlation", "Eine starke Korrelation.", "A strong correlation.", "misc", "B2"),
("Maxime", "die", "maxim", "Nach einer Maxime handeln.", "To act according to a maxim.", "misc", "C1"),
("Modalität", "die", "modality", "Verschiedene Modalitäten.", "Different modalities.", "misc", "C2"),
("Negation", "die", "negation", "Negation verneint.", "Negation negates.", "misc", "C1"),
("Objektivität", "die", "objectivity", "Objektivität ist schwer.", "Objectivity is difficult.", "misc", "C1"),
("Prämisse", "die", "premise", "Eine falsche Prämisse.", "A false premise.", "misc", "C1"),
("Proportion", "die", "proportion", "In der richtigen Proportion.", "In the right proportion.", "misc", "B2"),
("Prototyp", "der", "prototype", "Ein erster Prototyp.", "A first prototype.", "misc", "B2"),
("Rationalismus", "der", "rationalism", "Rationalismus betont Vernunft.", "Rationalism emphasises reason.", "misc", "C2"),
("Reduktion", "die", "reduction", "Eine Reduktion ist nötig.", "A reduction is necessary.", "misc", "B2"),
("Replikation", "die", "replication", "Replikation bestätigt.", "Replication confirms.", "misc", "C1"),
("Skala", "die", "scale", "Auf einer Skala von 1-10.", "On a scale of 1-10.", "misc", "B2"),
("Symmetrie", "die", "symmetry", "Symmetrie ist schön.", "Symmetry is beautiful.", "misc", "B2"),
("Taxonomie", "die", "taxonomy", "Eine Taxonomie ordnet.", "A taxonomy orders.", "misc", "C2"),
("Transformation", "die", "transformation", "Eine tiefe Transformation.", "A deep transformation.", "misc", "C1"),
("Typisierung", "die", "typification / typing", "Typisierung vereinfacht.", "Typification simplifies.", "misc", "C1"),
("Übereinstimmung", "die", "agreement / correspondence", "Eine hohe Übereinstimmung.", "A high degree of agreement.", "misc", "B2"),
("Untersuchung", "die", "investigation / examination", "Eine gründliche Untersuchung.", "A thorough investigation.", "misc", "B1"),
("Validität", "die", "validity", "Die Validität ist gegeben.", "The validity is given.", "misc", "C1"),
("Varianz", "die", "variance", "Eine hohe Varianz.", "A high variance.", "misc", "C1"),
("Verifikation", "die", "verification", "Die Verifikation ist nötig.", "Verification is necessary.", "misc", "C1"),
("Voraussage", "die", "prediction / forecast", "Eine Voraussage treffen.", "To make a prediction.", "misc", "B2"),
("Wahrscheinlichkeit", "die", "probability", "Die Wahrscheinlichkeit ist hoch.", "The probability is high.", "misc", "B2"),
("Wechselwirkung", "die", "interaction / interdependence", "Eine starke Wechselwirkung.", "A strong interaction.", "misc", "C1"),
("Zusammenfassung", "die", "summary", "Eine kurze Zusammenfassung.", "A brief summary.", "misc", "B1"),

# ══════════════════════════════════════════════
# Common phrases / compound words (A1-B1)
# ══════════════════════════════════════════════

("Ausnahme", "die", "exception", "Eine Ausnahme bestätigt die Regel.", "An exception proves the rule.", "misc", "B1"),
("Auswahl", "die", "selection / choice", "Eine große Auswahl.", "A large selection.", "misc", "B1"),
("Bedingung", "die", "condition / requirement", "Eine wichtige Bedingung.", "An important condition.", "misc", "B2"),
("Beschreibung", "die", "description", "Eine genaue Beschreibung.", "An exact description.", "misc", "B1"),
("Einleitung", "die", "introduction", "Die Einleitung ist kurz.", "The introduction is brief.", "school", "B1"),
("Empfehlung", "die", "recommendation", "Eine gute Empfehlung.", "A good recommendation.", "misc", "B1"),
("Entschuldigung", "die", "excuse / apology", "Das ist keine Entschuldigung.", "That is no excuse.", "misc", "A1"),
("Erklärung", "die", "explanation", "Eine einfache Erklärung.", "A simple explanation.", "misc", "A2"),
("Erledigung", "die", "completion / errand", "Die Erledigung dauert.", "Completing it takes time.", "misc", "B2"),
("Erleuchtung", "die", "enlightenment / illumination", "Eine plötzliche Erleuchtung.", "A sudden enlightenment.", "misc", "C1"),
("Feststellung", "die", "finding / statement", "Eine wichtige Feststellung.", "An important finding.", "misc", "B2"),
("Formular", "das", "form (to fill in)", "Füll das Formular aus!", "Fill in the form!", "work", "A2"),
("Garantie", "die", "guarantee / warranty", "Eine Garantie gibt Sicherheit.", "A guarantee gives security.", "work", "B1"),
("Genehmigung", "die", "approval / authorisation", "Die Genehmigung liegt vor.", "The approval is in place.", "misc", "B2"),
("Gründung", "die", "foundation / establishment", "Die Gründung der Firma.", "The founding of the company.", "work", "B2"),
("Handlungsempfehlung", "die", "recommendation for action", "Eine klare Handlungsempfehlung.", "A clear recommendation for action.", "misc", "C1"),
("Überblick", "der", "overview", "Ein guter Überblick.", "A good overview.", "misc", "B1"),
("Umfrage", "die", "survey / poll", "Eine Umfrage zeigt.", "A survey shows.", "misc", "B1"),
("Verbesserung", "die", "improvement", "Eine deutliche Verbesserung.", "A clear improvement.", "misc", "B1"),
("Verstärkung", "die", "reinforcement", "Eine Verstärkung ist nötig.", "Reinforcement is needed.", "misc", "B2"),
("Verwirklichung", "die", "realisation / implementation", "Die Verwirklichung des Plans.", "The realisation of the plan.", "misc", "C1"),
("Vorbereitung", "die", "preparation", "Die Vorbereitung dauert.", "The preparation takes time.", "misc", "B1"),
("Zusammenbruch", "der", "collapse / breakdown", "Ein totaler Zusammenbruch.", "A total collapse.", "misc", "B2"),
("Zuwendung", "die", "attention / allowance", "Zuwendung tut gut.", "Attention does good.", "emotions", "C1"),
]
