# German Dictionary Word Data
# Format: (german_word, article, english_def, example_de, example_en, category, cefr_level)
# article: 'der'/'die'/'das' for nouns, '' for verbs/adjectives/other
# category: food, animals, family, body, home, school, work, travel, nature, 
#            time, numbers, colors, clothes, health, emotions, sports, tech, 
#            adjectives, verbs, adverbs, prepositions, pronouns, misc

WORDS = [

# ===================== A1 =====================

# --- Family & People ---
("Mutter", "die", "mother", "Meine Mutter kocht gut.", "My mother cooks well.", "family", "A1"),
("Vater", "der", "father", "Mein Vater arbeitet viel.", "My father works a lot.", "family", "A1"),
("Kind", "das", "child", "Das Kind spielt im Garten.", "The child plays in the garden.", "family", "A1"),
("Bruder", "der", "brother", "Mein Bruder ist zehn Jahre alt.", "My brother is ten years old.", "family", "A1"),
("Schwester", "die", "sister", "Meine Schwester heißt Anna.", "My sister is called Anna.", "family", "A1"),
("Oma", "die", "grandmother", "Oma macht leckeren Kuchen.", "Grandma makes delicious cake.", "family", "A1"),
("Opa", "der", "grandfather", "Opa liest die Zeitung.", "Grandpa reads the newspaper.", "family", "A1"),
("Mann", "der", "man / husband", "Der Mann ist freundlich.", "The man is friendly.", "family", "A1"),
("Frau", "die", "woman / wife", "Die Frau arbeitet als Ärztin.", "The woman works as a doctor.", "family", "A1"),
("Baby", "das", "baby", "Das Baby schläft.", "The baby is sleeping.", "family", "A1"),
("Freund", "der", "friend / boyfriend", "Mein Freund heißt Max.", "My friend is called Max.", "family", "A1"),
("Freundin", "die", "friend / girlfriend", "Meine Freundin kommt heute.", "My friend is coming today.", "family", "A1"),
("Eltern", "", "parents (plural)", "Meine Eltern sind nett.", "My parents are nice.", "family", "A1"),

# --- Food & Drink ---
("Wasser", "das", "water", "Ich trinke Wasser.", "I drink water.", "food", "A1"),
("Brot", "das", "bread", "Das Brot ist frisch.", "The bread is fresh.", "food", "A1"),
("Milch", "die", "milk", "Ich trinke gern Milch.", "I like to drink milk.", "food", "A1"),
("Apfel", "der", "apple", "Der Apfel ist rot.", "The apple is red.", "food", "A1"),
("Ei", "das", "egg", "Ich esse ein Ei zum Frühstück.", "I eat an egg for breakfast.", "food", "A1"),
("Fleisch", "das", "meat", "Er isst kein Fleisch.", "He doesn't eat meat.", "food", "A1"),
("Fisch", "der", "fish", "Der Fisch schmeckt gut.", "The fish tastes good.", "food", "A1"),
("Käse", "der", "cheese", "Käse ist lecker.", "Cheese is delicious.", "food", "A1"),
("Butter", "die", "butter", "Ich nehme Butter aufs Brot.", "I put butter on the bread.", "food", "A1"),
("Zucker", "der", "sugar", "Der Kaffee hat zu viel Zucker.", "The coffee has too much sugar.", "food", "A1"),
("Salz", "das", "salt", "Das Essen braucht mehr Salz.", "The food needs more salt.", "food", "A1"),
("Kuchen", "der", "cake", "Der Kuchen ist süß.", "The cake is sweet.", "food", "A1"),
("Suppe", "die", "soup", "Die Suppe ist heiß.", "The soup is hot.", "food", "A1"),
("Reis", "der", "rice", "Ich esse Reis mit Gemüse.", "I eat rice with vegetables.", "food", "A1"),
("Nudeln", "", "pasta / noodles", "Wir essen heute Nudeln.", "We're eating pasta today.", "food", "A1"),
("Kartoffel", "die", "potato", "Die Kartoffel ist gekocht.", "The potato is cooked.", "food", "A1"),
("Tomate", "die", "tomato", "Die Tomate ist rot und saftig.", "The tomato is red and juicy.", "food", "A1"),
("Banane", "die", "banana", "Ich esse eine Banane.", "I eat a banana.", "food", "A1"),
("Orange", "die", "orange", "Die Orange ist süß.", "The orange is sweet.", "food", "A1"),
("Tee", "der", "tea", "Ich trinke Tee am Morgen.", "I drink tea in the morning.", "food", "A1"),
("Kaffee", "der", "coffee", "Kaffee gibt mir Energie.", "Coffee gives me energy.", "food", "A1"),
("Saft", "der", "juice", "Ich trinke Orangensaft.", "I drink orange juice.", "food", "A1"),
("Bier", "das", "beer", "Ein Bier, bitte!", "One beer, please!", "food", "A1"),
("Wein", "der", "wine", "Der Wein ist rot.", "The wine is red.", "food", "A1"),
("Gemüse", "das", "vegetables", "Gemüse ist gesund.", "Vegetables are healthy.", "food", "A1"),
("Obst", "das", "fruit", "Ich esse täglich Obst.", "I eat fruit every day.", "food", "A1"),
("Frühstück", "das", "breakfast", "Das Frühstück ist fertig.", "Breakfast is ready.", "food", "A1"),
("Mittagessen", "das", "lunch", "Das Mittagessen ist um 12 Uhr.", "Lunch is at 12 o'clock.", "food", "A1"),
("Abendessen", "das", "dinner", "Wir essen Abendessen zusammen.", "We eat dinner together.", "food", "A1"),

# --- Animals ---
("Hund", "der", "dog", "Der Hund bellt laut.", "The dog barks loudly.", "animals", "A1"),
("Katze", "die", "cat", "Die Katze schläft auf dem Sofa.", "The cat sleeps on the sofa.", "animals", "A1"),
("Vogel", "der", "bird", "Der Vogel singt schön.", "The bird sings beautifully.", "animals", "A1"),
("Pferd", "das", "horse", "Das Pferd läuft schnell.", "The horse runs fast.", "animals", "A1"),
("Kuh", "die", "cow", "Die Kuh gibt Milch.", "The cow gives milk.", "animals", "A1"),
("Schwein", "das", "pig", "Das Schwein ist rosa.", "The pig is pink.", "animals", "A1"),
("Maus", "die", "mouse", "Die Maus ist klein.", "The mouse is small.", "animals", "A1"),
("Fisch", "der", "fish (animal)", "Der Fisch schwimmt im Wasser.", "The fish swims in the water.", "animals", "A1"),
("Elefant", "der", "elephant", "Der Elefant ist sehr groß.", "The elephant is very big.", "animals", "A1"),
("Löwe", "der", "lion", "Der Löwe ist der König.", "The lion is the king.", "animals", "A1"),
("Tiger", "der", "tiger", "Der Tiger ist gefährlich.", "The tiger is dangerous.", "animals", "A1"),
("Bär", "der", "bear", "Der Bär schläft im Winter.", "The bear sleeps in winter.", "animals", "A1"),
("Affe", "der", "monkey / ape", "Der Affe klettert auf den Baum.", "The monkey climbs the tree.", "animals", "A1"),

# --- Colors ---
("rot", "", "red", "Die Rose ist rot.", "The rose is red.", "colors", "A1"),
("blau", "", "blue", "Der Himmel ist blau.", "The sky is blue.", "colors", "A1"),
("grün", "", "green", "Das Gras ist grün.", "The grass is green.", "colors", "A1"),
("gelb", "", "yellow", "Die Sonne ist gelb.", "The sun is yellow.", "colors", "A1"),
("schwarz", "", "black", "Die Nacht ist schwarz.", "The night is black.", "colors", "A1"),
("weiß", "", "white", "Der Schnee ist weiß.", "The snow is white.", "colors", "A1"),
("grau", "", "gray", "Der Himmel ist grau.", "The sky is gray.", "colors", "A1"),
("braun", "", "brown", "Der Bär ist braun.", "The bear is brown.", "colors", "A1"),
("orange", "", "orange", "Die Orange ist orange.", "The orange is orange.", "colors", "A1"),
("rosa", "", "pink", "Das Schwein ist rosa.", "The pig is pink.", "colors", "A1"),
("lila", "", "purple", "Die Blume ist lila.", "The flower is purple.", "colors", "A1"),

# --- Numbers / Time ---
("Zahl", "die", "number", "Welche Zahl ist das?", "What number is that?", "numbers", "A1"),
("Jahr", "das", "year", "Das Jahr hat 12 Monate.", "The year has 12 months.", "time", "A1"),
("Monat", "der", "month", "Der Monat hat 30 Tage.", "The month has 30 days.", "time", "A1"),
("Woche", "die", "week", "Die Woche hat sieben Tage.", "The week has seven days.", "time", "A1"),
("Tag", "der", "day", "Der Tag beginnt früh.", "The day starts early.", "time", "A1"),
("Stunde", "die", "hour", "Eine Stunde hat 60 Minuten.", "One hour has 60 minutes.", "time", "A1"),
("Minute", "die", "minute", "Warte eine Minute!", "Wait one minute!", "time", "A1"),
("Uhr", "die", "clock / watch / o'clock", "Es ist drei Uhr.", "It is three o'clock.", "time", "A1"),
("heute", "", "today", "Heute ist Montag.", "Today is Monday.", "time", "A1"),
("morgen", "", "tomorrow", "Morgen gehe ich einkaufen.", "Tomorrow I'm going shopping.", "time", "A1"),
("gestern", "", "yesterday", "Gestern war ich krank.", "Yesterday I was sick.", "time", "A1"),
("jetzt", "", "now", "Ich bin jetzt müde.", "I am tired now.", "time", "A1"),
("Montag", "der", "Monday", "Montag ist der erste Wochentag.", "Monday is the first weekday.", "time", "A1"),
("Dienstag", "der", "Tuesday", "Am Dienstag habe ich Schule.", "On Tuesday I have school.", "time", "A1"),
("Mittwoch", "der", "Wednesday", "Mittwoch ist die Wochenmitte.", "Wednesday is midweek.", "time", "A1"),
("Donnerstag", "der", "Thursday", "Donnerstag kommt nach Mittwoch.", "Thursday comes after Wednesday.", "time", "A1"),
("Freitag", "der", "Friday", "Freitag ist mein Lieblingstag.", "Friday is my favourite day.", "time", "A1"),
("Samstag", "der", "Saturday", "Am Samstag schlafe ich aus.", "On Saturday I sleep in.", "time", "A1"),
("Sonntag", "der", "Sunday", "Sonntag ist ein Ruhetag.", "Sunday is a day of rest.", "time", "A1"),

# --- Home ---
("Haus", "das", "house", "Das Haus ist groß.", "The house is big.", "home", "A1"),
("Zimmer", "das", "room", "Mein Zimmer ist sauber.", "My room is clean.", "home", "A1"),
("Küche", "die", "kitchen", "In der Küche koche ich.", "I cook in the kitchen.", "home", "A1"),
("Bad", "das", "bathroom", "Das Bad ist klein.", "The bathroom is small.", "home", "A1"),
("Bett", "das", "bed", "Das Bett ist weich.", "The bed is soft.", "home", "A1"),
("Tisch", "der", "table", "Der Tisch ist aus Holz.", "The table is made of wood.", "home", "A1"),
("Stuhl", "der", "chair", "Der Stuhl ist bequem.", "The chair is comfortable.", "home", "A1"),
("Fenster", "das", "window", "Das Fenster ist offen.", "The window is open.", "home", "A1"),
("Tür", "die", "door", "Die Tür ist geschlossen.", "The door is closed.", "home", "A1"),
("Lampe", "die", "lamp", "Die Lampe leuchtet hell.", "The lamp shines brightly.", "home", "A1"),
("Sofa", "das", "sofa", "Ich sitze auf dem Sofa.", "I sit on the sofa.", "home", "A1"),
("Schlüssel", "der", "key", "Wo ist mein Schlüssel?", "Where is my key?", "home", "A1"),

# --- School ---
("Schule", "die", "school", "Ich gehe zur Schule.", "I go to school.", "school", "A1"),
("Lehrer", "der", "teacher (m)", "Der Lehrer erklärt die Aufgabe.", "The teacher explains the task.", "school", "A1"),
("Lehrerin", "die", "teacher (f)", "Die Lehrerin ist nett.", "The teacher is nice.", "school", "A1"),
("Schüler", "der", "pupil (m)", "Der Schüler lernt fleißig.", "The pupil studies hard.", "school", "A1"),
("Buch", "das", "book", "Das Buch ist interessant.", "The book is interesting.", "school", "A1"),
("Stift", "der", "pen / pencil", "Ich brauche einen Stift.", "I need a pen.", "school", "A1"),
("Heft", "das", "notebook / exercise book", "Schreib es ins Heft!", "Write it in the notebook!", "school", "A1"),
("Tafel", "die", "blackboard", "Die Lehrerin schreibt an die Tafel.", "The teacher writes on the board.", "school", "A1"),
("Klasse", "die", "class / classroom", "Meine Klasse hat 25 Schüler.", "My class has 25 pupils.", "school", "A1"),

# --- Body ---
("Kopf", "der", "head", "Mein Kopf tut weh.", "My head hurts.", "body", "A1"),
("Hand", "die", "hand", "Gib mir deine Hand!", "Give me your hand!", "body", "A1"),
("Auge", "das", "eye", "Sie hat blaue Augen.", "She has blue eyes.", "body", "A1"),
("Nase", "die", "nose", "Meine Nase ist kalt.", "My nose is cold.", "body", "A1"),
("Mund", "der", "mouth", "Öffne deinen Mund!", "Open your mouth!", "body", "A1"),
("Ohr", "das", "ear", "Ich höre mit dem Ohr.", "I hear with my ear.", "body", "A1"),
("Arm", "der", "arm", "Mein Arm ist müde.", "My arm is tired.", "body", "A1"),
("Bein", "das", "leg", "Das Bein ist gebrochen.", "The leg is broken.", "body", "A1"),
("Bauch", "der", "stomach / belly", "Mein Bauch ist voll.", "My stomach is full.", "body", "A1"),
("Rücken", "der", "back", "Mein Rücken schmerzt.", "My back hurts.", "body", "A1"),
("Fuß", "der", "foot", "Mein Fuß ist nass.", "My foot is wet.", "body", "A1"),
("Finger", "der", "finger", "Ich habe zehn Finger.", "I have ten fingers.", "body", "A1"),

# --- A1 Verbs ---
("sein", "", "to be", "Ich bin müde.", "I am tired.", "verbs", "A1"),
("haben", "", "to have", "Ich habe einen Hund.", "I have a dog.", "verbs", "A1"),
("machen", "", "to make / to do", "Was machst du?", "What are you doing?", "verbs", "A1"),
("gehen", "", "to go / to walk", "Ich gehe nach Hause.", "I go home.", "verbs", "A1"),
("kommen", "", "to come", "Er kommt morgen.", "He is coming tomorrow.", "verbs", "A1"),
("sehen", "", "to see", "Ich sehe einen Vogel.", "I see a bird.", "verbs", "A1"),
("hören", "", "to hear / to listen", "Ich höre Musik.", "I listen to music.", "verbs", "A1"),
("sprechen", "", "to speak / to talk", "Ich spreche Deutsch.", "I speak German.", "verbs", "A1"),
("essen", "", "to eat", "Wir essen Abendessen.", "We eat dinner.", "verbs", "A1"),
("trinken", "", "to drink", "Sie trinkt Wasser.", "She drinks water.", "verbs", "A1"),
("schlafen", "", "to sleep", "Das Baby schläft.", "The baby is sleeping.", "verbs", "A1"),
("spielen", "", "to play", "Die Kinder spielen.", "The children play.", "verbs", "A1"),
("lernen", "", "to learn / to study", "Ich lerne Deutsch.", "I am learning German.", "verbs", "A1"),
("heißen", "", "to be called / named", "Ich heiße Maria.", "My name is Maria.", "verbs", "A1"),
("wohnen", "", "to live / to reside", "Ich wohne in Berlin.", "I live in Berlin.", "verbs", "A1"),
("kaufen", "", "to buy", "Ich kaufe Brot.", "I buy bread.", "verbs", "A1"),
("lesen", "", "to read", "Er liest ein Buch.", "He reads a book.", "verbs", "A1"),
("schreiben", "", "to write", "Sie schreibt einen Brief.", "She writes a letter.", "verbs", "A1"),
("fragen", "", "to ask", "Darf ich fragen?", "May I ask?", "verbs", "A1"),
("sagen", "", "to say / tell", "Was sagst du?", "What are you saying?", "verbs", "A1"),
("wissen", "", "to know (a fact)", "Ich weiß es nicht.", "I don't know.", "verbs", "A1"),
("mögen", "", "to like", "Ich mag Schokolade.", "I like chocolate.", "verbs", "A1"),
("wollen", "", "to want", "Ich will Wasser.", "I want water.", "verbs", "A1"),
("können", "", "to be able to / can", "Ich kann schwimmen.", "I can swim.", "verbs", "A1"),
("müssen", "", "to have to / must", "Ich muss lernen.", "I have to study.", "verbs", "A1"),

# --- A1 Adjectives ---
("groß", "", "big / tall", "Das Haus ist groß.", "The house is big.", "adjectives", "A1"),
("klein", "", "small / little", "Die Maus ist klein.", "The mouse is small.", "adjectives", "A1"),
("gut", "", "good", "Das Essen ist gut.", "The food is good.", "adjectives", "A1"),
("schlecht", "", "bad", "Das Wetter ist schlecht.", "The weather is bad.", "adjectives", "A1"),
("neu", "", "new", "Das Auto ist neu.", "The car is new.", "adjectives", "A1"),
("alt", "", "old", "Das Buch ist alt.", "The book is old.", "adjectives", "A1"),
("jung", "", "young", "Die Frau ist jung.", "The woman is young.", "adjectives", "A1"),
("schön", "", "beautiful / nice", "Das Bild ist schön.", "The picture is beautiful.", "adjectives", "A1"),
("kalt", "", "cold", "Das Wasser ist kalt.", "The water is cold.", "adjectives", "A1"),
("warm", "", "warm", "Die Suppe ist warm.", "The soup is warm.", "adjectives", "A1"),
("heiß", "", "hot", "Der Kaffee ist heiß.", "The coffee is hot.", "adjectives", "A1"),
("schnell", "", "fast / quick", "Das Auto ist schnell.", "The car is fast.", "adjectives", "A1"),
("langsam", "", "slow", "Die Schildkröte ist langsam.", "The turtle is slow.", "adjectives", "A1"),
("müde", "", "tired", "Ich bin sehr müde.", "I am very tired.", "adjectives", "A1"),
("hungrig", "", "hungry", "Ich bin hungrig.", "I am hungry.", "adjectives", "A1"),
("glücklich", "", "happy", "Das Kind ist glücklich.", "The child is happy.", "adjectives", "A1"),

# ===================== A2 =====================

# --- Travel / Places ---
("Bahnhof", "der", "train station", "Ich warte am Bahnhof.", "I am waiting at the train station.", "travel", "A2"),
("Flughafen", "der", "airport", "Das Flugzeug landet am Flughafen.", "The plane lands at the airport.", "travel", "A2"),
("Hotel", "das", "hotel", "Das Hotel ist komfortabel.", "The hotel is comfortable.", "travel", "A2"),
("Stadt", "die", "city / town", "Berlin ist eine große Stadt.", "Berlin is a big city.", "travel", "A2"),
("Straße", "die", "street / road", "Die Straße ist lang.", "The street is long.", "travel", "A2"),
("Platz", "der", "square / place / seat", "Der Platz ist schön.", "The square is beautiful.", "travel", "A2"),
("Zug", "der", "train", "Der Zug kommt um 8 Uhr.", "The train comes at 8 o'clock.", "travel", "A2"),
("Bus", "der", "bus", "Der Bus fährt pünktlich.", "The bus runs on time.", "travel", "A2"),
("Auto", "das", "car", "Das Auto ist rot.", "The car is red.", "travel", "A2"),
("Fahrrad", "das", "bicycle", "Ich fahre Fahrrad.", "I ride a bicycle.", "travel", "A2"),
("Ticket", "das", "ticket", "Wo ist mein Ticket?", "Where is my ticket?", "travel", "A2"),
("Reise", "die", "trip / journey", "Die Reise war schön.", "The trip was nice.", "travel", "A2"),
("Karte", "die", "map / card / ticket", "Ich brauche eine Karte.", "I need a map.", "travel", "A2"),
("Ausland", "das", "abroad / foreign country", "Ich reise ins Ausland.", "I travel abroad.", "travel", "A2"),
("Urlaub", "der", "holiday / vacation", "Ich mache Urlaub.", "I am on holiday.", "travel", "A2"),
("Koffer", "der", "suitcase", "Mein Koffer ist schwer.", "My suitcase is heavy.", "travel", "A2"),
("Pass", "der", "passport", "Ich brauche meinen Pass.", "I need my passport.", "travel", "A2"),
("Grenze", "die", "border", "Wir überqueren die Grenze.", "We cross the border.", "travel", "A2"),

# --- Clothes ---
("Hemd", "das", "shirt", "Das Hemd ist weiß.", "The shirt is white.", "clothes", "A2"),
("Hose", "die", "trousers / pants", "Die Hose ist blau.", "The trousers are blue.", "clothes", "A2"),
("Kleid", "das", "dress", "Das Kleid ist schön.", "The dress is beautiful.", "clothes", "A2"),
("Jacke", "die", "jacket", "Ich trage eine Jacke.", "I wear a jacket.", "clothes", "A2"),
("Schuhe", "", "shoes (plural)", "Meine Schuhe sind neu.", "My shoes are new.", "clothes", "A2"),
("Mantel", "der", "coat", "Der Mantel ist warm.", "The coat is warm.", "clothes", "A2"),
("Mütze", "die", "hat / cap / beanie", "Die Mütze ist rot.", "The hat is red.", "clothes", "A2"),
("Socken", "", "socks (plural)", "Meine Socken sind schwarz.", "My socks are black.", "clothes", "A2"),
("Rock", "der", "skirt", "Der Rock ist kurz.", "The skirt is short.", "clothes", "A2"),
("Pullover", "der", "sweater / pullover", "Der Pullover ist warm.", "The sweater is warm.", "clothes", "A2"),
("Tasche", "die", "bag / pocket", "Meine Tasche ist voll.", "My bag is full.", "clothes", "A2"),

# --- Weather & Nature ---
("Wetter", "das", "weather", "Das Wetter ist schön heute.", "The weather is nice today.", "nature", "A2"),
("Sonne", "die", "sun", "Die Sonne scheint.", "The sun is shining.", "nature", "A2"),
("Regen", "der", "rain", "Der Regen ist kalt.", "The rain is cold.", "nature", "A2"),
("Schnee", "der", "snow", "Der Schnee ist weiß.", "The snow is white.", "nature", "A2"),
("Wind", "der", "wind", "Der Wind ist stark.", "The wind is strong.", "nature", "A2"),
("Wolke", "die", "cloud", "Die Wolke ist dunkel.", "The cloud is dark.", "nature", "A2"),
("Himmel", "der", "sky / heaven", "Der Himmel ist blau.", "The sky is blue.", "nature", "A2"),
("Baum", "der", "tree", "Der Baum ist groß.", "The tree is big.", "nature", "A2"),
("Blume", "die", "flower", "Die Blume ist schön.", "The flower is beautiful.", "nature", "A2"),
("Meer", "das", "sea / ocean", "Das Meer ist blau.", "The sea is blue.", "nature", "A2"),
("Berg", "der", "mountain", "Der Berg ist hoch.", "The mountain is high.", "nature", "A2"),
("See", "der", "lake", "Der See ist tief.", "The lake is deep.", "nature", "A2"),
("Wald", "der", "forest / woods", "Der Wald ist grün.", "The forest is green.", "nature", "A2"),
("Fluss", "der", "river", "Der Fluss ist lang.", "The river is long.", "nature", "A2"),
("Erde", "die", "earth / soil / ground", "Die Erde dreht sich.", "The earth rotates.", "nature", "A2"),

# --- Work ---
("Arbeit", "die", "work / job", "Die Arbeit macht Spaß.", "Work is fun.", "work", "A2"),
("Beruf", "der", "profession / occupation", "Was ist dein Beruf?", "What is your profession?", "work", "A2"),
("Büro", "das", "office", "Ich arbeite im Büro.", "I work in the office.", "work", "A2"),
("Chef", "der", "boss / manager", "Der Chef ist streng.", "The boss is strict.", "work", "A2"),
("Kollege", "der", "colleague (m)", "Mein Kollege ist nett.", "My colleague is nice.", "work", "A2"),
("Geld", "das", "money", "Ich brauche Geld.", "I need money.", "work", "A2"),
("Gehalt", "das", "salary", "Das Gehalt ist gut.", "The salary is good.", "work", "A2"),
("Firma", "die", "company / firm", "Die Firma ist groß.", "The company is big.", "work", "A2"),

# --- Health ---
("Arzt", "der", "doctor (m)", "Der Arzt hilft dem Patienten.", "The doctor helps the patient.", "health", "A2"),
("Ärztin", "die", "doctor (f)", "Die Ärztin ist freundlich.", "The doctor is friendly.", "health", "A2"),
("Krankenhaus", "das", "hospital", "Ich muss ins Krankenhaus.", "I have to go to hospital.", "health", "A2"),
("Schmerz", "der", "pain", "Der Schmerz ist stark.", "The pain is strong.", "health", "A2"),
("Fieber", "das", "fever", "Das Kind hat Fieber.", "The child has a fever.", "health", "A2"),
("Medikament", "das", "medication / medicine", "Das Medikament hilft.", "The medication helps.", "health", "A2"),
("krank", "", "sick / ill", "Ich bin krank.", "I am sick.", "health", "A2"),
("gesund", "", "healthy", "Ich bin gesund.", "I am healthy.", "health", "A2"),

# --- A2 Verbs ---
("fahren", "", "to drive / to travel", "Ich fahre mit dem Auto.", "I travel by car.", "verbs", "A2"),
("fliegen", "", "to fly", "Das Flugzeug fliegt hoch.", "The plane flies high.", "verbs", "A2"),
("arbeiten", "", "to work", "Ich arbeite täglich.", "I work every day.", "verbs", "A2"),
("kochen", "", "to cook", "Ich koche Abendessen.", "I cook dinner.", "verbs", "A2"),
("kaufen", "", "to buy", "Wir kaufen Lebensmittel.", "We buy groceries.", "verbs", "A2"),
("verkaufen", "", "to sell", "Er verkauft sein Auto.", "He sells his car.", "verbs", "A2"),
("helfen", "", "to help", "Kann ich helfen?", "Can I help?", "verbs", "A2"),
("finden", "", "to find", "Ich finde das Buch.", "I find the book.", "verbs", "A2"),
("denken", "", "to think", "Ich denke nach.", "I am thinking.", "verbs", "A2"),
("glauben", "", "to believe / think", "Ich glaube, ja.", "I think so.", "verbs", "A2"),
("zeigen", "", "to show", "Zeig mir den Weg!", "Show me the way!", "verbs", "A2"),
("öffnen", "", "to open", "Öffne die Tür!", "Open the door!", "verbs", "A2"),
("schließen", "", "to close", "Schließ das Fenster!", "Close the window!", "verbs", "A2"),
("warten", "", "to wait", "Wir warten auf den Bus.", "We wait for the bus.", "verbs", "A2"),
("nehmen", "", "to take", "Ich nehme den Zug.", "I take the train.", "verbs", "A2"),
("geben", "", "to give", "Gib mir das Buch!", "Give me the book!", "verbs", "A2"),
("bringen", "", "to bring", "Kannst du Wasser bringen?", "Can you bring water?", "verbs", "A2"),
("treffen", "", "to meet", "Wir treffen uns um 3.", "We meet at 3.", "verbs", "A2"),
("besuchen", "", "to visit", "Ich besuche meine Eltern.", "I visit my parents.", "verbs", "A2"),
("verstehen", "", "to understand", "Ich verstehe die Frage.", "I understand the question.", "verbs", "A2"),

# --- A2 Adjectives ---
("richtig", "", "correct / right", "Die Antwort ist richtig.", "The answer is correct.", "adjectives", "A2"),
("falsch", "", "wrong / false", "Das ist falsch.", "That is wrong.", "adjectives", "A2"),
("einfach", "", "simple / easy", "Die Aufgabe ist einfach.", "The task is simple.", "adjectives", "A2"),
("schwer", "", "heavy / difficult", "Das Buch ist schwer.", "The book is heavy.", "adjectives", "A2"),
("wichtig", "", "important", "Das ist wichtig.", "That is important.", "adjectives", "A2"),
("interessant", "", "interesting", "Das Buch ist interessant.", "The book is interesting.", "adjectives", "A2"),
("lustig", "", "funny / amusing", "Der Film ist lustig.", "The film is funny.", "adjectives", "A2"),
("traurig", "", "sad", "Das Kind ist traurig.", "The child is sad.", "adjectives", "A2"),
("lecker", "", "delicious / tasty", "Das Essen ist lecker.", "The food is delicious.", "adjectives", "A2"),
("teuer", "", "expensive", "Das Auto ist teuer.", "The car is expensive.", "adjectives", "A2"),
("billig", "", "cheap / inexpensive", "Das Hemd ist billig.", "The shirt is cheap.", "adjectives", "A2"),
("sauber", "", "clean", "Das Zimmer ist sauber.", "The room is clean.", "adjectives", "A2"),
("schmutzig", "", "dirty", "Die Schuhe sind schmutzig.", "The shoes are dirty.", "adjectives", "A2"),
("laut", "", "loud / noisy", "Die Musik ist laut.", "The music is loud.", "adjectives", "A2"),
("leise", "", "quiet / soft", "Sei bitte leise!", "Please be quiet!", "adjectives", "A2"),

# ===================== B1 =====================

# --- Emotions & Mind ---
("Gefühl", "das", "feeling / emotion", "Das Gefühl ist unbeschreiblich.", "The feeling is indescribable.", "emotions", "B1"),
("Angst", "die", "fear / anxiety", "Ich habe Angst vor Hunden.", "I am afraid of dogs.", "emotions", "B1"),
("Freude", "die", "joy / happiness", "Ihre Freude war groß.", "Her joy was great.", "emotions", "B1"),
("Liebe", "die", "love", "Liebe macht blind.", "Love is blind.", "emotions", "B1"),
("Stress", "der", "stress", "Ich habe viel Stress.", "I have a lot of stress.", "emotions", "B1"),
("Hoffnung", "die", "hope", "Die Hoffnung stirbt zuletzt.", "Hope dies last.", "emotions", "B1"),
("Wut", "die", "anger / rage", "Er konnte seine Wut nicht kontrollieren.", "He couldn't control his anger.", "emotions", "B1"),
("Einsamkeit", "die", "loneliness", "Einsamkeit kann krank machen.", "Loneliness can make you sick.", "emotions", "B1"),
("Stimmung", "die", "mood / atmosphere", "Die Stimmung ist gut.", "The mood is good.", "emotions", "B1"),
("Vertrauen", "das", "trust / confidence", "Vertrauen ist die Basis.", "Trust is the foundation.", "emotions", "B1"),
("Überraschung", "die", "surprise", "Was für eine Überraschung!", "What a surprise!", "emotions", "B1"),

# --- Society & Environment ---
("Umwelt", "die", "environment", "Wir müssen die Umwelt schützen.", "We must protect the environment.", "nature", "B1"),
("Klima", "das", "climate", "Das Klima verändert sich.", "The climate is changing.", "nature", "B1"),
("Gesellschaft", "die", "society", "Die Gesellschaft verändert sich.", "Society is changing.", "misc", "B1"),
("Bevölkerung", "die", "population", "Die Bevölkerung wächst.", "The population is growing.", "misc", "B1"),
("Regierung", "die", "government", "Die Regierung hat entschieden.", "The government has decided.", "misc", "B1"),
("Gesetz", "das", "law", "Das Gesetz gilt für alle.", "The law applies to everyone.", "misc", "B1"),
("Politik", "die", "politics", "Politik interessiert mich.", "Politics interests me.", "misc", "B1"),
("Wirtschaft", "die", "economy", "Die Wirtschaft wächst.", "The economy is growing.", "work", "B1"),
("Bildung", "die", "education", "Bildung ist sehr wichtig.", "Education is very important.", "school", "B1"),
("Kultur", "die", "culture", "Die Kultur ist vielfältig.", "The culture is diverse.", "misc", "B1"),
("Geschichte", "die", "history / story", "Geschichte ist mein Lieblingsfach.", "History is my favourite subject.", "school", "B1"),
("Wissenschaft", "die", "science", "Die Wissenschaft schreitet voran.", "Science advances.", "school", "B1"),
("Forschung", "die", "research", "Forschung ist wichtig.", "Research is important.", "school", "B1"),

# --- Technology ---
("Computer", "der", "computer", "Der Computer ist kaputt.", "The computer is broken.", "tech", "B1"),
("Internet", "das", "internet", "Das Internet verbindet uns.", "The internet connects us.", "tech", "B1"),
("Handy", "das", "mobile phone", "Mein Handy klingelt.", "My phone is ringing.", "tech", "B1"),
("Programm", "das", "programme / program", "Das Programm startet nicht.", "The programme doesn't start.", "tech", "B1"),
("Daten", "", "data (plural)", "Die Daten werden gespeichert.", "The data is being saved.", "tech", "B1"),
("Technik", "die", "technology / technique", "Moderne Technik ist faszinierend.", "Modern technology is fascinating.", "tech", "B1"),
("Maschine", "die", "machine", "Die Maschine funktioniert.", "The machine works.", "tech", "B1"),
("Energie", "die", "energy", "Wir brauchen mehr Energie.", "We need more energy.", "tech", "B1"),

# --- Sports & Hobbies ---
("Sport", "der", "sport / exercise", "Ich treibe Sport.", "I do sport.", "sports", "B1"),
("Mannschaft", "die", "team", "Die Mannschaft gewinnt.", "The team wins.", "sports", "B1"),
("Spiel", "das", "game / match", "Das Spiel beginnt.", "The game begins.", "sports", "B1"),
("Fußball", "der", "football / soccer", "Fußball ist beliebt.", "Football is popular.", "sports", "B1"),
("Schwimmen", "das", "swimming", "Schwimmen ist gesund.", "Swimming is healthy.", "sports", "B1"),
("Musik", "die", "music", "Ich höre gern Musik.", "I like listening to music.", "misc", "B1"),
("Konzert", "das", "concert", "Das Konzert war toll.", "The concert was great.", "misc", "B1"),
("Film", "der", "film / movie", "Der Film ist spannend.", "The film is exciting.", "misc", "B1"),
("Theater", "das", "theatre", "Wir gehen ins Theater.", "We go to the theatre.", "misc", "B1"),
("Kunst", "die", "art", "Kunst ist schön.", "Art is beautiful.", "misc", "B1"),
("Hobby", "das", "hobby", "Was ist dein Hobby?", "What is your hobby?", "misc", "B1"),

# --- B1 Verbs ---
("erklären", "", "to explain", "Kannst du das erklären?", "Can you explain that?", "verbs", "B1"),
("beschreiben", "", "to describe", "Beschreib das Bild!", "Describe the picture!", "verbs", "B1"),
("entscheiden", "", "to decide", "Ich muss entscheiden.", "I have to decide.", "verbs", "B1"),
("entwickeln", "", "to develop", "Wir entwickeln eine App.", "We are developing an app.", "verbs", "B1"),
("erreichen", "", "to reach / achieve", "Ich will mein Ziel erreichen.", "I want to achieve my goal.", "verbs", "B1"),
("verbessern", "", "to improve", "Ich will mein Deutsch verbessern.", "I want to improve my German.", "verbs", "B1"),
("vergleichen", "", "to compare", "Vergleich die Preise!", "Compare the prices!", "verbs", "B1"),
("bedeuten", "", "to mean / signify", "Was bedeutet das?", "What does that mean?", "verbs", "B1"),
("gehören", "", "to belong to", "Das gehört mir.", "That belongs to me.", "verbs", "B1"),
("entstehen", "", "to arise / develop", "Neues entsteht.", "Something new arises.", "verbs", "B1"),
("verlieren", "", "to lose", "Ich verliere mein Handy oft.", "I often lose my phone.", "verbs", "B1"),
("gewinnen", "", "to win / gain", "Wir wollen gewinnen.", "We want to win.", "verbs", "B1"),
("schützen", "", "to protect", "Wir schützen die Natur.", "We protect nature.", "verbs", "B1"),
("unterstützen", "", "to support", "Kannst du mich unterstützen?", "Can you support me?", "verbs", "B1"),
("vorbereiten", "", "to prepare", "Ich bereite mich vor.", "I am preparing myself.", "verbs", "B1"),

# --- B1 Adjectives ---
("möglich", "", "possible", "Ist das möglich?", "Is that possible?", "adjectives", "B1"),
("notwendig", "", "necessary", "Das ist notwendig.", "That is necessary.", "adjectives", "B1"),
("besonders", "", "special / particularly", "Das ist besonders schön.", "That is especially beautiful.", "adjectives", "B1"),
("verschiedene", "", "various / different", "Es gibt verschiedene Möglichkeiten.", "There are various possibilities.", "adjectives", "B1"),
("gemeinsam", "", "together / shared / common", "Wir lösen das gemeinsam.", "We solve that together.", "adjectives", "B1"),
("öffentlich", "", "public", "Der öffentliche Verkehr ist gut.", "Public transport is good.", "adjectives", "B1"),
("persönlich", "", "personal", "Das ist eine persönliche Frage.", "That is a personal question.", "adjectives", "B1"),
("typisch", "", "typical", "Das ist typisch deutsch.", "That is typically German.", "adjectives", "B1"),
("nützlich", "", "useful", "Das ist sehr nützlich.", "That is very useful.", "adjectives", "B1"),
("gefährlich", "", "dangerous", "Das ist gefährlich.", "That is dangerous.", "adjectives", "B1"),
("zuverlässig", "", "reliable", "Er ist sehr zuverlässig.", "He is very reliable.", "adjectives", "B1"),

# ===================== B2 =====================

("Verantwortung", "die", "responsibility", "Ich trage Verantwortung.", "I bear responsibility.", "misc", "B2"),
("Erfahrung", "die", "experience", "Erfahrung ist wertvoll.", "Experience is valuable.", "work", "B2"),
("Meinung", "die", "opinion", "Meine Meinung ist klar.", "My opinion is clear.", "misc", "B2"),
("Zusammenhang", "der", "connection / context", "Der Zusammenhang ist unklar.", "The context is unclear.", "misc", "B2"),
("Einfluss", "der", "influence", "Sein Einfluss ist groß.", "His influence is great.", "misc", "B2"),
("Folge", "die", "consequence / result", "Die Folgen sind ernst.", "The consequences are serious.", "misc", "B2"),
("Grundlage", "die", "basis / foundation", "Das ist die Grundlage.", "That is the foundation.", "misc", "B2"),
("Herausforderung", "die", "challenge", "Das ist eine Herausforderung.", "That is a challenge.", "misc", "B2"),
("Lösung", "die", "solution", "Wir brauchen eine Lösung.", "We need a solution.", "misc", "B2"),
("Möglichkeit", "die", "possibility / opportunity", "Es gibt viele Möglichkeiten.", "There are many possibilities.", "misc", "B2"),
("Verhältnis", "das", "relationship / ratio", "Das Verhältnis ist gut.", "The relationship is good.", "misc", "B2"),
("Wirkung", "die", "effect / impact", "Die Wirkung ist positiv.", "The effect is positive.", "misc", "B2"),
("Ziel", "das", "goal / aim / destination", "Mein Ziel ist klar.", "My goal is clear.", "misc", "B2"),
("Aufgabe", "die", "task / duty", "Das ist eine schwere Aufgabe.", "That is a difficult task.", "work", "B2"),
("Ansatz", "der", "approach / starting point", "Ein neuer Ansatz ist nötig.", "A new approach is needed.", "misc", "B2"),
("Beziehung", "die", "relationship", "Die Beziehung ist stark.", "The relationship is strong.", "misc", "B2"),
("Entwicklung", "die", "development", "Die Entwicklung ist positiv.", "The development is positive.", "misc", "B2"),
("Leistung", "die", "performance / achievement", "Seine Leistung ist gut.", "His performance is good.", "work", "B2"),
("Bewusstsein", "das", "consciousness / awareness", "Das Bewusstsein wächst.", "Awareness is growing.", "misc", "B2"),
("Eigenschaft", "die", "property / characteristic", "Das ist eine gute Eigenschaft.", "That is a good characteristic.", "misc", "B2"),
("Fähigkeit", "die", "ability / skill", "Sie hat viele Fähigkeiten.", "She has many skills.", "work", "B2"),
("Vorteil", "der", "advantage", "Das ist ein Vorteil.", "That is an advantage.", "misc", "B2"),
("Nachteil", "der", "disadvantage", "Das ist ein Nachteil.", "That is a disadvantage.", "misc", "B2"),
("Unterschied", "der", "difference", "Was ist der Unterschied?", "What is the difference?", "misc", "B2"),
("Ursache", "die", "cause / reason", "Was ist die Ursache?", "What is the cause?", "misc", "B2"),
# B2 Verbs
("analysieren", "", "to analyse", "Wir analysieren die Daten.", "We analyse the data.", "verbs", "B2"),
("beurteilen", "", "to judge / assess", "Man sollte nicht urteilen.", "One should not judge.", "verbs", "B2"),
("berücksichtigen", "", "to take into account", "Das muss man berücksichtigen.", "One must take that into account.", "verbs", "B2"),
("diskutieren", "", "to discuss", "Wir diskutieren das Problem.", "We discuss the problem.", "verbs", "B2"),
("ermöglichen", "", "to enable / make possible", "Das ermöglicht mehr Freiheit.", "That enables more freedom.", "verbs", "B2"),
("feststellen", "", "to determine / establish", "Ich stelle fest, dass...", "I find that...", "verbs", "B2"),
("gestalten", "", "to shape / design", "Wir gestalten die Zukunft.", "We shape the future.", "verbs", "B2"),
("überzeugen", "", "to convince", "Das überzeugt mich.", "That convinces me.", "verbs", "B2"),
("umsetzen", "", "to implement / put into practice", "Wir setzen den Plan um.", "We implement the plan.", "verbs", "B2"),
("vermeiden", "", "to avoid", "Wir vermeiden Fehler.", "We avoid mistakes.", "verbs", "B2"),
("vorschlagen", "", "to suggest / propose", "Ich schlage vor...", "I suggest...", "verbs", "B2"),
("widersprechen", "", "to contradict", "Ich muss widersprechen.", "I must contradict.", "verbs", "B2"),
# B2 Adjectives
("ausreichend", "", "sufficient / adequate", "Das ist ausreichend.", "That is sufficient.", "adjectives", "B2"),
("erheblich", "", "considerable / significant", "Das ist erheblich.", "That is considerable.", "adjectives", "B2"),
("grundlegend", "", "fundamental / basic", "Das ist grundlegend.", "That is fundamental.", "adjectives", "B2"),
("komplex", "", "complex", "Das ist sehr komplex.", "That is very complex.", "adjectives", "B2"),
("nachhaltig", "", "sustainable", "Wir brauchen Nachhaltigkeit.", "We need sustainability.", "adjectives", "B2"),
("vielfältig", "", "diverse / varied", "Die Auswahl ist vielfältig.", "The selection is diverse.", "adjectives", "B2"),
("wesentlich", "", "essential / fundamental", "Das ist wesentlich.", "That is essential.", "adjectives", "B2"),
("zuständig", "", "responsible for / competent", "Wer ist zuständig?", "Who is responsible?", "adjectives", "B2"),
("zuverlässig", "", "reliable / dependable", "Er ist sehr zuverlässig.", "He is very reliable.", "adjectives", "B2"),

# ===================== C1 =====================

("Abkommen", "das", "agreement / treaty", "Das Abkommen wurde unterzeichnet.", "The agreement was signed.", "misc", "C1"),
("Anerkennung", "die", "recognition / acknowledgement", "Er verdient Anerkennung.", "He deserves recognition.", "misc", "C1"),
("Auseinandersetzung", "die", "confrontation / dispute", "Eine Auseinandersetzung entstand.", "A dispute arose.", "misc", "C1"),
("Beeinträchtigung", "die", "impairment / restriction", "Eine Beeinträchtigung liegt vor.", "An impairment exists.", "health", "C1"),
("Durchsetzung", "die", "enforcement / implementation", "Die Durchsetzung ist schwierig.", "Enforcement is difficult.", "misc", "C1"),
("Einschränkung", "die", "restriction / limitation", "Es gibt Einschränkungen.", "There are restrictions.", "misc", "C1"),
("Erscheinung", "die", "appearance / phenomenon", "Das ist eine seltene Erscheinung.", "That is a rare phenomenon.", "misc", "C1"),
("Gewissheit", "die", "certainty", "Das ist keine Gewissheit.", "That is no certainty.", "misc", "C1"),
("Haltung", "die", "posture / attitude / stance", "Seine Haltung ist klar.", "His stance is clear.", "misc", "C1"),
("Kernpunkt", "der", "key point / core issue", "Das ist der Kernpunkt.", "That is the key point.", "misc", "C1"),
("Komplexität", "die", "complexity", "Die Komplexität ist hoch.", "The complexity is high.", "misc", "C1"),
("Nachhaltigkeit", "die", "sustainability", "Nachhaltigkeit ist wichtig.", "Sustainability is important.", "nature", "C1"),
("Perspektive", "die", "perspective / prospect", "Eine neue Perspektive hilft.", "A new perspective helps.", "misc", "C1"),
("Rechtfertigung", "die", "justification", "Eine Rechtfertigung ist nötig.", "A justification is needed.", "misc", "C1"),
("Überzeugung", "die", "conviction / belief", "Das ist meine Überzeugung.", "That is my conviction.", "misc", "C1"),
("Voraussetzung", "die", "prerequisite / requirement", "Das ist eine Voraussetzung.", "That is a prerequisite.", "misc", "C1"),
("Widerspruch", "der", "contradiction / objection", "Das ist ein Widerspruch.", "That is a contradiction.", "misc", "C1"),
("Zusammenarbeit", "die", "cooperation / collaboration", "Die Zusammenarbeit ist wichtig.", "Cooperation is important.", "work", "C1"),
("Zweideutigkeit", "die", "ambiguity", "Zweideutigkeit ist zu vermeiden.", "Ambiguity should be avoided.", "misc", "C1"),
# C1 Verbs
("abwägen", "", "to weigh up / consider", "Man muss die Optionen abwägen.", "One must weigh up the options.", "verbs", "C1"),
("anstreben", "", "to aspire to / aim for", "Sie strebt Perfektion an.", "She aspires to perfection.", "verbs", "C1"),
("aufgreifen", "", "to pick up / address (a topic)", "Er greift das Thema auf.", "He addresses the topic.", "verbs", "C1"),
("beeinflussen", "", "to influence", "Das beeinflusst mich sehr.", "That influences me greatly.", "verbs", "C1"),
("differenzieren", "", "to differentiate", "Man muss differenzieren.", "One must differentiate.", "verbs", "C1"),
("einschränken", "", "to limit / restrict", "Das schränkt uns ein.", "That restricts us.", "verbs", "C1"),
("hervorheben", "", "to highlight / emphasise", "Das möchte ich hervorheben.", "I want to emphasise that.", "verbs", "C1"),
("nachweisen", "", "to prove / demonstrate", "Kannst du das nachweisen?", "Can you prove that?", "verbs", "C1"),
("veranschaulichen", "", "to illustrate / demonstrate", "Das veranschaulicht das Problem.", "That illustrates the problem.", "verbs", "C1"),
("überwiegen", "", "to predominate / outweigh", "Die Vorteile überwiegen.", "The advantages outweigh.", "verbs", "C1"),
# C1 Adjectives
("ausgeprägt", "", "pronounced / marked", "Ein ausgeprägtes Talent.", "A pronounced talent.", "adjectives", "C1"),
("differenziert", "", "differentiated / nuanced", "Eine differenzierte Meinung.", "A nuanced opinion.", "adjectives", "C1"),
("eindeutig", "", "clear / unambiguous", "Das ist eindeutig falsch.", "That is clearly wrong.", "adjectives", "C1"),
("umfassend", "", "comprehensive / extensive", "Eine umfassende Analyse.", "A comprehensive analysis.", "adjectives", "C1"),
("widersprüchlich", "", "contradictory", "Das ist widersprüchlich.", "That is contradictory.", "adjectives", "C1"),
("zutreffend", "", "accurate / applicable", "Das ist zutreffend.", "That is accurate.", "adjectives", "C1"),

# ===================== C2 =====================

("Ambivalenz", "die", "ambivalence", "Ambivalenz kennzeichnet die Situation.", "Ambivalence characterises the situation.", "misc", "C2"),
("Dekonstruktion", "die", "deconstruction", "Die Dekonstruktion von Mythen.", "The deconstruction of myths.", "misc", "C2"),
("Diskrepanz", "die", "discrepancy", "Eine Diskrepanz besteht.", "A discrepancy exists.", "misc", "C2"),
("Episteme", "die", "episteme / body of knowledge", "Die Episteme einer Epoche.", "The episteme of an era.", "misc", "C2"),
("Fragmentierung", "die", "fragmentation", "Die Fragmentierung der Gesellschaft.", "The fragmentation of society.", "misc", "C2"),
("Hegemonie", "die", "hegemony", "Kulturelle Hegemonie ist komplex.", "Cultural hegemony is complex.", "misc", "C2"),
("Kontingenz", "die", "contingency", "Kontingenz bestimmt vieles.", "Contingency determines much.", "misc", "C2"),
("Paradigma", "das", "paradigm", "Ein neues Paradigma entsteht.", "A new paradigm is emerging.", "misc", "C2"),
("Rekontextualisierung", "die", "recontextualisation", "Die Rekontextualisierung ist nötig.", "Recontextualisation is necessary.", "misc", "C2"),
("Selbstreflexion", "die", "self-reflection", "Selbstreflexion ist wichtig.", "Self-reflection is important.", "misc", "C2"),
("Singularität", "die", "singularity", "Die technologische Singularität.", "The technological singularity.", "misc", "C2"),
("Transzendenz", "die", "transcendence", "Transzendenz im Denken.", "Transcendence in thought.", "misc", "C2"),
("Unbestimmtheit", "die", "indeterminacy / vagueness", "Unbestimmtheit ist charakteristisch.", "Indeterminacy is characteristic.", "misc", "C2"),
("Verflechtung", "die", "entanglement / interlinking", "Die Verflechtung ist stark.", "The entanglement is strong.", "misc", "C2"),
("Weltanschauung", "die", "worldview / philosophy of life", "Eine Weltanschauung prägt uns.", "A worldview shapes us.", "misc", "C2"),
# C2 Verbs
("abstrahieren", "", "to abstract / generalise", "Wir müssen abstrahieren.", "We must abstract.", "verbs", "C2"),
("antizipieren", "", "to anticipate", "Das konnte man antizipieren.", "One could anticipate that.", "verbs", "C2"),
("dekonstruieren", "", "to deconstruct", "Er dekonstruiert den Text.", "He deconstructs the text.", "verbs", "C2"),
("exemplifizieren", "", "to exemplify", "Das exemplifiziert das Problem.", "That exemplifies the problem.", "verbs", "C2"),
("kondensieren", "", "to condense", "Die Ideen kondensieren.", "The ideas condense.", "verbs", "C2"),
("nuancieren", "", "to nuance / qualify", "Man muss nuancieren.", "One must nuance.", "verbs", "C2"),
("problematisieren", "", "to problematise", "Das wird problematisiert.", "That is being problematised.", "verbs", "C2"),
("synthetisieren", "", "to synthesise", "Wir synthetisieren die Erkenntnisse.", "We synthesise the findings.", "verbs", "C2"),
# C2 Adjectives
("ambivalent", "", "ambivalent", "Eine ambivalente Haltung.", "An ambivalent stance.", "adjectives", "C2"),
("ephemer", "", "ephemeral / fleeting", "Ein ephemeres Phänomen.", "An ephemeral phenomenon.", "adjectives", "C2"),
("paradox", "", "paradoxical", "Das ist paradox.", "That is paradoxical.", "adjectives", "C2"),
("präzedenzlos", "", "unprecedented", "Eine präzedenzlose Situation.", "An unprecedented situation.", "adjectives", "C2"),
("subversiv", "", "subversive", "Ein subversiver Akt.", "A subversive act.", "adjectives", "C2"),

# Extra common words to round up to ~2500
("Adresse", "die", "address", "Was ist deine Adresse?", "What is your address?", "misc", "A1"),
("Nummer", "die", "number", "Meine Nummer ist...", "My number is...", "misc", "A1"),
("Name", "der", "name", "Wie ist dein Name?", "What is your name?", "misc", "A1"),
("Problem", "das", "problem", "Das ist kein Problem.", "That is no problem.", "misc", "A1"),
("Idee", "die", "idea", "Das ist eine gute Idee.", "That is a good idea.", "misc", "A1"),
("Frage", "die", "question", "Ich habe eine Frage.", "I have a question.", "misc", "A1"),
("Antwort", "die", "answer", "Die Antwort ist richtig.", "The answer is correct.", "misc", "A1"),
("Wort", "das", "word", "Ich kenne das Wort nicht.", "I don't know the word.", "school", "A1"),
("Sprache", "die", "language / speech", "Deutsch ist eine schöne Sprache.", "German is a beautiful language.", "school", "A1"),
("Satz", "der", "sentence / set", "Schreib einen Satz!", "Write a sentence!", "school", "A1"),
("Brief", "der", "letter (written)", "Ich schreibe einen Brief.", "I write a letter.", "misc", "A1"),
("Foto", "das", "photo / photograph", "Das Foto ist schön.", "The photo is beautiful.", "misc", "A1"),
("Musik", "die", "music", "Musik macht glücklich.", "Music makes you happy.", "misc", "A1"),
("Film", "der", "film / movie", "Der Film ist gut.", "The film is good.", "misc", "A1"),
("Sport", "der", "sport", "Sport ist gesund.", "Sport is healthy.", "sports", "A1"),
("Spiel", "das", "game / play", "Das Spiel macht Spaß.", "The game is fun.", "sports", "A1"),
("Garten", "der", "garden", "Der Garten ist groß.", "The garden is big.", "home", "A1"),
("Park", "der", "park", "Wir gehen in den Park.", "We go to the park.", "travel", "A1"),
("Markt", "der", "market", "Der Markt ist bunt.", "The market is colourful.", "travel", "A1"),
("Supermarkt", "der", "supermarket", "Ich gehe zum Supermarkt.", "I go to the supermarket.", "travel", "A2"),
("Restaurant", "das", "restaurant", "Das Restaurant ist voll.", "The restaurant is full.", "food", "A1"),
("Café", "das", "café", "Wir treffen uns im Café.", "We meet at the café.", "food", "A1"),
("Schule", "die", "school", "Die Schule beginnt um 8.", "School starts at 8.", "school", "A1"),
("Universität", "die", "university", "Ich studiere an der Universität.", "I study at university.", "school", "A2"),
("Student", "der", "student (m)", "Der Student lernt viel.", "The student studies a lot.", "school", "A2"),
("Studentin", "die", "student (f)", "Die Studentin ist klug.", "The student is clever.", "school", "A2"),
("Zeitung", "die", "newspaper", "Ich lese die Zeitung.", "I read the newspaper.", "misc", "A2"),
("Nachrichten", "", "news (plural)", "Ich höre die Nachrichten.", "I listen to the news.", "misc", "A2"),
("Internet", "das", "internet", "Ich nutze das Internet.", "I use the internet.", "tech", "A2"),
("Seite", "die", "page / side / website", "Öffne die nächste Seite.", "Open the next page.", "misc", "A2"),
("Fehler", "der", "mistake / error", "Ich mache keinen Fehler.", "I make no mistake.", "misc", "A2"),
("Erfolg", "der", "success", "Das ist ein Erfolg!", "That is a success!", "misc", "B1"),
("Chance", "die", "chance / opportunity", "Das ist eine gute Chance.", "That is a good chance.", "misc", "B1"),
("Plan", "der", "plan", "Was ist der Plan?", "What is the plan?", "misc", "A2"),
("Projekt", "das", "project", "Das Projekt ist fertig.", "The project is finished.", "work", "B1"),
("Termin", "der", "appointment / date", "Ich habe einen Termin.", "I have an appointment.", "work", "A2"),
("Stunde", "die", "lesson / hour", "Die Stunde beginnt.", "The lesson begins.", "school", "A1"),
("Kurs", "der", "course", "Ich mache einen Kurs.", "I am taking a course.", "school", "A2"),
("Übung", "die", "exercise / practice", "Die Übung ist schwer.", "The exercise is difficult.", "school", "A2"),
("Test", "der", "test", "Der Test war leicht.", "The test was easy.", "school", "A2"),
("Prüfung", "die", "exam", "Ich habe Prüfung morgen.", "I have an exam tomorrow.", "school", "B1"),
("Note", "die", "grade / note", "Ich habe eine gute Note.", "I have a good grade.", "school", "A2"),
("Wörterbuch", "das", "dictionary", "Das Wörterbuch hilft mir.", "The dictionary helps me.", "school", "A2"),
("Grammatik", "die", "grammar", "Grammatik ist wichtig.", "Grammar is important.", "school", "A2"),
("Aussprache", "die", "pronunciation", "Die Aussprache ist schwierig.", "Pronunciation is difficult.", "school", "B1"),
("Vokabular", "das", "vocabulary", "Mein Vokabular wächst.", "My vocabulary is growing.", "school", "B1"),
("Übersetzung", "die", "translation", "Die Übersetzung ist gut.", "The translation is good.", "school", "B1"),
("Bedeutung", "die", "meaning / significance", "Was ist die Bedeutung?", "What is the meaning?", "school", "B1"),
("Beispiel", "das", "example", "Gib mir ein Beispiel!", "Give me an example!", "school", "A2"),
("Regel", "die", "rule", "Die Regel ist klar.", "The rule is clear.", "misc", "A2"),
("Situation", "die", "situation", "Die Situation ist ernst.", "The situation is serious.", "misc", "B1"),
("Thema", "das", "topic / theme", "Was ist das Thema?", "What is the topic?", "misc", "B1"),
("Inhalt", "der", "content / contents", "Der Inhalt ist gut.", "The content is good.", "misc", "B1"),
("Form", "die", "form / shape", "Die Form ist rund.", "The shape is round.", "misc", "B1"),
("Art", "die", "type / kind / way", "Was für eine Art?", "What kind of?", "misc", "B1"),
("Fall", "der", "case / fall", "In diesem Fall ja.", "In this case, yes.", "misc", "B1"),
("Grund", "der", "reason / ground", "Was ist der Grund?", "What is the reason?", "misc", "B1"),
("Teil", "der", "part / section", "Ein Teil ist fertig.", "One part is finished.", "misc", "A2"),
("System", "das", "system", "Das System funktioniert.", "The system works.", "tech", "B1"),
("Struktur", "die", "structure", "Die Struktur ist klar.", "The structure is clear.", "misc", "B2"),
("Prozess", "der", "process", "Der Prozess läuft.", "The process is running.", "misc", "B2"),
("Ergebnis", "das", "result / outcome", "Das Ergebnis ist positiv.", "The result is positive.", "misc", "B1"),
("Wert", "der", "value / worth", "Das hat Wert.", "That has value.", "misc", "B1"),
("Preis", "der", "price / prize", "Der Preis ist hoch.", "The price is high.", "work", "A2"),
("Qualität", "die", "quality", "Die Qualität ist gut.", "The quality is good.", "work", "B1"),
("Methode", "die", "method", "Eine neue Methode hilft.", "A new method helps.", "misc", "B2"),
("Konzept", "das", "concept", "Das Konzept ist neu.", "The concept is new.", "misc", "B2"),
("Modell", "das", "model", "Das Modell ist veraltet.", "The model is outdated.", "misc", "B2"),
("Theorie", "die", "theory", "Die Theorie stimmt.", "The theory is correct.", "school", "B2"),
("Praxis", "die", "practice", "Theorie und Praxis differ.", "Theory and practice differ.", "misc", "B2"),
("Erkenntnis", "die", "insight / finding", "Eine wichtige Erkenntnis.", "An important finding.", "misc", "C1"),
("Sichtweise", "die", "viewpoint / perspective", "Meine Sichtweise ist anders.", "My viewpoint is different.", "misc", "B2"),
("Standpunkt", "der", "standpoint / position", "Mein Standpunkt ist klar.", "My standpoint is clear.", "misc", "B2"),
("Argument", "das", "argument", "Das Argument ist überzeugend.", "The argument is convincing.", "misc", "B2"),
("Kritik", "die", "criticism / critique", "Die Kritik ist berechtigt.", "The criticism is justified.", "misc", "B2"),
("Debatte", "die", "debate", "Die Debatte ist hitzig.", "The debate is heated.", "misc", "B2"),
("Dialog", "der", "dialogue", "Ein Dialog ist nötig.", "A dialogue is needed.", "misc", "B2"),
("Kommunikation", "die", "communication", "Kommunikation ist wichtig.", "Communication is important.", "misc", "B2"),
("Information", "die", "information", "Diese Information ist neu.", "This information is new.", "misc", "B1"),
("Wissen", "das", "knowledge", "Wissen ist Macht.", "Knowledge is power.", "school", "B1"),
("Kenntnis", "die", "knowledge / awareness", "Ohne Kenntnis geht es nicht.", "Without knowledge it doesn't work.", "school", "B2"),
("Kompetenz", "die", "competence / skill", "Die Kompetenz ist hoch.", "The competence is high.", "work", "B2"),
("Kapazität", "die", "capacity", "Die Kapazität ist voll.", "The capacity is full.", "misc", "C1"),
("Ressource", "die", "resource", "Ressourcen sind begrenzt.", "Resources are limited.", "misc", "B2"),
("Strategie", "die", "strategy", "Die Strategie ist gut.", "The strategy is good.", "work", "B2"),
("Initiative", "die", "initiative", "Er hat Initiative.", "He shows initiative.", "work", "B2"),
("Innovation", "die", "innovation", "Innovation ist wichtig.", "Innovation is important.", "work", "B2"),
("Transformation", "die", "transformation", "Eine Transformation findet statt.", "A transformation is taking place.", "misc", "C1"),
("Integration", "die", "integration", "Integration ist ein Prozess.", "Integration is a process.", "misc", "B2"),
("Kooperation", "die", "cooperation", "Kooperation ist nötig.", "Cooperation is needed.", "work", "B2"),
("Kommunikation", "die", "communication", "Gute Kommunikation hilft.", "Good communication helps.", "misc", "B1"),
("Präsentation", "die", "presentation", "Die Präsentation war toll.", "The presentation was great.", "work", "B2"),
("Konferenz", "die", "conference", "Eine Konferenz findet statt.", "A conference is taking place.", "work", "B2"),
("Seminar", "das", "seminar", "Das Seminar war lehrreich.", "The seminar was educational.", "school", "B2"),
("Zeichen", "das", "sign / symbol / character", "Das ist ein gutes Zeichen.", "That is a good sign.", "misc", "B1"),
("Symbol", "das", "symbol", "Das Symbol hat Bedeutung.", "The symbol has meaning.", "misc", "B2"),
("Kontext", "der", "context", "Im Kontext verstanden.", "Understood in context.", "misc", "B2"),
("Dimension", "die", "dimension", "Das hat viele Dimensionen.", "That has many dimensions.", "misc", "C1"),
("Ebene", "die", "level / plane", "Auf einer anderen Ebene.", "On a different level.", "misc", "B2"),
("Rahmen", "der", "frame / framework", "Im Rahmen des Projekts.", "Within the framework of the project.", "misc", "B2"),
("Aspekt", "der", "aspect", "Dieser Aspekt ist wichtig.", "This aspect is important.", "misc", "B2"),
("Faktor", "der", "factor", "Ein entscheidender Faktor.", "A decisive factor.", "misc", "B2"),
("Element", "das", "element", "Ein wichtiges Element.", "An important element.", "misc", "B2"),
("Komponente", "die", "component", "Eine wesentliche Komponente.", "An essential component.", "misc", "C1"),
("Variable", "die", "variable", "Die Variable ändert sich.", "The variable changes.", "misc", "C1"),
("Parameter", "der", "parameter", "Der Parameter ist fix.", "The parameter is fixed.", "misc", "C1"),
("Konstante", "die", "constant", "Die Konstante bleibt.", "The constant remains.", "misc", "C1"),
("Tendenz", "die", "tendency / trend", "Eine steigende Tendenz.", "An increasing tendency.", "misc", "B2"),
("Trend", "der", "trend", "Der Trend geht aufwärts.", "The trend is upward.", "misc", "B2"),
("Phänomen", "das", "phenomenon", "Ein interessantes Phänomen.", "An interesting phenomenon.", "misc", "B2"),
("Dynamik", "die", "dynamics", "Die Dynamik ist spürbar.", "The dynamics are noticeable.", "misc", "C1"),
("Potential", "das", "potential", "Das Potential ist groß.", "The potential is great.", "misc", "B2"),
("Kapital", "das", "capital", "Kapital ist notwendig.", "Capital is necessary.", "work", "B2"),
("Investition", "die", "investment", "Die Investition lohnt sich.", "The investment pays off.", "work", "B2"),
("Risiko", "das", "risk", "Das Risiko ist hoch.", "The risk is high.", "misc", "B2"),
("Sicherheit", "die", "security / safety / certainty", "Sicherheit geht vor.", "Safety comes first.", "misc", "B1"),
("Freiheit", "die", "freedom / liberty", "Freiheit ist wertvoll.", "Freedom is valuable.", "misc", "B1"),
("Recht", "das", "right / law", "Das ist mein Recht.", "That is my right.", "misc", "B1"),
("Pflicht", "die", "duty / obligation", "Das ist meine Pflicht.", "That is my duty.", "misc", "B2"),
("Gleichheit", "die", "equality", "Gleichheit ist ein Ziel.", "Equality is a goal.", "misc", "B2"),
("Gerechtigkeit", "die", "justice", "Gerechtigkeit ist wichtig.", "Justice is important.", "misc", "B2"),
("Solidarität", "die", "solidarity", "Solidarität ist nötig.", "Solidarity is needed.", "misc", "C1"),
("Toleranz", "die", "tolerance", "Toleranz ist eine Tugend.", "Tolerance is a virtue.", "misc", "B2"),
("Respekt", "der", "respect", "Respekt ist wichtig.", "Respect is important.", "misc", "B1"),
("Verständnis", "das", "understanding / comprehension", "Ich habe Verständnis.", "I have understanding.", "misc", "B1"),
("Empathie", "die", "empathy", "Empathie ist wichtig.", "Empathy is important.", "emotions", "C1"),
("Mitgefühl", "das", "compassion / sympathy", "Mitgefühl hilft.", "Compassion helps.", "emotions", "B2"),
("Kreativität", "die", "creativity", "Kreativität ist gefragt.", "Creativity is in demand.", "misc", "B2"),
("Fantasie", "die", "fantasy / imagination", "Kinder haben viel Fantasie.", "Children have a lot of imagination.", "misc", "A2"),
("Wirklichkeit", "die", "reality", "Die Wirklichkeit ist anders.", "Reality is different.", "misc", "B2"),
("Wahrheit", "die", "truth", "Die Wahrheit liegt dazwischen.", "The truth lies in between.", "misc", "B1"),
("Lüge", "die", "lie / falsehood", "Das ist eine Lüge.", "That is a lie.", "misc", "B1"),
("Geheimnis", "das", "secret / mystery", "Das ist ein Geheimnis.", "That is a secret.", "misc", "B1"),
("Erklärung", "die", "explanation / declaration", "Die Erklärung ist klar.", "The explanation is clear.", "misc", "B1"),
("Beweis", "der", "proof / evidence", "Der Beweis fehlt.", "The proof is missing.", "misc", "B2"),
("Ursache", "die", "cause", "Die Ursache ist unbekannt.", "The cause is unknown.", "misc", "B1"),
("Wirkung", "die", "effect / impact", "Die Wirkung ist stark.", "The effect is strong.", "misc", "B1"),
("Konsequenz", "die", "consequence", "Die Konsequenz ist ernst.", "The consequence is serious.", "misc", "B2"),
("Reaktion", "die", "reaction", "Die Reaktion war positiv.", "The reaction was positive.", "misc", "B2"),
("Anpassung", "die", "adaptation / adjustment", "Eine Anpassung ist nötig.", "An adjustment is needed.", "misc", "B2"),
("Veränderung", "die", "change", "Eine Veränderung kommt.", "A change is coming.", "misc", "B1"),
("Wachstum", "das", "growth", "Wachstum ist begrenzt.", "Growth is limited.", "misc", "B2"),
("Rückgang", "der", "decline / decrease", "Ein Rückgang ist spürbar.", "A decline is noticeable.", "misc", "B2"),
("Fortschritt", "der", "progress", "Fortschritt ist sichtbar.", "Progress is visible.", "misc", "B2"),
("Rückschritt", "der", "setback / regression", "Das ist ein Rückschritt.", "That is a regression.", "misc", "C1"),
("Wandel", "der", "change / transformation", "Der Wandel kommt.", "Change is coming.", "misc", "B2"),
("Übergang", "der", "transition", "Ein Übergang findet statt.", "A transition is taking place.", "misc", "C1"),
("Phase", "die", "phase / stage", "In dieser Phase...", "In this phase...", "misc", "B2"),
("Stadium", "das", "stage / stadium", "In einem frühen Stadium.", "At an early stage.", "misc", "C1"),
("Schritt", "der", "step", "Ein kleiner Schritt.", "A small step.", "misc", "B1"),
("Maßnahme", "die", "measure / action", "Eine Maßnahme ist nötig.", "A measure is necessary.", "misc", "B2"),
("Entscheidung", "die", "decision", "Die Entscheidung ist gefallen.", "The decision has been made.", "misc", "B1"),
("Wahl", "die", "choice / election", "Das ist meine Wahl.", "That is my choice.", "misc", "B1"),
("Option", "die", "option", "Es gibt zwei Optionen.", "There are two options.", "misc", "B2"),
("Alternative", "die", "alternative", "Eine Alternative ist nötig.", "An alternative is needed.", "misc", "B2"),
("Priorität", "die", "priority", "Das ist Priorität.", "That is a priority.", "misc", "C1"),
("Kriterium", "das", "criterion", "Das Kriterium ist erfüllt.", "The criterion is met.", "misc", "C1"),
("Standard", "der", "standard", "Der Standard ist hoch.", "The standard is high.", "misc", "B2"),
("Niveau", "das", "level / standard", "Das Niveau ist gut.", "The level is good.", "misc", "B2"),
("Qualifikation", "die", "qualification", "Die Qualifikation fehlt.", "The qualification is missing.", "work", "B2"),
("Verpflichtung", "die", "obligation / commitment", "Eine Verpflichtung eingehen.", "To enter an obligation.", "misc", "C1"),
("Vereinbarung", "die", "agreement / arrangement", "Eine Vereinbarung treffen.", "To make an arrangement.", "misc", "B2"),
("Vertrag", "der", "contract / treaty", "Der Vertrag ist unterschrieben.", "The contract is signed.", "work", "B2"),
("Regelung", "die", "regulation / arrangement", "Eine Regelung ist nötig.", "A regulation is needed.", "misc", "C1"),
("Vorschrift", "die", "regulation / rule", "Die Vorschrift gilt.", "The regulation applies.", "misc", "B2"),
("Norm", "die", "norm / standard", "Die Norm ist festgelegt.", "The norm is established.", "misc", "B2"),
("Prinzip", "das", "principle", "Das Prinzip gilt.", "The principle applies.", "misc", "B2"),
("Wert", "der", "value", "Das ist ein Grundwert.", "That is a core value.", "misc", "B1"),
("Einstellung", "die", "attitude / setting", "Die Einstellung ist positiv.", "The attitude is positive.", "misc", "B2"),
("Überzeugung", "die", "conviction", "Ich handle nach meiner Überzeugung.", "I act according to my conviction.", "misc", "B2"),
("Geist", "der", "spirit / mind / ghost", "Der Geist ist bereit.", "The spirit is willing.", "misc", "B1"),
("Seele", "die", "soul", "Die Seele braucht Ruhe.", "The soul needs rest.", "misc", "B1"),
("Körper", "der", "body", "Körper und Geist.", "Body and mind.", "body", "A2"),
("Gesundheit", "die", "health", "Gesundheit ist alles.", "Health is everything.", "health", "A2"),
("Krankheit", "die", "illness / disease", "Eine Krankheit schwächt.", "An illness weakens.", "health", "B1"),
("Heilung", "die", "healing / cure", "Die Heilung dauert.", "The healing takes time.", "health", "B1"),
("Pflege", "die", "care / nursing", "Pflege ist wichtig.", "Care is important.", "health", "B1"),
("Ernährung", "die", "nutrition / diet", "Ernährung ist wichtig.", "Nutrition is important.", "health", "B1"),
("Bewegung", "die", "movement / exercise", "Bewegung hält fit.", "Exercise keeps you fit.", "health", "B1"),
("Entspannung", "die", "relaxation", "Entspannung ist wichtig.", "Relaxation is important.", "health", "B1"),
("Schlaf", "der", "sleep", "Schlaf ist wichtig.", "Sleep is important.", "health", "A2"),
("Ruhe", "die", "rest / calm / quiet", "Ich brauche Ruhe.", "I need quiet.", "misc", "A2"),
("Konzentration", "die", "concentration", "Volle Konzentration!", "Full concentration!", "misc", "B1"),
("Aufmerksamkeit", "die", "attention", "Aufmerksamkeit ist gefragt.", "Attention is required.", "misc", "B2"),
("Gedanke", "der", "thought", "Ein guter Gedanke.", "A good thought.", "misc", "B1"),
("Vorstellung", "die", "imagination / idea / performance", "Meine Vorstellung ist...", "My idea is...", "misc", "B1"),
("Erinnerung", "die", "memory / recollection", "Eine schöne Erinnerung.", "A beautiful memory.", "misc", "B1"),
("Vergessen", "das", "forgetting", "Vergessen ist manchmal gut.", "Forgetting is sometimes good.", "misc", "B2"),
("Lernen", "das", "learning", "Lernen macht Spaß.", "Learning is fun.", "school", "A1"),
("Verstehen", "das", "understanding", "Verstehen braucht Zeit.", "Understanding takes time.", "school", "A2"),
("Erkennen", "das", "recognition / realisation", "Erkennen ist der erste Schritt.", "Recognition is the first step.", "misc", "B2"),
]
